import type { Text } from "@/i18n/overlay";
import type { Occasion } from "../bingo";

/*
 * Dziaders bingo. Keyed by the occasion slug, which stays Polish because it is part of every card
 * code. Squares are drawn from the pool by index, so each pool keeps the Polish length and order:
 * the same card code gives the same squares in both editions. Under ~45 characters each.
 */

export const OCCASIONS: Record<string, Text<Occasion, "slug">> = {
  wesele: {
    name: "Svatba",
    title: "Svatbeni bingo",
    intro: "Od oczepin¹ do poprawin². Najbolje se igra za mizo stricev, daleč od ansambla.",
    notes: [
      "¹ Oczepiny: polnočni obred poljske svatbe, ko nevesti snamejo tančico, svatje pa igrajo družabne igre. Na Slovenskem so mu nekoč rekli čepljenje.",
      "² Poprawiny: drugi dan svatbe, ko se svatje vrnejo in pojedo, kar je ostalo.",
    ],
    squares: [
      "Stric pleše s kravato na glavi",
      "»Gorzko!« in poljub še pred juho",
      "»Moja ohcet je trajala tri dni«",
      "»To ni muzika«",
      "Na glas: kdo je koliko dal v kuverto",
      "Suknjič slečen pred 21.00",
      "Stric uči natakarja točiti",
      "»Kdaj pa kaj otroci?«",
      "Pecivo v prtičku za domov",
      "Vprašanje, koliko je stala dvorana",
      "Prepir, kod bi bilo hitreje",
      "Nekdo snema celo svatbo navpično",
      "Stric pleše sam. S strastjo.",
      "Govor brez povabila",
      "»V gasilskem domu je bil zrezek boljši«",
      "Prošnja DJ-ju: tišje. Potem: glasneje",
      "Račji ples, odplesan smrtno resno",
      "Skupinsko slikanje traja dvajset minut",
      "Spor o sedežu za mizo",
      "Stric preveri, ali je juha vroča",
      "»Jaz sem tu samo na hitro«, ura 4.00",
      "Tretja različica, kako sta se spoznala",
      "Telefonski pogovor na zvočniku",
      "Vprašanje, ali je še kaj bigosa",
      "Čevlji sezuti pod mizo",
      "Stric pleše z vsemi tetami po vrsti",
      "»Jaz bi to drugače zrihtal«",
      "Preverjanje rezultata tekme pod mizo",
      "»Včasih je igral ansambel, ne DJ«",
      "Prvi ples, ocenjen na glas",
      "Rože z mize odnesene domov",
      "Zdravica, daljša od poroke",
      "Kravata v žepu suknjiča",
      "Natakarja vprašajo, od kod je juha",
    ],
  },
  wigilia: {
    name: "Sveti večer",
    title: "Svetovečerni bingo",
    intro: "Od prve zvezdice¹ do dremeža po makovi potici. Listke razdeli po boršču.",
    notes: [
      "¹ Prva zvezdica: ko zasije, se na Poljskem začne večerja svetega večera, dvanajst postnih jedi in prazen pogrinjek za popotnika. Glavna jed je krap, ki pred tem nekaj dni plava v kadi.",
    ],
    squares: [
      "»Pri mami je bil krap boljši«",
      "Krapova luska v denarnici, »za denar«",
      "»Kdaj pa kaj poroka?«",
      "Dremež po boršču",
      "Spor: ušesca z gobami ali z zeljem",
      "Stric šteje, ali je res dvanajst jedi",
      "»Bom vam jaz povedal, kako je«",
      "Navodila za darilo, prebrana na glas",
      "Televizor prižgan »samo za malo«",
      "»V mojih časih je bil še pravi sneg«",
      "Prvo zvezdico čakajo z uro v roki",
      "Zgodba o koščicah ob vsakem grižljaju",
      "Darilo: nogavice. Spet.",
      "»Kdo je pa toliko tega pripravil?«",
      "Hrana, zapakirana za domov",
      "Razprava o cenah krapa",
      "Dremež v fotelju z daljincem v roki",
      "Kompot iz suhega sadja: pol jih pije, pol ne",
      "»Letos je pa malo snega«",
      "Podrobna vprašanja o službi",
      "Voščilo, posneto s telefonom navpično",
      "Darilo z računom, »za zamenjavo«",
      "»Pirogi so malo pretrdi«",
      "Daljinec v plastični vrečki",
      "»Jaz pa ne rabim nič več«",
      "Nekdo sede k pogrinjku za popotnika",
      "Spor, kdo deli darila",
      "»Včasih so bile jelke prave«",
      "Slanik na tri načine, vsak »najboljši«",
      "Voščilo po telefonu, na zvočniku",
      "Makova potica izgine pred večerjo",
      "»Hrane bo dovolj do silvestrovega«",
      "Vprašanje, ali je krap plaval v kadi",
      "Pogovor o tem, kdo pride na štefanovo",
    ],
  },
  majowka: {
    name: "Podaljšani vikend",
    title: "Prvomajski bingo",
    intro: "Žar, vrtiček, vremenska napoved vsake četrt ure. Igre je konec, ko začne deževati.",
    squares: [
      "Kurjenje brez podžigalnega gela",
      "Spor, kdaj obrniti vratovino",
      "»Letos je pa mrzel prvi maj«",
      "Lasten žar, ker se »na tem ne da«",
      "Napoved, preverjena vsake četrt ure",
      "Zgodba o zastoju na cesti v Zakopane",
      "Predpasnik »Mojster žara«",
      "Klobasa prismojena »nalašč«",
      "Pihanje v oglje do onemoglosti",
      "»Pri nas na vrtičku je bolje«",
      "Deset minut razpiranja ležalnika",
      "Prepir o glasbi iz zvočnika",
      "Francoska solata v maju",
      "Pogovor o komarjih",
      "Vreča oglja je vseeno premajhna",
      "Sosed kuka čez ograjo",
      "Ocena tujega žara",
      "Dež točno ob 15.00",
      "»Jaz bi šel v hribe«",
      "Nabodala brez zelenjave",
      "Dremež s časopisom na obrazu",
      "Pogovor o ceni goriva",
      "Sosedova kosilnica ob 8.00",
      "Prijemalka, pozabljena na rešetki",
      "Dve gorčici in spor o tretji",
      "»Vratovina mora počivati«",
      "Aluminijasta folija na rešetki",
      "Koliko je stal žar, s podrobnostmi",
      "Predavanje o kurjenju ognja",
      "Jakna oblečena ob 18.00",
      "Načrt za jutri: isto",
      "Žar očiščen šele junija",
    ],
  },
  morze: {
    name: "Na morju",
    title: "Plažni bingo",
    intro: "Od vetrobrana¹ ob zori do vafljev ob sončnem zahodu. Igra se med valobrani.",
    notes: [
      "¹ Vetrobran: platnena ograda, s katero si poljski kopalec ob zori ogradi svoj kos baltske plaže. Na Jadranu to nalogo opravlja brisača.",
    ],
    squares: [
      "Vetrobran postavljen pred 7.00",
      "Nogavice v sandalih",
      "»Za ta denar bi bil v Grčiji …«",
      "Voda »osvežujoča«, 14 stopinj",
      "Pritoževanje nad ceno vafljev",
      "Parkiranje za 30 zł in komentar",
      "Sendviči z jajcem na plaži",
      "Časopis na obrazu med sončenjem",
      "Galeb ukrade krompirček",
      "»Tukaj piha, selimo se«",
      "Petnajst minut razpiranja ležalnika",
      "Radio na plaži",
      "Kopalke iz leta 1998",
      "Spor o prostoru za vetrobran",
      "»Baltik je najbolj zdravo morje«",
      "Nekdo zakopan v pesek do vratu",
      "Napihovanje blazine z usti",
      "Školjka z napisom »Pozdrav z morja«",
      "Budnica ob 5.30, »da ne zamudimo«",
      "Pasna torbica z dokumenti na trebuhu",
      "Štirideseta fotografija sončnega zahoda",
      "Ocena ocvrte ribe s stojnice",
      "Stric plava »do boje« in nazaj",
      "»Jutri bo boljše vreme«",
      "Prepir, kdo pazi na stvari",
      "Brisača, puščena čez noč",
      "»Na Helu je bolje«",
      "Pogovor s sosedom izza vetrobrana",
      "Vetrobran, sposojen od soseda",
      "Temperatura vode, preverjena v aplikaciji",
      "Klobuk, kupljen na promenadi",
      "Zagorelost v obliki majice",
    ],
  },
  imieniny: {
    name: "Godovanje",
    title: "Godovni bingo",
    intro: "Od copat v predsobi do slovesa v predsobi. Listke razdeli po prvem »Sto lat«¹.",
    notes: ["¹ Sto lat: poljska napitnica slavljencu, naj živi sto let. Slovenski ustreznik je »Kolikor kapljic, toliko let«."],
    squares: [
      "»Ne sezuvajte se!« Vsi se sezujejo",
      "Copati za goste, dve številki premajhni",
      "Francoska solata v kristalni skledi",
      "Osvetljen bar v regalu",
      "Stric potrka po regalu: »Masiva!«",
      "Pet ljudi na kavču za tri",
      "Stoli, sposojeni od sosedov",
      "Kuhinjski stolček za najmlajšega",
      "Televizor ves večer prižgan, brez zvoka",
      "»Sto lat« zapojejo previsoko",
      "Drugič »Sto lat«, ker je nekdo zamudil",
      "Vilice ob kozarec: stric prosi za tišino",
      "»Samo dve besedi«. Govori pol ure",
      "»Kako pa kaj v službi?«",
      "»Koliko ti pa plačajo? Neto?«",
      "Tuja plača, izračunana na prtičku",
      "»Pri tvojih letih sem že imel stanovanje«",
      "Primerjanje položnic za ogrevanje",
      "Žolca: je jo samo stric",
      "Na prtu povoščeno platno, »da se ne umaže«",
      "Iskanje vaze za tretji šopek",
      "Bonboniera z lanskega godovanja",
      "»Rojstni dan? Pri nas se je praznoval god«",
      "»Kje si parkiral? Tam se ne sme«",
      "Posvet moških na balkonu",
      "Kozarčki iz treh različnih kompletov",
      "Čaj v kozarcu z držalom",
      "Sosed potrka po radiatorju ob 22.00",
      "Poslavljanje v predsobi traja uro",
      "»Daj izvijač, bom to takoj privil«",
      "»Kdo vam je pa te ploščice polagal?«",
      "Torta pride, ko nihče ne more več",
      "Spor, ali gre v solato jabolko",
      "Album s fotografijami po torti",
    ],
  },
  podroz: {
    name: "Z avtom na pot",
    title: "Potovalni bingo",
    intro: "Od pakiranja prtljažnika do črpalke, ki bo »vsak čas«. Igra se na zadnjem sedežu, potiho.",
    squares: [
      "»Kdo je odprl okno?«",
      "»Vsak čas bo črpalka«, že sto kilometrov",
      "»Tu je bila včasih luknja«",
      "»Ne prehitevaj me« in doda plin",
      "Navigacija utišana po tretjem »obrnite«",
      "Avtomobilski atlas iz leta 1997",
      "Sendviči v srebrnem papirju",
      "Trdo kuhana jajca in sol v papirčku",
      "»Glej, kako ta vozi«",
      "»Vozniško je pa najbrž dobil v čipsu«",
      "Ocena voznikov po registrski tablici",
      "»Kdor vozi, ta izbira radio«",
      "Radio prasketa, ampak »zdaj bo ujelo«",
      "Povprečna hitrost, sporočena vsako uro",
      "»Lulat pred odhodom, ker se ne ustavljamo«",
      "»Po zadrgi? Naj stoji kot vsi drugi«",
      "Po levem pasu vse od Lodža",
      "Utripanje z dolgimi: »za ovinkom merijo«",
      "Klima izklopljena, »ker več žre«",
      "Tankanje na okroglo vsoto, do groša",
      "Poraba, izračunana na stotinko natančno",
      "Predavanje o držanju volana",
      "»Samo še malo« in tako 200 km",
      "Termovka s čajem na gozdnem parkirišču",
      "Ati ne vpraša za pot, ker »ve«",
      "Bližnjica, ki pot podaljša za uro",
      "»Toliko za avtocesto? Rop pri belem dnevu«",
      "Prtljažnik pakira samo ati. Po načrtu",
      "Predlog menjave za volanom: zavrnjen",
      "Šipa umita ob vsakem tankanju",
      "Brca v gumo na vsakem postanku",
      "»S fiatom 126p smo se vozili dva dni«",
      "Zaviranje tik pred radarjem",
      "»Toliko za hot dog? Bomo jedli sendviče«",
    ],
  },
};

/** The free centre square, the same on every card. */
export const FREE_SQUARE = "»V mojih časih …«";
