import type { Text } from "@/i18n/overlay";
import type { OBSERVANCES as Observances } from "../calendar";

/*
 * Trgalni koledar. The page is picked by the date, so every list keeps the Polish length and
 * order. Proverbs rhyme like a folk calendar's and keep the " / " between the two lines, where the
 * page breaks them. Observances are keyed by their date, which stays as it is.
 */

/** Ten per month, January first. */
export const PROVERBS: Text<string[][]> = [
  [
    "Ko januarja pritisne mraz, / ata pol ure greje avto, vsako jutro ob isti čas.",
    "Ko na cesti leži sneg, / ata v dvojki vozi čez ravnino in čez breg.",
    "Če minus dvajset kaže toplomer, / ata nese smeti v samem puloverju, kot vsak večer.",
    "V januarju se v hiši ne greje: / ata obleče pulover in dni do pomladi šteje.",
    "Ata novoletne zaobljube v koledar zapiše, / od februarja pa koledar leži v garaži, daleč od hiše.",
    "Kdor januarja prvi skida dvorišče, / ta do pomladi pri sosedih napake išče.",
    "Januarja jelka igle po preprogi trosi, / ata pa: »Naj še postoji, saj nikogar nič ne prosi.«",
    "Ko januarja maturanti gredo na ples, / ata pove, kako je on plesal polonezo, in to zares.",
    "Kdor januarja na žaru peče klobase, / ta prvega maja ne čaka več, ker ga ima že zase.",
    "Januarski račun za elektriko in kurjavo / ata bere pri zajtrku na glas, da se vsi držijo za glavo.",
  ],
  [
    "Ko februarja vse zmrzne do dna, / ata preveri akumulator, a sosedov, ker svojega že pozna.",
    "Februar je kratek, a hud: / ata skida pol poti, ker je to še razumen trud.",
    "Za valentinovo cvetje iz akcije, / saj diši enako, cena pa je manjše dimenzije.",
    "Ko februarja z žleba visijo ledene sveče, / ata natanko ve, kdo je kriv, in to tudi reče.",
    "Februarja počitnice in pobočje belo: / ata ga v plugu prevozi, kot vsako leto, celo.",
    "Februarja ata v garaži ob pečici sedi / in vijake po kozarcih lepo uredi.",
    "Ko februarja v kleti zamrzne vodovod, / ata ga s fenom greje, mama pa fen išče povsod.",
    "Ko februarja maček na radiatorju dremlje, / ata trdi, da se kuri samo zanj, in to resno jemlje.",
    "Ko je februarja parkirišče kot steklo, / ata parkira na dveh mestih, ker se je »tako izteklo«.",
    "Kdor februarja sandale na nogavice natakne, / ta se julija dilemi o obutvi umakne.",
  ],
  [
    "Marca se vreme meša kakor v loncu: / ata nosi kapo, dežnik in kremo proti soncu.",
    "Marca je treba ure premakniti, / ata premakne vse, tiste v avtu pa se nihče ne sme dotakniti.",
    "Kdor marca zimske gume pospravi, / ta aprila posluša, kaj mu ata o tem pravi.",
    "Marca ata na vrtičku koplje gredice, / sosedu čez plot pa razlaga vrtičkarske resnice.",
    "Marca pospravljanje kleti traja do noči: / ata nosi škatle iz kota v kot, sam, brez pomoči.",
    "Marca je za oknom vse še megleno, / ata pa na okenski polici seje paradižnik, z vero nezlomljeno.",
    "Marčni veter, marčna slota, / ata pa že prižiga žar, ker je sobota.",
    "Kdor marca vetrobran iz kleti izvleče, / ta julija na plaži za prostor ne potrebuje sreče.",
    "Ko marca sneg še enkrat zapade na vrt in polje, / ata reče: »A nisem rekel?« in je takoj boljše volje.",
    "Ko marca koleno dež napove, / ata pobere perilo, preden napoved sploh kaj ve.",
  ],
  [
    "April prepleta sneg in cvetje, / ata pa hodi v sandalih, ker je po njegovem že poletje.",
    "Prvega aprila ata staro šalo zbije, / družina se smeje, ker ve, da se pred njo nihče ne skrije.",
    "Kdor aprila letne gume montira, / ta posluša ata, ki o majskem snegu filozofira.",
    "Aprila prvi žar sezono odpira, / ata prvo klobaso z rešetke sam izbira.",
    "Ko aprila slana grozi jablani v cvetu, / ata jo pokrije z zaveso, kot nekoč, po starem receptu.",
    "Aprila kolo iz kleti pride na plan, / ata napumpa gume in se pelje v trgovino, sto metrov stran.",
    "Ko aprila sosed prvi pokosi travo, / ata pokosi še isti dan, le nižje in širše, za slavo.",
    "Kdor aprila na tehnični pregled k »svojemu« zavije, / ta dobi nalepko, nobene napake pa nihče ne odkrije.",
    "Ko aprila zdaj sneži, zdaj je lepo vreme, / ata vozi v prtljažniku lopato in vetrobran: saj nobeno ni breme.",
    "Aprila se na vrtičku listje kuri, / sosed pa kliče gasilce, seveda, ob isti uri.",
  ],
  [
    "Prvi maj brez žara je le dan, dela prost: / ata drži klešče, vsakdo drug je pri žaru samo gost.",
    "Maja, ko cvetijo kostanji, / ata ima dopust na morju načrtovan že od lani.",
    "Sredi maja pridejo ledeni možje, / ata paradižnik sadi pozneje, ne zaradi mode, to se ve.",
    "Maja mladina piše maturo, / ata pa pravi, da je bila njegova težja, in to ponavlja vsako uro.",
    "Majski dež prinaša kruh, / ata pa vseeno zaliva, ker je za dež gluh.",
    "Kdor maja sandale prvič obuje, / ta bele nogavice v paketih kupuje.",
    "Maja pred gradbenim centrom ni prostora, / ata zasede dve mesti, ker pač mora.",
    "Majsko sonce vse prebudi, / ata vstane ob petih in zbudi vse ljudi.",
    "Maja v soboto ob sedmih, na vse zgodaj, / ata kosi travo. Sosedov ni nihče vprašal, kdaj.",
    "Ko maja nad vrtičkom grmi, / ata izvleče anteno in čaka s svetilko v temi.",
  ],
  [
    "Junija otroci prinesejo spričevala z odliko, / ata pa poudari, da je bila njegova odlika z veliko razliko.",
    "Junija se po svatbah pleše veselo, / ata si kravato po polnoči zaveže čez čelo.",
    "Ko junija svetovno ali evropsko prvenstvo igrajo, / ata zabija gole s kavča, da noge kar same brcajo.",
    "Junija na vrtičku vse poganja, / ata bučko meri in se ji spoštljivo klanja.",
    "Konec junija se počitnice pričnejo, / ata že pakira avto po sistemu, ki ga drugi ne razumejo.",
    "Junija komarji nad vodo letajo, / ata pravi, da ga ne pikajo, ker ga komarji poznajo.",
    "Ko junija pripeka, ata okna zapira, / ker »vročina gre noter«, in z zavesami vse zastira.",
    "Kdor junija vsak dan žar prižiga, / ta julija klešč nikomur ne da, in ga nič ne briga.",
    "Za očetovski dan kravata ali nogavic par: / ata reče, da ne rabi nič, in vzame, žal, vsak dar.",
    "Junijske jagode se štejejo vsako jutro na novo, / da se ve, koliko jih je zmanjkalo, in to zagotovo.",
  ],
  [
    "Julija vetrobran ob pol sedmih zjutraj že stoji, / ker kdor pride pozneje, prostora ne dobi.",
    "Ocvrta riba na morju sredi julija: / ata vpraša, koliko stane sto gramov, in obraz se mu zvija.",
    "Julija je klima v avtu izklopljena, / ker »več porabi«: družina skuhana, denarnica pa ohranjena.",
    "Julija v kampu velja eno pravilo: / ata ravna prikolico, dokler se ni vse umirilo.",
    "Ko julija na dopustu dežuje, / ata sonce obljublja, ker mu ga koleno napoveduje.",
    "Julija v koloni ata pozna bližnjico: / boljšo od kolone, čeprav pelje naravnost v pšenico.",
    "V vročini ata pije vroč čaj, / ker »vroče hladi«, in vsem razloži, zakaj.",
    "Julija letovanje, julija hotel: / ata ob sedmih zasede mizo v sredini, kot je hotel.",
    "Ko julija višnje na drevesu dozorijo, / ata drži lestev in razlaga, kako se trgajo, da vsi znorijo.",
    "Julija ob cesti bob in borovnice: / ata primerja cene, od prve do zadnje stojnice.",
  ],
  [
    "Avgusta je morje najtoplejše, / ata pa pravi, da je bilo leta osemdeset še toplejše.",
    "Ko avgusta zvezde padajo z neba, / ata si zaželi parkirno mesto pred blokom: več ni treba.",
    "Avgusta so po dežju v gozdu gobe, / ata pozna mesta in jih ne izda do konca svoje dobe.",
    "Avgusta češplje padajo z vej, / ata kuha mezgo v vsakem prostem trenutku, brez mej.",
    "Po avgustovskem dopustu ata poda poročilo / o vsaki koloni, obvozu in črpalki, vse, kar se je zgodilo.",
    "Avgusta paradižnika z vrtička je za cele zaboje, / ata ga nosi sosedom, čeprav imajo vsi svoje.",
    "Avgusta zadnji žar, potem spet šolske klopi: / ata pravi, da je bilo včasih težje in lepše, in se v spominih raztopi.",
    "Ko avgusta ose nad mizo brenčijo, / ata jih s televizijskim sporedom podi, one pa mu vedno ubežijo.",
    "Ko avgusta sosed v bloku prenavlja, / ata stoji med vrati: »Kdo vam pa to tako postavlja?«",
    "Konec avgusta vetrobran zapusti obalo, / ata ga opere in spravi v klet, kjer bo sanjal o poletju, in to ne malo.",
  ],
  [
    "Ko september jesen prinaša, / ata že za termin za zimske gume povpraša.",
    "Septembra se gobe nabirajo od zore, / ata se vrne s košaro in z zgodbo, ki je nihče ustaviti ne more.",
    "Ko je septembra na travniku babje leto, / ata ve, da bo zima mila: tako pravijo zajci, in to je sveto.",
    "Septembra vrtiček rodi kot nor, / ata vozi bučke, da je zelen ves prtljažni prostor.",
    "Ko septembra zadnjič pokosi trato, / ata kosilnico čisti tako slovesno, kot bi čistil zlato.",
    "Septembra so večeri vse hladnejši, / ata obleče pulover, radiatorji pa so še hladnejši.",
    "Septembra jabolka z jablane letijo, / ata pobere vsako, sosedje pa se jih branijo.",
    "Septembrski večer in tekma v živo: / ata vpije na sodnika, ker sodi, seveda, krivo.",
    "Ko septembra lastovke odhajajo, / ata v kleti šteje kozarce, ki ostajajo.",
    "Septembra se vrnejo domače naloge, / ata jih razlaga po svoje, da se vsem šibijo noge.",
  ],
  [
    "Oktobra se menjajo gume, / ata jih je zamenjal že septembra in je zadovoljen, kar se razume.",
    "Ko oktobra steče ogrevanje, / ata privije radiatorje: »Najprej pulover, potem tarnanje.«",
    "Ko oktobra ure prestavimo nazaj, / ata ima v avtu pravo uro, ne da bi prestavil kaj.",
    "Oktobra listje z dreves pada do konca, / ata ga grabi vsak dan, naravi navkljub, do večernega zvonca.",
    "Oktobra pade prva slana, / ata vrtnice zavije v vreče od krompirja: njegova skrb, vsem znana.",
    "Oktobra ata zelje kisa v sodu / in o njem pripoveduje vsemu rodu.",
    "Oktober je zlat in gozd ves pisan, / ata pa že šteje dni do svetega večera: vsak je v koledarju zapisan.",
    "Oktobra dežuje, kot da se je nebo odprlo, / ata v garaži popravlja, kar se da, ker je drugo delo zamrlo.",
    "Oktobra so večeri dolgi in brez luči, / ata gleda oddaje o vlakih, vse do polnoči.",
    "Oktobra so kostanji vsepovsod po tleh, / ata iz njih naredi možička z brki, najlepšega od vseh.",
  ],
  [
    "Novembra listje, dež in vse naenkrat, / ata pa pravi: »Včasih je bil to pravi listopad.«",
    "Novembra je za oknom sivo in mračno, / ata z lepilnim trakom tesni okna, mrko in natančno.",
    "Ko novembra prvi sneg prši, / ata strga šipe, čeprav sonce vse v pol ure posuši.",
    "Novembra so večeri dolgi kot kača, / ata pripoveduje o dopustu in se k njemu vedno znova vrača.",
    "Ko novembra radiator topel postane, / ata ga privije: »Greje za soseda,« in pri tem ostane.",
    "Ko je novembra v letaku akcija, / ata kupi tri vrtalnike: drugi za groš, tretji v paketu. To je ekonomija.",
    "Novembra megla, novembra blato, / ata pere avto, ker je sobota. Pa kaj zato.",
    "Ko so novembra slive v kisu pripravljene, / ata z njimi gosti goste: to so reči, skoraj posvečene.",
    "Novembra ata ptičem krmilnico zgradi, / s streho, žlebom in temelji, kot se spodobi.",
    "Novembra račun za ogrevanje gre v nebo, / ata obleče drugi pulover in mu je kot spomladi lepo.",
  ],
  [
    "Ko decembra krap v kadi zaplava, / ata ga straži do svetega večera, kot veleva navada prava.",
    "Decembra ata kupi darila, ko so jih vsi drugi že imeli, / in pravi, da včasih daril ni bilo, pa so bili vsi veseli.",
    "Ko decembra lučke na balkonu utripajo, / ata jih ob desetih ugasne, ker vate zapravljajo.",
    "Decembra ata jelko izbira do mraka, / potem pa vzame prvo s kupa: tisto, ki ga čaka.",
    "Decembra so doma gostje, vsa družina, / ata pa v garaži: tam je mir in tišina.",
    "Decembra ata lanske lučke razpleta / do noči, zbrano, kot da rešuje uganko sveta.",
    "Ko decembra Indeks doseže klinično vrednost, / to pomeni, da se k svetovečerni mizi zbira vsa družinska skupnost.",
    "Decembra se voščilnice pišejo ročno, / ata vse napiše enako: na kratko, okorno in točno.",
    "Ko decembra sneg naletava vso noč, / ata ob petih kida, ker ima v sebi moč.",
    "Opolnoči na silvestrovo ata šampanjec odčepi, / ob pol enih pa v naslonjaču pred ekranom že spi.",
  ],
];

/** »Nasvet za danes«: a household tip in the dziaders' own logic. */
export const TIPS: Text<string[]> = [
  "Račun se spravi v denarnico, denarnica pa v predal. Po treh letih lahko denarnico vržeš stran.",
  "Škatla od televizorja se hrani do konca garancije, potem pa do konca televizorja. Potem pride prav za naslednjega.",
  "Luč se ugasne v sobi, iz katere odideš, tudi če v njej še kdo sedi.",
  "Tlak v gumah se preveri z brco. Če se noga odbije, je vse v mejah normale.",
  "Radiator ne potrebuje več kot dvojke. Preostala toplota je v puloverju, ki leži v omari.",
  "Voda za čaj se zavre za en kozarec. Drugi lahko počaka, da pride na vrsto.",
  "Vrečka se po nakupu zloži v trikotnik in spravi v vrečko z vrečkami. Trikotnik zavzame manj prostora kot kvadrat.",
  "Daljinec je najbolje hraniti v plastični vrečki. Vrečka se zamenja vsaka štiri leta, daljinec nikoli.",
  "Avto se pere v soboto zjutraj, tudi če bo v nedeljo deževalo. Dež spere samo umazanijo, ki je že bila.",
  "V trgovino se hodi s seznamom. Seznam je zato, da veš, česa nisi kupil.",
  "Ko kaj ne dela, ga najprej izklopiš, potem pa udariš od strani. Navodila so šele na tretjem mestu.",
  "Okna se umivajo s časopisom. Čistilo za stekla je kemija, časopis pa je še vedno informacija.",
  "Na vrtiček se gre z zalogo vode, čeprav je na vrtičku pipa. Pipa morda ne bo hotela.",
  "Kozarci od marmelade se umijejo in hranijo v rezervi. Rezerva kozarcev se hrani za primer nove marmelade.",
  "Ko na televiziji napovedujejo dež, je vredno vprašati koleno. Koleno nima reklam.",
  "Bencin se toči do polnega, tudi če je dražji kot včeraj. Jutri bo morda še dražji.",
  "Vijaki se razvrstijo po velikosti v kozarce od kave. Kozarci od kave se razvrstijo po znamki kave.",
  "Gostom se ponudijo copati. Copati za goste so ene velikosti, ki vsakemu pristaja enako slabo.",
  "Hladilnik se zapre takoj. Razmišljati se da tudi pri zaprtem.",
  "Meso za žar se kupi dan prej, da svinjski vrat lahko odleži svoje. Klobasi ni treba ničesar.",
  "V avtu morajo biti odeja, vlečna vrv, lopata in papirnati zemljevid. Navigacija se morda ne spozna, zemljevid pa nima mnenja.",
  "Pred dopustom se zaprejo voda, plin in potrpežljivost. Potrpežljivost se odpre šele na cilju.",
  "Vedro na parkirnem mestu ni smet. Je rezervacija.",
  "Navodila za uporabo se hranijo v registratorju, v plastični srajčki. Prebereš jih lahko, ko naprava neha delati.",
  "Telefon se nosi v etuiju s preklopnim pokrovčkom, pokrovček pa se zapre po vsakem pogovoru. Zaslon ne mara prepiha.",
  "V restavracijo se gre po kosilu doma. Takrat lahko porcije mirno oceniš.",
  "Znižane žemlje se takoj zamrznejo. Po odmrzovanju imajo okus po znižanih žemljah, samo pozneje.",
  "Na svatbo se vzameta kuverta in zvezek. Kuverta je za darilo, zvezek za stroške, kuli za vsak primer.",
  "Listek za brisalcem mora vsebovati besedo »vljudno«. Brez nje je samo listek.",
  "Pri elektriki se varčuje zvečer. Dovolj je ena svetilka, v sobi s televizorjem, in televizor.",
  "Za žar ne potrebuješ podžigalnika v gelu. Dovolj so časopis od prejšnjega tedna, vžigalice in ura debate.",
  "Vodovodarja pokličeš šele po tretjem lastnem popravilu. Takrat vsaj veš, česa ne delati.",
  "Aplikacijo na telefonu nastavi sin. Potem se je ne dotikaš, da se ne razglasi.",
  "Pri akciji »drugi kos gratis« se kupita dva kosa. Tretji bi tudi prišel prav, ampak za tretjega ni akcije.",
  "Uro v avtu lahko pustiš na zimskem času. Pol leta tako ali tako kaže prav.",
  "Kozarci od gorčice so najtrpežnejši v hiši. Kristal stoji v regalu, kozarci od gorčice delajo.",
  "Preproga se v soboto posesa, enkrat na leto pa iztepe na drogu za preproge. Drog za preproge je tudi pohištvo, le skupno.",
  "Na urad se dokumenti nosijo v plastični srajčki. Uradnik takoj vidi, da ima opravka s pripravljenim človekom.",
  "Počitniško prikolico ravnaš do uspeha. Uspeh pride navadno na dan odhoda.",
  "Na počitnice se odhaja ob štirih zjutraj, da se izogneš kolonam. Ob štirih zjutraj se na pot odpravijo tudi kolone.",
  "Gobe se nabirajo ob zori, rastišč pa ne izdaš nikomur. Niti gobam.",
  "Ko gostje odhajajo, se luč na stopnišču ugasne po tretjem nadstropju. Naprej poznajo pot.",
  "Nova naprava se priklopi brez navodil. Če dela, so bila navodila odveč. Če ne dela, so bila slabo napisana.",
  "Sosedu, ki parkira postrani, se pusti listek. Sosedu, ki parkira naravnost, tudi, za vsak primer.",
  "Ena čajna vrečka se uporabi dvakrat. Drugič je čaj blažji in pride ceneje.",
  "Televizija se gleda s treh metrov. Bliže se sede samo med tekmo, da lahko bolje svetuješ trenerju.",
  "Ključi od avta se obesijo na žebelj pri vratih. Žebelj je samo eden, da se nihče ne zmoti.",
  "Kuli ima doma svoje mesto. Če ga ni tam, ga je nekdo vzel in treba je ugotoviti, kdo.",
  "Preden kupiš avto, vprašaš svaka. Potem kupiš drugega, ampak svak je bil vprašan.",
  "Na okenski polici mora biti blazina. Brez blazine je opazovanje dvorišča nepopolno in naporno za komolce.",
  "Račun se preveri pri blagajni, pri izhodu in doma. Tretjič se navadno ujema.",
  "Pred nevihto se iz televizorja izvleče antena. Televizor je star, ampak nevihta tudi.",
  "Na družinsko kosilo se pride četrt ure prezgodaj. Takrat je čas preveriti, kaj se je spremenilo v regalu.",
  "Vrtalnik se sosedu posodi iz vljudnosti, prevzame pa s predavanjem o vrtanju.",
  "List s koledarja se odtrga zjutraj. Kdor trga zvečer, živi na kredit.",
  "Račun za elektriko se bere na glas, pred vso družino. Takrat vsak ve, kdo je pustil polnilnik v vtičnici.",
  "Radiator se odzrači vsako leto, tudi če greje. Radiator mora vedeti, kdo je tu glavni.",
  "Novi čevlji se uhodijo doma, v copatih. Copati spodaj, čevlji zgoraj, in tako en teden.",
  "V vlaku se sede v smeri vožnje. Ritensko se vozijo samo tisti, ki se ne spoznajo.",
  "Kosilnica se po sezoni očisti temeljiteje kot avto. Avto vozi vse leto, kosilnica si je zaslužila počitek.",
];

/** »Priporočilo Inštituta za danes«: one short line in the infinitive of official notices. */
export const ORDERS: Text<string[]> = [
  "Danes ne prižigati žara s podžigalnikom v gelu.",
  "Preveriti tlak v gumah. Za vsak primer brcniti.",
  "Ugasniti luč v sobi, ki jo zapuščaš.",
  "Ne dotikati se daljinca brez dovoljenja lastnika.",
  "V vrsti vprašati samo eno stvar. Res samo eno.",
  "Odložiti klešče na mizo. Za minuto, za vajo.",
  "Prebrati navodila do prvega klicaja.",
  "Reči »dober dan« sosedu s slušalkami. Enkrat.",
  "Pred deveto ne komentirati tujega parkiranja.",
  "Pustiti navigaciji, da izbere pot. Brez debate, do prvega ovinka.",
  "Iz kleti odnesti eno škatlo. Ne prinesti nazaj dveh.",
  "Do kosila ne govoriti »v mojih časih«.",
  "Odčitati temperaturo za oknom in je ne komentirati.",
  "Spustiti koga naprej v vrsti pri blagajni. Šteti do deset.",
  "Preveriti, ali mora radiator res stati na dvojki.",
  "Napisati sporočilo z malimi črkami. Brez podpisa.",
  "Narediti posnetek zaslona, ne fotografije televizorja.",
  "Pohvaliti tuji plinski žar. Iskreno, če se da.",
  "V tuji kuhinji ničesar ne prestavljati.",
  "Listek za brisalec pustiti v predalu. Naj počaka.",
  "Pojesti kosilo v restavraciji brez pripomb natakarju.",
  "Nikogar ne vprašati, koliko je dal za avto.",
  "Prešteti vrečke v vrečki. Rezultat obdržati zase.",
  "V letalu vstati s sedeža šele, ko so vrata odprta.",
  "Sprejeti klic hčere brez »kdo je?«.",
  "Prevoziti mesto brez trobljenja. Razen ko se prižge zelena.",
  "Do konca poslušati eno pesem iz tega stoletja.",
  "V trgovini ne kukati v tujo košarico.",
  "Ob žaru sesti kot gost. Preprosto sesti.",
  "Kupiti eno stvar brez letaka. Za poskus.",
  "Pred mrakom odložiti libelo.",
  "Ne preverjati, ali je sosed pravilno ločil steklo.",
  "Pojesti žemljo po redni ceni. Inštitut ve, da je težko.",
  "Poklicati koga brez »halo, me slišiš?«.",
  "Pustiti komu drugemu, da odtrga list s koledarja.",
  "Ne prišepetavati sodniku v televizorju, kaj naj piska.",
  "Priznati vremenski napovedi, da je imela prav. Enkrat, potiho.",
  "Pustiti vetrobran v prtljažniku do jutri.",
  "Vrniti vrtalnik brez predavanja o vrtanju.",
  "Ne računati, koliko je stala svatba. Niti ene jedi.",
];

/** The Institute's observances, keyed by their date ("MM-DD"). */
export const OBSERVANCES: Record<string, Text<(typeof Observances)[number], "date">> = {
  "01-05": { name: "Dan napovedi pospravljanja jelke", note: "Napove se, da bo jelka pospravljena. Rok se določi pozneje." },
  "01-15": { name: "Dan strganja šip", note: "Obeležuje se s kartico od hladilnika, ker je strgalo v drugem avtu." },
  "01-28": { name: "Dan ogrevanja motorja", note: "Pol ure v prostem teku, v imenu tradicije in sosedske radovednosti." },
  "02-09": { name: "Dan razvrščanja vijakov", note: "Po velikosti, v kozarce od kave. Presežek vijakov se preseli v kozarce od kumaric." },
  "02-15": { name: "Dan znižanega cvetja", note: "Dan po znanem prazniku je vse pol cenejše. Roža je roža." },
  "02-21": { name: "Dan zagonskih kablov", note: "Kabli se sosedu posodijo skupaj s predavanjem o akumulatorjih." },
  "03-07": { name: "Dan škatle od televizorja", note: "Škatle se hranijo do konca garancije, potem pa še dlje, ker bodo prišle prav." },
  "03-22": { name: "Dan prinašanja vetrobrana iz kleti", note: "Do julija so še trije meseci, ampak priprava je temelj vsega." },
  "04-02": { name: "Dan iste šale", note: "Včerajšnja šala se danes pove še enkrat, za tiste, ki je niso slišali." },
  "04-09": { name: "Dan prve košnje", note: "Obeležuje se v soboto ob sedmih zjutraj, ne glede na to, kateri dan v tednu je." },
  "04-18": { name: "Dan svojega kontrolorja", note: "Kontrolor pozna avto že leta in si ga ogleda s spoštovanjem, od daleč." },
  "05-08": { name: "Dan klešč", note: "Klešče se predajo samo v izjemnih okoliščinah. Danes takih ni." },
  "05-20": { name: "Dan bele nogavice", note: "V sandalih, seveda. Dolžina nogavice: do sredine meč, brez debate." },
  "05-29": { name: "Dan spominov na prvi maj", note: "O prvomajskih praznikih se pripoveduje do avgusta. Od avgusta se pripoveduje o dopustu." },
  "06-05": { name: "Dan bučke", note: "Bučka se izmeri, stehta in razdeli sosedom, ki imajo svoje." },
  "06-17": { name: "Dan kravate na čelu", note: "Obeležuje se po polnoči, za mizo stricev, na vsaki svatbi v državi." },
  "07-10": { name: "Dan vetrobrana", note: "Vetrobran se postavi ob 6.30, preden se sonce sploh zave." },
  "07-19": { name: "Dan ravnanja prikolice", note: "Konča se, ko je mehurček na sredini ali ko zaide sonce." },
  "07-29": { name: "Dan ribe po sto gramov", note: "Cena ocvrte ribe se prebere na glas, z neverico, dvakrat." },
  "08-07": { name: "Dan obvoza čez njivo", note: "Obvoz je vedno krajši, tudi če je daljši." },
  "08-21": { name: "Dan paradižnika z vrtička", note: "Paradižnika z vrtička se ne primerja z ničimer, še posebej ne s tistim iz trgovine." },
  "08-28": { name: "Dan zadnjega žara pred šolo", note: "Klobase so iste, ampak vsi govorijo o zvezkih." },
  "09-04": { name: "Dan karirastega zvezka", note: "Karirasti zvezek se kupi na zalogo, za primer računov, ki jih bo treba preveriti." },
  "09-18": { name: "Dan molčečega gobarja", note: "Rastišč se ne izdaja. Niti na praznik." },
  "09-26": { name: "Dan vrečke z vrečkami", note: "Danes se preštejejo zaloge. Rezultat se ne objavi." },
  "10-01": { name: "Dan odprtja Inštituta", note: "1. oktobra 2026 je Inštitut odprl vrata javnosti. Klešče so za en dan predali naprej." },
  "10-02": { name: "Nacionalni dan popisa", note: "Ta dan se je začel Nacionalni popis dziadersov. Vsak pregled šteje, anonimno." },
  "10-15": { name: "Dan zimskih gum", note: "Kdor jih je zamenjal septembra, se lahko danes vzvišeno nasmehne." },
  "10-24": { name: "Svetovni dan kabla neznanega namena", note: "Kabel ostane v predalu. Nekoč se bo izkazalo, čemu je." },
  "11-07": { name: "Dan tesnjenja oken", note: "Vata, lepilni trak in prepričanje, da toplota uhaja samo skozi sosedova okna." },
  "11-19": { name: "Dan listka za brisalcem", note: "Piše se z velikimi tiskanimi črkami, vljudno, na hrbtni strani računa." },
  "11-28": { name: "Dan puloverja namesto radiatorja", note: "Radiator ostane na dvojki. Puloverji se izdajo iz omare, po eden na družinskega člana." },
  "12-08": { name: "Dan razpletanja lučk", note: "Lanske lučke se razpletajo zbrano. Traja do mraka ali dlje." },
  "12-15": { name: "Dan krapa v kadi", note: "Kopanje se prestavi na po praznikih. Krap ima prednost." },
  "12-30": { name: "Dan načrtovanja silvestrovanja doma", note: "Načrt je preprost: televizija, šampanjec opolnoči, spanec ob pol enih." },
};
