import type { Text } from "@/i18n/overlay";
import type { Situation } from "../phrasebook";

/*
 * Dziaderski pogovornik. Keyed by the situation slug, which stays Polish because it is part of
 * every line code ("samochod-3b7"). A code picks parts by index, so every list keeps the Polish
 * length and order. Each part is a whole sentence: any opener, claim and closer of a chapter read
 * as one line, so none of them may lean on another.
 */

/** Every chapter starts with these, in the Polish order. */
const OPENERS = [
  "Eno ti bom povedal.",
  "Zdaj me pa dobro poslušaj.",
  "Nočem se vmešavati, ampak se bom.",
  "Človek božji, jaz se s tem ukvarjam že trideset let.",
  "Jaz nič ne rečem, samo pravim.",
  "Povem na kratko, ker ne maram dosti govoriti.",
  "Ti se na to ne spoznaš, zato ti bom razložil.",
  "Veš, kaj bi jaz naredil na tvojem mestu?",
];

/** Every chapter ends with these, in the Polish order. */
const CLOSERS = [
  "Ampak kaj pa jaz vem.",
  "Potem pa ne reci, da nisem rekel.",
  "Zapomni si, kaj ti pravim.",
  "Moj svak je tako naredil in mu je še danes žal.",
  "Včasih bi bilo kaj takega nepredstavljivo.",
  "In s tem je debate konec.",
  "Jaz ti samo svetujem.",
  "Boš videl, da imam prav. Kot vedno.",
];

export const SITUATIONS: Record<string, Text<Situation, "slug">> = {
  samochod: {
    name: "V avtu",
    short: "Avto",
    openers: [...OPENERS, "Daj, bom jaz vozil.", "Zapelji na bankino, da ti pokažem."],
    claims: [
      "Dizel je dizel, vse ostalo so igračke.",
      "Tega motorja se ne da uničiti, če ga pustiš pri miru.",
      "Gume se zamenjajo oktobra, ne šele, ko zapade sneg.",
      "Za ta denar dobiš dva passata iz Nemčije.",
      "Električni avto? Kaj pa, ko zmanjka elektrike?",
      "Tukaj nekaj trka. Slišiš? Jaz slišim.",
      "Navigacija je navigacija, ampak jaz tod vozim od dvaindevetdesetega.",
      "V tretji prestavi gre v klanec sam od sebe.",
      "Klima se pokvari. Okno dela vedno.",
      "Pravi voznik ne rabi parkirnih senzorjev.",
      "Olje se preveri vsak teden, ne šele, ko zasveti lučka.",
      "Takega avta se ne pere v avtopralnici. Samo ročno, ob nedeljah.",
    ],
    closers: [...CLOSERS, "Zdaj pa poglej, koliko porabi.", "Pa ne loputaj z vrati."],
  },
  remont: {
    name: "Pri prenovi",
    short: "Prenova",
    openers: [...OPENERS, "Umakni se, takoj boš videl, kako se to dela.", "Kdo ti je pa to tako položil?"],
    claims: [
      "Ploščice se polagajo od sredine, ne od stene.",
      "Mojster? To naredim sam čez vikend.",
      "Tukaj ni nobenega pravega kota. Nikjer ga ni.",
      "Tole steno bi podrl. Saj ni nosilna. Menda.",
      "Silikon ni rešitev, ampak priznanje napake.",
      "Jaz bi tu dal laminat. Povsod bi dal laminat.",
      "Libela lahko laže, oko pa nikoli.",
      "Tile vijački so ostali, ker so rezervni.",
      "Včasih se je delalo za večnost, ne za garancijo.",
      "Navodila so za tiste, ki ne znajo.",
      "Vrtalnik mora biti udarni. Tudi za eno sliko.",
      "Fuga mora biti siva, ker se bela umaže. Vem, kaj govorim.",
    ],
    closers: [...CLOSERS, "Daj sem vrtalnik.", "Pa ne kliči mojstra, ker je sramota."],
  },
  urlop: {
    name: "Na dopustu",
    short: "Dopust",
    openers: [...OPENERS, "Vstani, ura je pol šestih.", "Jaz semkaj hodim že leta, tako da vem."],
    claims: [
      "Vetrobran se postavi pred sedmo, potem ni več prostora.",
      "Za ta denar bi imeli v Grčiji dva tedna.",
      "Sendviči od doma. Vsaj vemo, kaj je notri.",
      "Voda ima štirinajst stopinj. Osvežilna.",
      "Vafelj za dvajset zlotov? Jaz se spomnim, ko je stal en zlot.",
      "Na pot se gre ob štirih, pa ni kolon.",
      "All inclusive je treba izkoristiti. Do zadnjega zajtrka.",
      "Nogavice v sandalih so udobje, ne moda.",
      "Morje je najboljše septembra. Ali maja. Samo zdaj ne.",
      "Napoved sem preveril v treh aplikacijah. Vse lažejo.",
      "Brisača se pogrne že zvečer, da imaš zjutraj kje ležati.",
      "Spominki se kupijo zadnji dan, takrat so cenejši.",
    ],
    closers: [...CLOSERS, "Vetrobrana vzamemo dva.", "Domov gremo v soboto zjutraj, pred kolonami."],
  },
  restauracja: {
    name: "V restavraciji",
    short: "Restavracija",
    openers: [...OPENERS, "Šef, a imate trenutek?", "Jaz nič ne rečem, ampak porcija je majhna."],
    claims: [
      "Zrezek mora moleti čez krožnik.",
      "Za ta denar bi bila doma tri kosila.",
      "Ta miza se maje. Tista zraven tudi.",
      "Ne jem ničesar, česar ne znam izgovoriti.",
      "Tatarski biftek je surovo meso, ne jed.",
      "Kava v tej skodelici je vzorec, ne kava.",
      "Vedno vzamem isto, zato jedilnega lista ne rabim.",
      "Krompir mora biti s koprom. O tem se ne debatira.",
      "Pierogi se delajo doma, ne pa naročajo.",
      "Juho iz vrečke spoznam po prvi žlici.",
      "Včasih je bil kompot h kosilu vključen v ceno.",
      "Račun delimo na enake dele, samo sladico vsak plača sam.",
    ],
    closers: [...CLOSERS, "Ostanek mi pa zapakirajte, prosim.", "Ocena na internetu: dve zvezdici."],
  },
  komputer: {
    name: "Pri računalniku",
    short: "Računalnik",
    openers: [...OPENERS, "Pokliči koga mlajšega.", "Nekaj se je pokvarilo, ampak jaz se nisem ničesar dotaknil."],
    claims: [
      "Ugasni in prižgi. Vedno pomaga.",
      "Ruter je treba čez noč izklopiti, da se spočije.",
      "Geslo imam na listku pod tipkovnico. Varno.",
      "Posodobitev ne nameščam, ker potem nič ne dela.",
      "To je virus. Povem ti, da je virus.",
      "Vse natisnem, ker se v računalniku izgubi.",
      "Včasih je bil en računalnik na družino in je bilo dovolj.",
      "Ta vaš oblak so samo podatki pri tujih ljudeh.",
      "Internet je počasen, ker ga sosed krade.",
      "Miška mora biti na kabel, ker se baterija izprazni.",
      "Jaz tega nisem kliknil. Samo se je kliknilo.",
      "Ikone so se mi premaknile. Nekdo je tu brskal.",
    ],
    closers: [...CLOSERS, "Natisni mi to.", "Še najbolje, da mi to daš na ključek."],
  },
  "dzieci-sasiadow": {
    name: "Sosedovi otroci",
    short: "Sosedovi otroci",
    openers: [...OPENERS, "Samo malo, mladenič.", "Kje so vaši starši?"],
    claims: [
      "Včasih so se otroci igrali na drogu za preproge, ne pa na telefonih.",
      "Žoga ob tej uri? Zdaj je vendar popoldanski počitek.",
      "Na moji trati se ne igra. To ni igrišče.",
      "Kolo se po pločniku potiska. Jaz sem ga vedno potiskal.",
      "Včasih je otrok prišel domov, ko so se prižgale ulične svetilke.",
      "Kreda na pločniku? Kdo pa bo to potem spral?",
      "Pri vaših letih sem se sam vozil v mesto po kruh.",
      "Ti skiroji bi morali imeti registrske tablice.",
      "Glasno je. Jaz nič ne rečem, ampak glasno je.",
      "Žoga je priletela na vrt? Zdaj je to moja žoga.",
      "Včasih se je reklo dober dan celemu bloku.",
      "Starši nič ne rečejo, zato bom pa jaz.",
    ],
    closers: [...CLOSERS, "In to povej očetu.", "Naslednjič žoga ostane pri meni."],
  },
  pogoda: {
    name: "O vremenu",
    short: "Vreme",
    openers: [...OPENERS, "Ugasni to napoved, jaz ti bom povedal, kako bo.", "Potrkaj po barometru, ampak nežno."],
    claims: [
      "Na televiziji pravijo sonce, koleno pravi dež. Verjamem kolenu.",
      "Nevihta bo, to čutim. Pa še lastovke letajo nizko.",
      "Termometer za kuhinjskim oknom visi od štiriinosemdesetega in se še ni zmotil.",
      "Včasih je bilo poleti bolj vroče, pozimi pa bolj mrzlo. Zdaj je vse mlačno.",
      "Napoved delajo v Varšavi. Kako naj oni vedo, kaj je pri nas na dvorišču?",
      "Včasih je snežak pred blokom stal do marca, zdaj pa ne zdrži do kosila.",
      "Včasih so šipe zmrzovale od znotraj, pa se je dalo živeti.",
      "Dežnika ne nosim. Ko dežuje, se skriješ pod napušč in počakaš.",
      "Dolge gate se oblečejo prvega oktobra. Vreme s tem nima nobene zveze.",
      "Ne glej v telefon, ampak v nebo. Nebo se ne obesi.",
      "Ko piha z vzhoda, piha tri dni. Vedno je bilo tako.",
      "Osemindvajset stopinj ni vročina. Vročina je bila štiriindevetdesetega.",
    ],
    closers: [...CLOSERS, "Pa poberi perilo z balkona.", "Pulover pa vseeno vzemi."],
  },
  zakupy: {
    name: "V trgovini",
    short: "Trgovina",
    openers: [...OPENERS, "Pokaži no ta račun.", "Daj to nazaj, v letaku je bilo ceneje."],
    claims: [
      "Letak se bere s kulijem v roki, kot pogodba.",
      "Kocka masla je devetindevetdesetega stala dva zlota. Imam zapisano.",
      "Račun se preveri pri blagajni, ne doma. Doma je že prepozno.",
      "Samopostrežna blagajna? Naj si postreže sama.",
      "Koliko pa to zdaj stane? Ne povej, ker me bo kap.",
      "Vrečk se ne kupuje. Vrečke se ima.",
      "Če je drugi izdelek zastonj, se jih vzame štiri. To je matematika.",
      "Mleko se vzame čisto od zadaj. Spredaj je tisto s kratkim rokom.",
      "Ko odprejo drugo blagajno, se ne teče, ampak hodi s hitrim korakom.",
      "Rdeča cena še ni akcija. Treba je preračunati na kilogram.",
      "Žeton za voziček se nosi pri ključih. Že dvajset let isti.",
      "V trgovino se gre zvečer, ko znižajo kruh.",
    ],
    closers: [...CLOSERS, "Račun pa shrani, za vsak primer.", "Vzel sem šest, ker je bila akcija."],
  },
};
