import type { Species, SpeciesKey, Status, StatusInfo } from "@/content/species";
import type { Text } from "@/i18n/overlay";

/** Data, not text: codes, slugs (from slugs/species.ts), Latin names, regions, calendars, related keys. */
type Skip = "code" | "slug" | "latin" | "authority" | "region" | "calendar" | "related";

/** Threat statuses (IUCN), masculine, agreeing with "dziaders". */
export const STATUSES_TEXT: Record<Status, Text<StatusInfo>> = {
  EX: { label: "izumrl" },
  EW: { label: "izumrl v naravi" },
  CR: { label: "skrajno ogrožen" },
  EN: { label: "ogrožen" },
  VU: { label: "ranljiv" },
  NT: { label: "potencialno ogrožen" },
  LC: { label: "najmanj ogrožen" },
};

/** Atlas dziadersov: the Slovenian text of the species, keyed by species key. */
export const SPECIES_TEXT: Record<SpeciesKey, Text<Species, Skip>> = {
  grill: {
    name: "Žarni dziaders",
    genitive: "Žarnega dziadersa",
    prefix: "Žarno",
    suffix: "žarni",
    statusNote: "Populacija raste od prvomajskega podaljšanega vikenda do prve slane.",
    teaser: "Klešč ne da iz rok.",
    summary: "Pogosta vrsta, dejavna od prvomajskega podaljšanega vikenda do prve slane. Prepoznavna po kleščah, ki jih ne prepusti nikomur.",
    description: [
      "Žarni dziaders je najbolje raziskana vrsta v Atlasu. Pojavi se s prvim toplim vikendom in zasede mesto ob žaru, ki ga ne zapusti do konca zabave. Klešče obravnava kot insignije oblasti: odda jih le v primeru nujne potrebe in jih takoj po vrnitvi vzame nazaj.",
      "Vrsta ima močno razvit čut za presojo. Že s petnajstih metrov prepozna slabo zakurjen žar, prezgodaj obrnjeno vratovino in podžigalni gel. Svoja opažanja sporoča glasno, navadno z uvodnimi besedami »Tako se pa ne kuri«.",
    ],
    habitat: "Vrtovi, vrtički in balkoni s pogledom na tuj žar. Sezonsko vsa Poljska.",
    activity: "Prevzemanje klešč. Ocenjevanje, kako kurijo drugi.",
    calls: ["Tako se pa ne kuri.", "Vratovina rabi svoj cajt."],
    enemies: "Plinski žar, podžigalni gel, gost, ki je prinesel halloumi.",
    fieldMarks: "Predpasnik z napisom. Klešče v roki tudi daleč od žara.",
    traits: [{ label: "Nadzor nad kleščami" }, { label: "Nezaupanje do plinskega žara" }, { label: "Pripravljenost odstopiti žar" }],
    symptoms: [
      "Prevzame klešče, preden jih gostitelj utegne odložiti.",
      "Kuri izključno s časopisom in vžigalicami. Podžigalni gel je zanj »kemija«.",
      "Vratovino preizkusi s prstom in razglasi, da še ni.",
      "Komentira vsak tuj žar v polmeru sto metrov.",
      "Ima predpasnik z napisom in ga ponosno nosi.",
      "Meni, da klobasa s plinskega žara ni klobasa z žara.",
      "Na koncu dolgo čisti rešetko in pripoveduje o rešetkah, ki jih je imel nekoč.",
    ],
    handling: [
      "Ne približevati se žaru brez povabila.",
      "Hvaliti vratovino, tudi zažgano.",
      "Ne omenjati ne plinskega žara ne halloumija.",
    ],
  },
  parking: {
    name: "Parkirni dziaders",
    genitive: "Parkirnega dziadersa",
    prefix: "Parkirno",
    suffix: "parkirni",
    statusNote: "Populacija stabilna, močno teritorialna.",
    teaser: "Parkira na dveh mestih, da ga nihče ne oplazi.",
    summary: "Močno teritorialna vrsta. Hkrati zaseda dve parkirni mesti in brani tretje, ki ga ima za svoje od leta 1997.",
    description: [
      "Parkirni dziaders živi v tesni povezavi s parkirnim mestom. Pred blokom ima »svoje« mesto, do katerega nima nikakršne pravne podlage, a ga brani z vso odločnostjo. Pred supermarketom pa izbere dve mesti hkrati in avto postavi natanko na črto, da ga nihče ne bi oplazil z vrati.",
      "Vrsta vodi obsežno korespondenco. Listki, puščeni za brisalci tujih avtomobilov, sodijo med najbolje dokumentirane pojave v zbirkah Inštituta. Napisani so na roko, z velikimi tiskanimi črkami, in vedno vsebujejo besedo »vljudno«.",
    ],
    habitat: "Parkirišča pred bloki in supermarketi. Ob nedeljah tudi pred cerkvami.",
    activity: "Zasedanje dveh mest hkrati. Varovanje »svojega« mesta pred blokom.",
    calls: ["To je moje mesto že od sedemindevetdesetega.", "Tukaj pa vi ne boste stali."],
    enemies: "Cona plačljivega parkiranja, voznik SUV-a, risanje novih črt.",
    fieldMarks: "Ko odpelje, na mestu pusti vedro.",
    traits: [{ label: "Teritorialnost" }, { label: "Natančnost parkiranja" }, { label: "Poznavanje predpisov" }],
    symptoms: [
      "Pozna registrske številke avtomobilov vseh sosedov.",
      "Parkira na dveh mestih, da mu nihče ne bi z vrati oplazil avta.",
      "Za brisalce pušča listke. Vedno napisane na roko.",
      "Ko odpelje, na svojem mestu pusti vedro ali stol.",
      "Kroži po parkirišču, dokler se ne sprosti mesto tik ob vhodu.",
      "Cono plačljivega parkiranja ima za napad na osebno svobodo.",
      "Zvečer z balkona preverja, ali avto še stoji.",
    ],
    handling: [
      "Ne parkirati na »njegovem« mestu, tudi če je prosto že tri tedne.",
      "Ne odnašati vedra.",
      "Na listek za brisalcem ne odgovarjati z listkom.",
    ],
  },
  budowa: {
    name: "Gradbeni dziaders",
    genitive: "Gradbenega dziadersa",
    prefix: "Gradbeno",
    suffix: "gradbeni",
    statusNote: "Izpodrivajo ga spletni videoposnetki z navodili.",
    teaser: "»Kdo vam je pa to delal?«",
    summary: "Strokovnjak za tuje prenove. Na vsakem gradbišču vpraša: »Kdo vam je pa to delal?«",
    description: [
      "Gradbeni dziaders se najpogosteje zadržuje v trgovinah s tehničnim blagom, kjer sobotna dopoldneva preživlja ob ogledovanju orodja, ki ga ne bo kupil. Če ga kupi, ga kupi »na zalogo«. Doma ima vsaj tri vrtalnike in niti enega ustreznega svedra.",
      "Posebej dejaven je v navzočnosti mojstrov. Stoji med vrati, opazuje, komentira in pripoveduje, kako je to sam delal leta 1994. Svojih prenov navadno ne dokonča, ima pa zanje popoln načrt, s tesarskim svinčnikom narisan na kartonu.",
    ],
    habitat: "Gradbišča, trgovine s tehničnim blagom, tuje prenove.",
    activity: "Komentiranje dela mojstrov. Kupovanje orodja »na zalogo«.",
    calls: ["Kdo vam je pa to delal?", "Jaz bi to drugače speljal."],
    enemies: "Mavčno-kartonska plošča, mojster s predračunom, laserska libela.",
    fieldMarks: "Tesarski svinčnik za ušesom, nazadnje uporabljen leta 2003.",
    traits: [{ label: "Kritika tujih fug" }, { label: "Samozavest pri elektriki" }, { label: "Dokončevanje začetih prenov" }],
    symptoms: [
      "Mojstra vpraša: »Kdo vam je pa to delal?«, tudi če je to delal isti mojster.",
      "Za ušesom nosi tesarski svinčnik. Tudi v cerkvi.",
      "Orodje kupuje »na zalogo«.",
      "Prenovo kopalnice je začel leta 2019. Napredek: 70 %.",
      "Pri znancih oceni fuge, še preden se sezuje.",
      "Navodil ne bere. Ostanejo mu »rezervni« vijaki.",
      "S členkom potrka po vsaki steni in s tonom diagnoze reče »knauf«.",
    ],
    handling: [
      "Ne spraševati ga za mnenje o prenovi, razen če imaš na voljo celo popoldne.",
      "Ne posojati mu laserske libele. Ne bo je vrnil, ker »ne dela«.",
      "Hvaliti stare fuge.",
    ],
  },
  moto: {
    name: "Avtomobilski dziaders",
    genitive: "Avtomobilskega dziadersa",
    prefix: "Avtomobilsko",
    suffix: "avtomobilski",
    statusNote: "Lokalno pogostejši v bližini postaj za tehnične preglede.",
    teaser: "»Takih pa danes ne delajo več.«",
    summary: "Pogosta vrsta na parkiriščih trgovin s tehničnim blagom. Meni, da je motor pod dvema litroma nesporazum.",
    description: [
      "Avtomobilski dziaders ljudi ocenjuje po avtomobilih, avtomobile pa po zvoku zapiranja vrat. Pred nakupom brcne v gume in prisluhne, čeprav ni še nikoli pojasnil, čemu. Meni, da so najboljše avtomobile izdelovali do leta 2004, vse, kar je nastalo pozneje, pa »ima preveč elektronike«.",
      "Burno se odziva na avtomatske menjalnike, električne avtomobile in sistem start-stop, ki ga izklopi takoj po zagonu motorja. Zimske gume namesti vedno pred prvo slano in o tem vedno poroča.",
    ],
    habitat: "Parkirišča trgovin s tehničnim blagom, garaže, avtomobilske skupine na Facebooku.",
    activity: "Izpodbijanje smiselnosti motorjev pod dvema litroma.",
    calls: ["Takih pa danes ne delajo več.", "Dizel je dizel."],
    enemies: "Avtomatski menjalnik, električni avto, sistem start-stop.",
    fieldMarks: "Pred nakupom brca v gume. Obesek za ključe avtomobila, ki ga nima od leta 2004.",
    traits: [
      { label: "Brcanje v gume pred nakupom" },
      { label: "Nezaupanje do avtomatskega menjalnika" },
      { label: "Strpnost do sistema start-stop" },
    ],
    symptoms: [
      "Pred nakupom brca v gume. In po nakupu.",
      "Sistem start-stop izklopi ob vsakem zagonu motorja.",
      "Pravi: »Takih pa danes ne delajo več.«",
      "Ve, koliko je stal dizel leta 2009.",
      "Nosi obesek za ključe avtomobila, ki ga nima že dvajset let.",
      "Namesto »Kako se pelje?« vpraša »Koliko pa porabi?«",
      "Električni avto ima za igračo. Dizel je dizel.",
    ],
    handling: [
      "Ne hvaliti avtomatskega menjalnika.",
      "Vprašati ga o tlaku v gumah. Pogovor bo trajal eno uro, bo pa prijeten.",
      "Ne parkirati tik ob njem.",
    ],
  },
  wakacje: {
    name: "Počitniški dziaders",
    genitive: "Počitniškega dziadersa",
    prefix: "Počitniško",
    suffix: "počitniški",
    statusNote: "Julija se seli k morju. Vrne se s kompletom magnetov za hladilnik.",
    teaser: "Vetrobran, sandali, nogavice. Ura je 6.30.",
    summary: "Selitvena vrsta. Julija se pojavi ob morju, kjer ob 6.30 postavi vetrobran.",
    description: [
      "Počitniški dziaders enajst mesecev na leto načrtuje dva tedna dopusta. Ob morju je pred soncem: vetrobran¹ stoji ob 6.30, brisače ležijo na ležalnikih ob 6.45, ob 7.00 pa vrsta že komentira cene vafljev.",
      "V tujini išče nekaj, kar spominja na panirani zrezek². Če ne najde ničesar, poseže po sendvičih, prinesenih od doma. Z vsakega potovanja se vrne s kompletom magnetov za hladilnik in z zagorelostjo v obliki majice.",
    ],
    habitat: "Baltska obala od Świnoujścia do Krynice Morske. Sezonsko tudi Hrvaška.",
    activity: "Postavljanje vetrobrana ob zori. Rezerviranje ležalnikov z brisačo.",
    calls: ["Tukaj je zasedeno.", "Ob našem morju vsaj veš, kaj ješ."],
    enemies: "Prepoved vetrobranov, veter z morja, all inclusive brez paniranega zrezka.",
    fieldMarks: "Sandali z nogavicami, pasna torbica, zagorelost v obliki majice.",
    traits: [
      { label: "Zgodnost postavitve vetrobrana" },
      { label: "Odpor do kreme z zaščitnim faktorjem" },
      { label: "Sprijaznjenost s cenami vafljev" },
    ],
    symptoms: [
      "Vetrobran postavi pred sončnim vzhodom.",
      "Ležalnike rezervira z brisačo.",
      "Nosi sandale z belimi frotirnimi nogavicami.",
      "Cene vafljev primerja s cenami iz leta 1998.",
      "V hotelu all inclusive išče panirani zrezek.",
      "Ima pasno torbico, v njej pa potni list, gotovino in sendvič.",
      "Pravi, da ob našem morju vsaj veš, kaj ješ.",
    ],
    handling: [
      "Ne postavljati vetrobrana v njegovem vidnem polju.",
      "Ne spraševati o cenah vafljev.",
      "Magnet za hladilnik sprejeti s hvaležnostjo.",
    ],
    notes: [
      "¹ Vetrobran (pol. parawan): platnena stena na kolih, s katero si poljski kopalci ogradijo svoj kos Baltika. Na Jadranu isto nalogo opravlja brisača na ležalniku.",
      "² Panirani zrezek: na Poljskem kotlet schabowy, svinjski in nedeljski. Slovenski bralec ga pozna kot dunajski zrezek.",
    ],
  },
  facebook: {
    name: "Facebookovski dziaders",
    genitive: "Facebookovskega dziadersa",
    prefix: "Facebookovsko",
    suffix: "facebookovski",
    statusNote: "Najhitreje rastoča populacija v Atlasu.",
    teaser: "Deli. Ne bere. Komentira z velikimi črkami.",
    summary: "Najhitreje rastoča populacija v Atlasu. Deli, preden prebere, in komentira z velikimi črkami.",
    description: [
      "Facebookovski dziaders živi v lokalnih skupinah, verižnih sporočilih in razdelkih s komentarji. Vsebine ocenjuje po naslovu, naslove pa po tem, kako zelo so ga razjezili. Deli »za vsak slučaj«, navadno s pripisom »DELI, PREDEN ZBRIŠEJO!!!«",
      "Vrsta ima profilno sliko z ribo ali avtomobilom in se pod vsak komentar podpiše z imenom in priimkom, tudi pod lastno objavo. Zadnjih nekaj let poseljuje tudi družinske skupine v klepetalnikih, kamor vsako jutro pošlje sličico s kavo in željami za lep dan.",
    ],
    habitat: "Lokalne skupine, komentarji pod članki, verižna sporočila.",
    activity: "Deljenje brez branja. Pisanje z velikimi črkami.",
    calls: ["DELI, PREDEN ZBRIŠEJO!!!", "Kdo se še spomni?"],
    enemies: "Preverjanje dejstev, povezava do vira, vnuk, ki razlaga, da je to fotomontaža.",
    fieldMarks: "Profilna slika z ribo ali avtomobilom. Najmanj trije klicaji.",
    traits: [{ label: "Raba tipke caps lock" }, { label: "Vera v verižna sporočila" }, { label: "Branje članka pred komentiranjem" }],
    symptoms: [
      "Piše z velikimi črkami. Tudi »Dober dan«.",
      "Deli članke, ki jih ni prebral.",
      "Postavi vsaj tri klicaje.",
      "Pod fotografijo sifona za sodavico vpraša »Kdo se še spomni?«",
      "Vsako jutro družini pošlje sličico s kavo.",
      "Komentarje podpisuje z imenom in priimkom.",
      "Verjame v verižna sporočila. Za vsak primer.",
    ],
    handling: [
      "Ne pošiljati mu povezave na preverjanje dejstev. Delil jo bo kot dokaz zarote.",
      "Odzvati se s srčkom. To zadošča.",
      "Družinsko skupino utišati, ne pa je zapustiti.",
    ],
  },
  smart: {
    name: "Smart-home dziaders",
    genitive: "Smart-home dziadersa",
    prefix: "Tehnološko",
    suffix: "tehnološki",
    statusNote: "Mlada vrsta, opisana leta 2023. Populacija je odvisna od vnukov.",
    teaser: "Pametne žarnice ugaša s stikalom.",
    summary: "Mlada vrsta, opisana leta 2023. Kupuje pametne naprave in jih upravlja s stikalom.",
    description: [
      "Smart-home dziaders je najmlajša vrsta v Atlasu. Ima pametne žarnice, pametni sesalnik in pametni termostat, uporablja pa jih izključno ročno. Aplikacijo mu je namestil vnuk, geslo za wifi visi na listku pod usmerjevalnikom, usmerjevalnik pa ponoči izklaplja, »da se spočije«.",
      "Populacija je močno odvisna od mlajših družinskih članov, ki jih ob vsaki posodobitvi pokliče po telefonu. Vrsta ne zaupa oblaku, zaupa pa zunanjim diskom, ki jih hrani v predalu s kabli.",
    ],
    habitat: "Nova naselja, enodružinske hiše z dvoriščnimi vrati na daljinsko upravljanje.",
    activity: "Kupovanje pametnih naprav in njihovo ročno upravljanje.",
    calls: ["Vnukec mi je to nastavil.", "Kaj mi bo aplikacija, če pa imam stikalo?"],
    enemies: "Posodobitev programske opreme, geslo za wifi, dvostopenjsko preverjanje.",
    fieldMarks: "Geslo za wifi na listku, prilepljenem pod usmerjevalnik.",
    traits: [{ label: "Število pametnih naprav v domu" }, { label: "Odvisnost od vnuka" }, { label: "Uporaba aplikacije" }],
    symptoms: [
      "Pametne žarnice ugaša s stikalom.",
      "Usmerjevalnik ponoči izklopi, da se spočije.",
      "Geslo za wifi hrani na listku pod usmerjevalnikom.",
      "Pokliče, da preveri, ali je e-sporočilo prispelo.",
      "Glasovnemu pomočniku govori vse glasneje.",
      "S telefonom fotografira zaslon računalnika.",
      "Pri vsaki posodobitvi pritisne »Opomni me pozneje«.",
    ],
    handling: [
      "Ne spreminjati gesla za wifi.",
      "Po namestitvi aplikacije vse zapisati na listek. Z velikimi tiskanimi črkami.",
      "Ne izdati mu, da se sesalnik lahko vozi sam.",
    ],
  },
  dzialka: {
    name: "Vrtičkarski dziaders",
    genitive: "Vrtičkarskega dziadersa",
    prefix: "Vrtičkarsko",
    suffix: "vrtičkarski",
    statusNote: "Uta iz leta 1983. Načrti za njeno dozidavo prav tako.",
    teaser: "Uta iz leta 1983. Načrti za dozidavo tudi.",
    summary: "Prebivalec vrtičkarskih območij. Uta iz leta 1983, načrti za dozidavo prav tako.",
    description: [
      "Vrtičkarski dziaders na vrtičku preživi čas od odprtja sezone v marcu do zadnjega izkopanega korenja. Vrtnari z industrijskim zamahom, pridelek pa primerja s pridelkom soseda za mrežo in mu ob tem svetuje, kako se privezuje paradižnik.",
      "Središče teritorija je uta. Zgrajena je bila leta 1983 iz pločevine, ladijskega poda in vrat stare omare, od leta 1983 pa čaka na dozidavo. V njej stojijo radio, naravnan na eno samo postajo, in vsi predmeti, ki »bodo še prišli prav«.",
    ],
    habitat: "Vrtičkarska območja. Ute iz pločevine in ladijskega poda.",
    activity: "Primerjanje paradižnikov. Svetovanje sosedom čez mrežo.",
    calls: ["Moji so pa že zdavnaj nastavili.", "Včasih je bil paradižnik še paradižnik."],
    enemies: "Voluhar, lazar, upravni odbor vrtičkarskega društva.",
    fieldMarks: "Slamnik. Radio, od leta 1991 naravnan na eno samo postajo.",
    traits: [{ label: "Paradižnikovo rivalstvo" }, { label: "Nadzor nad sosedovo ozaro" }, { label: "Strpnost do krtov" }],
    symptoms: [
      "Svoje paradižnike primerja s sosedovimi. Na glas.",
      "Svetuje čez mrežo, ne da bi ga kdo vprašal za mnenje.",
      "Ima uto iz leta 1983 in načrt za njeno dozidavo iz istega leta.",
      "Posluša radio, od leta 1991 naravnan na eno samo postajo.",
      "Družini vozi bučke v veleprodajnih količinah.",
      "Pozna vsakega krta na vrtičku. Nobenega ne trpi.",
      "Meni, da »kupljeno ni isto«.",
    ],
    handling: ["Sprejemati bučke. Vse.", "Ne hvaliti paradižnikov iz supermarketa.", "V uti se ničesar ne dotikati."],
  },
  wedka: {
    name: "Ribiški dziaders",
    genitive: "Ribiškega dziadersa",
    prefix: "Ribiško",
    suffix: "ribiški",
    statusNote: "Njegova zatočišča izginjajo pod vikendi.",
    teaser: "Vstane ob 4.00. Ne ujame ničesar. Vrne se zadovoljen.",
    summary: "Vstane ob štirih, ne ujame ničesar in se vrne zadovoljen. Riba, ki je ni ujel, je bila takšna.",
    description: [
      "Ribiški dziaders ima nočno-jutranji življenjski ritem. Ob štirih že sedi ob vodi, v telovniku s štirinajstimi žepi, s termovko in v popolnem molku, ki ga prekine le zato, da pove, da danes nič ne prijema.",
      "Vrsta slovi po zgodbah. Ujete ribe rastejo z vsako pripovedjo, tiste, ki so ušle s trnka, pa dosežejo velikost, ki ogroža plovbo. Naravna sovražnika sta kolega, ki je ujel več, in kajakaš, ki je »vse splašil«.",
    ],
    habitat: "Bregovi jezer, akumulacije, kanali. Vedno »preverjeno mesto«.",
    activity: "Vstajanje ob štirih. Molk. Lovljenje ničesar.",
    calls: ["Takle je bila.", "Danes ni prijemalo."],
    enemies: "Kajakaš, zračni tlak, kolega, ki je kaj ujel.",
    fieldMarks: "Telovnik s štirinajstimi žepi, termovka, odsotnost ribe.",
    traits: [{ label: "Zgodnost vstajanja" }, { label: "Pretiravanje pri opisu ujete ribe" }, { label: "Število ujetih rib" }],
    symptoms: [
      "Vstaja ob štirih, tudi ob nedeljah.",
      "Ko pripoveduje o ribi, razpre roke. Vsakič širše.",
      "Dan povzame z besedami »danes ni prijemalo«.",
      "Ima telovnik s štirinajstimi žepi in ve, kaj je v vsakem.",
      "Krivdo zvali na zračni tlak.",
      "Ima »preverjeno mesto«, ki ga ne izda niti družini.",
      "Vrne se brez ribe, a v odličnem razpoloženju.",
    ],
    handling: ["Ne spraševati, koliko je ujel.", "Ne veslati mimo njega s kajakom.", "Čestitati za ribo, ki je ni nihče videl."],
  },
  korpo: {
    name: "Korporativni dziaders",
    genitive: "Korporativnega dziadersa",
    prefix: "Korporativno",
    suffix: "korporativni",
    statusNote: "Odporen na zaporedna prestrukturiranja.",
    teaser: "Tiska mejle. Pravi »dajmo en call«.",
    summary: "Pisarniška vrsta. Tiska mejle, sklicuje sestanke, ki bi lahko bili mejl, in vsako sporočilo konča z »Lep pozdrav«.",
    description: [
      "Korporativni dziaders poseljuje poslovne stavbe razreda A, sejne sobe in pisalno mizo ob oknu, ki jo zaseda še iz časov, ko je bilo podjetje v drugi stavbi. Pravi »dajmo en call«, po vsakem callu pa natisne zapisnik, ga skenira in pošlje po mejlu.",
      "Vrsta je odporna na zaporedna prestrukturiranja, digitalne preobrazbe in menjave klepetalnikov. Dela od doma ne priznava: »Včasih se je delalo, ne pa home office.« Ob petkih nosi kravato, da pokaže, da je tudi petek delovni dan.",
    ],
    habitat: "Poslovne stavbe razreda A, sejne sobe, pisalna miza ob oknu.",
    activity: "Tiskanje mejlov. Sklicevanje sestankov, ki bi lahko bili mejl.",
    calls: ["Dajmo en call.", "Včasih se je delalo, ne pa home office."],
    enemies: "Delo od doma, službeni klepetalnik, mlajši vodja.",
    fieldMarks: "»Lep pozdrav« v vsakem sporočilu, tudi v klepetu.",
    traits: [{ label: "Sestanki, ki bi lahko bili mejl" }, { label: "Tiskanje mejlov" }, { label: "Zaupanje v oblak" }],
    symptoms: [
      "Mejle natisne, da jih lahko prebere.",
      "Vsako sporočilo konča z »Lep pozdrav«, tudi v klepetu.",
      "Skliče sestanek, da bi se pogovorili o prejšnjem sestanku.",
      "Pokliče, da vpraša, ali je mejl prispel.",
      "Pravi »dajmo en call«, potem pa pride osebno.",
      "V predalu ima spenjač, ki ga ne posodi nikomur.",
      "Meni, da je delo od doma dopust.",
    ],
    handling: [
      "Na mejl odgovoriti z mejlom. Ne s smeškom.",
      "Ne premikati njegovega spenjača.",
      "Na sestanku, ki bi lahko bil mejl, ohraniti mirno kri.",
    ],
  },
  zeglarz: {
    name: "Jadralski dziaders",
    genitive: "Jadralskega dziadersa",
    statusNote: "Zadnjo plovbo je opravil leta 1978 in od takrat pripoveduje o njej.",
    teaser: "»Tukaj jadram od oseminsedemdesetega.«",
    summary: "Obrežna vrsta Mazurskih jezer. Tukaj jadra od oseminsedemdesetega, čeprav nazadnje oseminsedemdesetega.",
    description: [
      "Jadralski dziaders naseljuje pomole in krčme Mazurije, od koder z neodobravanjem opazuje sodobno jadranje. Vsako jadrnico oceni po tem, kako ima zložene vrvi, vsako posadko po poznavanju šant¹, vsak veter pa po tem, ali je »to pravi veter«. Navadno ni.",
      "Zadnjo plovbo je opravil leta 1978 in od takrat o njej pripoveduje z vse več podrobnostmi. Kapitansko kapo nosi vso sezono, čeprav nima ne jahte ne izpita za voditelja čolna ne načrtov, da bi ju pridobil.",
    ],
    habitat: "Pomoli in krčme na Mazurskih jezerih. Največ jih je v Giżycku in Mikołajkih.",
    activity: "Pripovedovanje o plovbah. Ocenjevanje, kako drugi zlagajo vrvi.",
    calls: ["Tukaj jadram od oseminsedemdesetega.", "To ni pravi veter."],
    enemies: "Motorni čoln, čarter z navigacijo v telefonu, prepoved vstopa na pomol.",
    fieldMarks: "Kapitanska kapa brez jahte. Mornarski vozel na vsaki vrvici v hiši, vključno z zaveso.",
    traits: [{ label: "Poznavanje vozlov" }, { label: "Samozavest za tujim krmilom" }, { label: "Strpnost do motornih čolnov" }],
    symptoms: [
      "Nosi kapitansko kapo, čeprav nima jahte.",
      "Na vrvici za zaveso naveže reševalni vozel.",
      "S pomola oceni vsak manever tujega čolna.",
      "Ob 23.00 poje šante. Vse kitice.",
      "Trdi, da današnji veter ni pravi veter.",
      "Kuhinji pravi kambuza, tlom pa krov.",
      "O plovbi iz leta 1978 pripoveduje vsak teden, vsakič dlje.",
    ],
    handling: [
      "V njegovi navzočnosti ne privezovati čolna.",
      "Poznati vsaj eno šanto. Zadošča refren.",
      "Ne kazati mu navigacije v telefonu.",
    ],
    notes: ["¹ Šante (pol. szanty): mornarske pesmi, ki jih na Poljskem najraje pojejo jadralci na jezerih, daleč od morja."],
  },
  grzybiarz: {
    name: "Gobarski dziaders",
    genitive: "Gobarskega dziadersa",
    statusNote: "Populacija septembra eksplodira, po prvem izdatnem deževju.",
    teaser: "Ve za rastišča. Ne bo povedal.",
    summary: "Gozdna vrsta, dejavna septembra in oktobra. Rastišča pozna že štirideset let in jih ne izda nikomur.",
    description: [
      "Gobarski dziaders se v gozdu pojavi pred zoro, dan po prvem izdatnem dežju. Premika se hitro in neslišno, na vprašanja o poti pa odgovarja izmikajoče. Svoja rastišča pozna že štirideset let in jih varuje učinkoviteje kot marsikatera država svoje meje.",
      "Vrsta prezira aplikacije za prepoznavanje gob in gobarske atlase, saj je nezmotljiva, vsaj po lastnem mnenju. Po vrnitvi iz gozda postavi košaro na vidno mesto in čaka, da kdo vpraša. Na vprašanje »Kje?« odgovori »V gozdu«.",
    ],
    habitat: "Gozdovi Podlasja, zlasti Puszcza Knyszyńska. Natančna rastišča so zaupne narave.",
    activity: "Nabiranje gob pred zoro. Prikrivanje rastišč. Primerjanje košar.",
    calls: ["Ta mesta poznam že štirideset let.", "Tukaj so včasih rasli jurčki."],
    enemies: "Gobar z aplikacijo, suša, turist, ki se »samo sprehaja«.",
    fieldMarks: "Pletena košara, nožek z leseno ročko, gumijasti škornji tudi v suhem vremenu.",
    traits: [{ label: "Diskretnost glede rastišč" }, { label: "Zgodnost odhoda v gozd" }, { label: "Zaupanje v gobarski atlas" }],
    symptoms: [
      "V gozd odide pred zoro, da nihče ne vidi, kam gre.",
      "Na vprašanje »Kje?« odgovori »V gozdu«.",
      "Na gozdnem parkirišču primerja svojo košaro s tujimi.",
      "Pravi, da so tukaj včasih rasli jurčki.",
      "Gobo vedno odreže pri tleh, nikoli je ne izruva. In o tem predava.",
      "Gobe suši na nitki nad radiatorjem.",
      "Rastišča pozna že štirideset let. Ne bo povedal.",
    ],
    handling: [
      "Ne hoditi za njim v gozd.",
      "Ne spraševati o rastiščih.",
      "Sprejeti kozarec suhih gob in ne spraševati o poreklu.",
    ],
  },
  przygraniczny: {
    name: "Obmejni dziaders",
    genitive: "Obmejnega dziadersa",
    statusNote: "Populacija se je povečala po letu 2004, z odprtjem meja.",
    teaser: "Prevozi 40 km, da natoči 3 groše ceneje.",
    summary: "Selitvena vrsta obmejnega pasu. Prevozi 40 kilometrov, da kaj kupi 3 groše ceneje, in je na to ponosna.",
    description: [
      "Obmejni dziaders naseljuje Lubuško vojvodstvo¹ in se redno seli čez mejo po gorivo, kavo, pralni prašek in prepričanje, da je »tam ceneje«. Razliko v ceni pozna na groš natančno, stroške vožnje pa dosledno spregleda.",
      "Z vsakega pohoda se vrne s polnim prtljažnikom in zgodbo o prihrankih, ki jih je izračunal na poti nazaj. Posebej ceni nakupe na debelo, ker se »splača, če vzameš več«.",
    ],
    habitat: "Obmejni pas Lubuškega vojvodstva. Bencinske črpalke, tržnice in parkirišča trgovskih centrov na obeh straneh meje.",
    activity: "Primerjanje cen na obeh straneh meje. Točenje goriva do vrha, tudi v kanistre.",
    calls: ["Tam je za tri groše ceneje.", "Splača se, če vzameš več."],
    enemies: "Menjalni tečaj, vrsta na meji, vprašanje o stroških goriva za pot.",
    fieldMarks: "Kanister v prtljažniku. Računi iz dveh držav v predalu armaturne plošče.",
    traits: [
      { label: "Natančnost primerjanja cen" },
      { label: "Upoštevanje stroškov vožnje" },
      { label: "Izkoriščenost prtljažnika" },
    ],
    symptoms: [
      "Prevozi 40 km, da natoči 3 groše ceneje.",
      "Vozi kanister. Za vsak primer.",
      "Pralni prašek kupuje v pakiranjih za pet let.",
      "Pomni menjalne tečaje zadnjih dvajsetih let.",
      "Ve, ob kateri uri na meji ni vrste.",
      "Stroške goriva iz računa prihrankov izpusti.",
      "Za vsako sosednjo državo pravi, da je »tam ceneje«.",
    ],
    handling: [
      "V njegovi navzočnosti ne računati stroškov vožnje.",
      "Sprejeti tujo kavo in se začuditi, da je tako poceni.",
      "Ne omenjati akcije v trgovini v soseski. Odpeljal se bo preverit.",
    ],
    notes: [
      "¹ Lubuško vojvodstvo: leži na zahodu Poljske, ob nemški meji. Slovenski bralec pozna pojav z obratne strani: s črpalk ob meji, kamor po cenejše gorivo prihajajo Avstrijci in Italijani.",
    ],
  },
  oszczednosciowy: {
    name: "Varčni dziaders",
    genitive: "Varčnega dziadersa",
    statusNote: "Populacija stabilna, dejavnost se povečuje v času razprodaj.",
    teaser: "Vrečke hrani v vrečki.",
    summary: "Velikopoljska vrsta. Vrečke hrani v vrečki, za drugimi ugaša luč in pozna vse akcijske letake.",
    description: [
      "Varčni dziaders je na Velikopoljskem¹ vodil krožno gospodarstvo, še preden je to postalo modno. Vrečke hrani v vrečki, kozarce umije in razvrsti po velikosti, aluminijasto folijo pa zgladi in jo uporabi znova. Pred vsakim nakupom preuči akcijske letake s pozornostjo, ki pritiče predpisom.",
      "Vrsta za domačimi ugaša luč, med umivanjem zob zapira pipo in pazi, da okna ob vključenem ogrevanju niso odprta. Na vse to je zelo ponosna in navadno ima prav, kar razpravo še dodatno otežuje.",
    ],
    habitat: "Velikopoljska, z največjo gostoto v Poznanju. Akcijske ponudbe v polmeru desetih kilometrov.",
    activity: "Zbiranje vrečk, kozarcev in akcijskih letakov. Ugašanje luči za drugimi.",
    calls: ["Ne meči stran, to se bo splaknilo.", "Ugasni luč, elektrika ni zastonj."],
    enemies: "Plačljiva vrečka, odprto okno ob vključenem ogrevanju, račun brez popusta.",
    fieldMarks: "Vrečka z vrečkami pod pomivalnim koritom. Kozarci, razvrščeni po velikosti.",
    traits: [{ label: "Zbiranje vrečk" }, { label: "Poznavanje akcijskih letakov" }, { label: "Izdatki brez očitne potrebe" }],
    symptoms: [
      "Vrečke hrani v vrečki.",
      "Ugasne luč za vsakim, ki zapusti sobo.",
      "Aluminijasto folijo opere in jo uporabi znova.",
      "Akcijske letake pozna bolje kot televizijski spored.",
      "Kozarce razvršča po velikosti.",
      "Pravi: »Ne meči stran, to se bo splaknilo.«",
      "Ve, koliko je stal vsak predmet v hiši.",
    ],
    handling: [
      "V njegovi navzočnosti ne metati vrečk stran.",
      "Ugasniti luč, preden jo ugasne on.",
      "Ne govoriti, koliko je kaj stalo.",
    ],
    notes: [
      "¹ Velikopoljska: pokrajina okoli Poznanja, katere prebivalci na Poljskem slovijo po varčnosti. Na Slovenskem enak sloves uživajo Gorenjci.",
    ],
  },
  uzdrowiskowy: {
    name: "Zdraviliški dziaders",
    genitive: "Zdraviliškega dziadersa",
    statusNote: "Populacija se obnovi vsaka dva tedna, v ritmu turnusov.",
    teaser: "Ciechocinek, solni zidovi, plesni večer. Več ni treba reči.",
    summary: "Zdraviliška vrsta. V ritmu dvotedenskih turnusov poseljuje solne zidove in plesne večere v Ciechocinku.",
    description: [
      "Zdraviliški dziaders se v zdravilišču, najraje v Ciechocinku¹, pojavi v ritmu turnusov in nemudoma prevzame nadzor nad klopjo ob solnem zidu². Zjutraj vdihava slanico, popoldne hodi na terapije, zvečer pa obleče suknjič in se odpravi na plesni večer, kjer prikaže korake, osvojene v sedemdesetih letih.",
      "Vrsta živi bogato družabno življenje. Vsak turnus se konča z izmenjavo naslovov, obljubo, da ostanejo v stiku, in ugotovitvijo, da je bilo »na turnusu lepše kot doma«. Po vrnitvi ves teden pripoveduje o terapijah, na minuto natančno.",
    ],
    habitat: "Zdravilišča, zlasti Ciechocinek. Solni zidovi, sprehajališča in plesne dvorane zdraviliških domov.",
    activity: "Vdihavanje slanice ob solnih zidovih. Plesni večeri. Primerjanje turnusov.",
    calls: ["Na turnusu je bilo lepše kot doma.", "Gospa, smem prositi za ples?"],
    enemies: "Konec turnusa, dež na sprehajališču, orkester, ki igra prehitro.",
    fieldMarks: "Suknjič za ples, urnik terapij v žepu, zagorelost s klopi ob solnem zidu.",
    traits: [{ label: "Udeležba na plesnih večerih" }, { label: "Poznavanje terapij" }, { label: "Želja po vrnitvi domov" }],
    symptoms: [
      "Ob sedmih zjutraj zasede klop ob solnem zidu.",
      "Ima suknjič, namenjen izključno plesu.",
      "Pozna imena vseh terapij in ve, za kaj pomagajo.",
      "Na ples povabi z besedami »Smem prositi?«",
      "Družini prinese mineralno vodo, ki je nihče ne bo popil.",
      "Turnuse primerja: »Lani je bil orkester boljši.«",
      "Po vrnitvi pripoveduje o terapijah na minuto natančno.",
    ],
    handling: [
      "Ne zavračati plesa brez tehtnega razloga.",
      "Spraševati ga o terapijah. Rad govori o njih.",
      "Ne sedati na njegovo klop ob solnem zidu.",
    ],
    notes: [
      "¹ Ciechocinek: zdraviliško mesto ob Visli, znano po plesnih večerih in zdraviliških romancah. Slovenski bralec ga pozna iz Rogaške Slatine.",
      "² Solni zid (pol. tężnia): visoka lesena konstrukcija, obložena s protjem, po kateri polzi slanica. Gostje sedijo ob njej in dihajo.",
    ],
  },
  gorski: {
    name: "Gorski dziaders",
    genitive: "Gorskega dziadersa",
    statusNote: "Poti vse pogosteje zasedajo osebe v pohodniških čevljih.",
    teaser: "Na Śnieżko v sandalih. V vsaki koči vpraša, koliko stane čaj.",
    summary: "Visokogorska vrsta Sudetov. Na Śnieżko se povzpne v sandalih in v vsaki koči komentira ceno čaja.",
    description: [
      "Gorski dziaders osvaja vrhove Krkonoš v sandalih, nogavicah in z občutkom večvrednosti do oseb v specializirani obutvi. Na poti se giblje presenetljivo hitro in prehiteva pohodnike s palicami ter pripominja, da so palice »za penzioniste«, čeprav je sam upokojen.",
      "V vsaki koči se ustavi, da povpraša po ceni čaja, nato pa izvleče svojo termovko. Spominja se časov, ko se je na Śnieżko¹ hodilo peš iz Karpacza, čaj pa je stal toliko kot danes vstop na stranišče.",
    ],
    habitat: "Poti v Krkonošah in pogorju Góry Stołowe, planinske koče, parkirišča na izhodiščih poti.",
    activity: "Osvajanje vrhov v neprimerni obutvi. Komentiranje cen v kočah.",
    calls: ["Koliko za čaj? V mojih časih je bil zastonj.", "Včasih se je šlo peš iz Karpacza."],
    enemies: "Cena čaja v koči, sedežnica, pohodnik s palicami.",
    fieldMarks: "Sandali z nogavicami na 1600 metrih nadmorske višine. Termovka s čajem, da mu v koči ni treba plačati.",
    traits: [{ label: "Hitrost vzpona" }, { label: "Opremljenost" }, { label: "Komentiranje cen v koči" }],
    symptoms: [
      "Na Śnieżko se povzpne v sandalih.",
      "V vsaki koči vpraša po ceni čaja.",
      "Na terasi koče pije čaj iz lastne termovke.",
      "Prehiteva pohodnike s palicami in komentira palice.",
      "Ve, koliko je stalo prenočišče v koči leta 1985.",
      "Sedežnico ima za goljufijo.",
      "Na vrhu pravi: »Včasih se je videlo več.«",
    ],
    handling: [
      "Ne predlagati sedežnice.",
      "Zanj vzeti čaj v termovki. Cenil bo gesto in prihranek.",
      "Ne komentirati sandalov.",
    ],
    notes: ["¹ Śnieżka: najvišji vrh Krkonoš (1603 m), na poljsko-češki meji. Slovenski bralec isto obutev pozna s Triglava."],
  },
  festiwalowy: {
    name: "Festivalski dziaders",
    genitive: "Festivalskega dziadersa",
    statusNote: "Vsako leto znova potrdi, da so bile včasih pesmi boljše.",
    teaser: "Vsako leto gleda festival, da se prepriča, da so bile včasih pesmi boljše.",
    summary: "Televizijska vrsta. Vsako leto gleda festival popevk, da se prepriča, da so bile včasih pesmi boljše.",
    description: [
      "Festivalski dziaders gleda vse festivale popevk¹, čeprav mu ni všeč noben. To počne iz občutka dolžnosti: nekdo mora potrditi, da so bile pesmi včasih boljše, da so izvajalci peli, ne pa kričali, in da so voditelji govorili razločno.",
      "Vrsta pozna refrene vseh uspešnic izpred leta 1985 in jih poje skupaj s televizorjem, ne da bi poznala kitice. Nove izvajalce ocenjuje izključno po tem, ali je »to petje«. Navadno ni.",
    ],
    habitat: "Pred televizorjem junija, med festivalom popevk. Občasno amfiteatri.",
    activity: "Gledanje festivalov popevk. Primerjanje izvajalcev z izvajalci izpred let.",
    calls: ["To so bile včasih pesmi.", "To ni petje, to je kričanje."],
    enemies: "Autotune, rap, voditelj, ki govori prehitro.",
    fieldMarks: "Poje refrene uspešnic iz sedemdesetih, ne da bi poznal kitice. Daljinec v roki, če bi prišli oglasi.",
    traits: [
      { label: "Poznavanje refrenov izpred leta 1985" },
      { label: "Strpnost do autotuna" },
      { label: "Glasnost petja s televizorjem" },
    ],
    symptoms: [
      "Festival gleda samo zato, da ga lahko kritizira.",
      "Pravi: »To so bile včasih pesmi.«",
      "Poje refrene, ne da bi poznal kitice.",
      "Autotune prepozna v prvi sekundi.",
      "Rap ima za govorjenje ob glasbi.",
      "Ve, kdo je zmagal na festivalu leta 1979.",
      "Glasnost poveča samo pri pesmih izpred štiridesetih let.",
    ],
    handling: [
      "V avtu ne vklapljati rapa.",
      "Vprašati ga za najljubšo pesem iz sedemdesetih. Sledila bo izvedba v celoti.",
      "Ne razpravljati o rezultatih festivala.",
    ],
    notes: [
      "¹ Festivali popevk: na Poljskem predvsem festival v Opolu, ki ga televizija prenaša vsak junij od leta 1963. Slovenski bralec ga pozna kot Slovensko popevko.",
    ],
  },
  golebiarz: {
    name: "Golobarski dziaders",
    genitive: "Golobarskega dziadersa",
    statusNote: "Golobnjaki se umikajo parkiriščem.",
    teaser: "Golobnjak ima novejšo streho kot hiša.",
    summary: "Šlezijska vrsta. Goji golobe pismonoše, golobnjak pa ima novejšo streho kot hiša.",
    description: [
      "Golobarski dziaders že več desetletij goji golobe pismonoše in z njimi ravna z nežnostjo, kakršne ne izkazuje nikomur drugemu. Golobnjak redno popravlja, izolira in obnavlja, medtem ko streha hiše čaka na vrsto od leta 1986.",
      "Ob tekmovalnih nedeljah se ne odmakne od golobnjaka in vrnitve pričakuje na sekundo natančno. Vsako vrnitev iz tujine družini opiše s podrobnostmi, vrednimi športnega prenosa.",
    ],
    habitat: "Golobnjaki na strehah in vrtovih Zgornje Šlezije. Razstave in tekmovalni leti.",
    activity: "Vzreja golobov pismonoš. Pričakovanje vrnitev. Obnavljanje golobnjaka.",
    calls: ["Vrnila se je! Iz Nizozemske, v devetih urah!", "Golobi niso hobi, to je šport."],
    enemies: "Kragulj, sosed, ki se pritožuje nad golobi, deževna tekmovalna nedelja.",
    fieldMarks: "Tekmovalna ura na častnem mestu v hiši. Golobnjak z novo streho poleg hiše s staro.",
    traits: [{ label: "Naložbe v golobnjak" }, { label: "Poznavanje rodovnikov golobov" }, { label: "Naložbe v streho hiše" }],
    symptoms: [
      "Golobnjak ima novejšo streho kot hiša.",
      "Ob tekmovalni nedelji se ne premakne od okna.",
      "Rodovnike golobov pozna do pete generacije.",
      "O golobih govori »ona« in »on«, o sosedih »tisti tam«.",
      "Meni, da so golobi šport, ne hobi.",
      "Vrnitev goloba iz Nizozemske opisuje kot finale svetovnega prvenstva.",
      "Sovraži kragulje. Občutek je obojestranski.",
    ],
    handling: ["Za golobe ne uporabljati besede »ptiči«.", "Ne spraševati o strehi hiše.", "Ob tekmovalni nedelji ne klicati."],
  },
  jurajski: {
    name: "Jurski dziaders",
    genitive: "Jurskega dziadersa",
    statusNote: "Trdi, da je videl izumiranje dinozavrov, in ne namerava biti naslednji.",
    teaser: "Spominja se časov, ko je bilo vse boljše. Vključno z dinozavri.",
    summary: "Svetokriška vrsta z izjemno dolgim spominom. Spominja se časov, ko je bilo vse boljše, vključno z dinozavri.",
    description: [
      "Jurski dziaders ima najdaljši spomin v Atlasu. Njegovi spomini z vsakim letom segajo dlje: začel je pri Ljudski republiki Poljski (PRL)¹, nadaljeval z obdobjem med vojnama in prišel vse do jure, ko je bilo po njegovih besedah vse boljše, večje in cenejše. Vključno z dinozavri.",
      "Vrsta naseljuje okolico Svetokriškega gorovja, ki ga ima za eno najstarejših gorovij v Evropi in hkrati za gorovje, ki je bilo »včasih višje«. Prva trditev drži. Druga tudi, čeprav ne iz razlogov, ki jih navaja.",
    ],
    habitat: "Svetokriško gorovje, okolica Łysice, dinozavrski parki in jame. Klopi pred trgovino v Kielcah.",
    activity: "Spominjanje starih časov, ki segajo vse dlje nazaj.",
    calls: ["V mojih časih so bili dinozavri, ne pa to danes.", "Včasih so bile gore višje."],
    enemies: "Zgodovinska dejstva, vodnik z diplomo, vnuk z enciklopedijo.",
    fieldMarks: "Zgodbe, ki se začnejo z »V mojih časih« in segajo v mezozoik.",
    traits: [{ label: "Globina spominov" }, { label: "Skladnost spominov z dejstvi" }, { label: "Navezanost na Łysico" }],
    symptoms: [
      "Vsako zgodbo začne z »V mojih časih«.",
      "Njegovi »časi« segajo vse dlje nazaj.",
      "Trdi, da so bile gore včasih višje. Ima prav, a ne zaradi tega.",
      "Popravlja vodnike v dinozavrskih parkih.",
      "Meni, da so dinozavri izumrli, ker se niso znali prilagoditi.",
      "V žepu nosi fosil in ga pokaže, ne da bi ga kdo vprašal.",
      "Pravi, da so bili včasih plazilci še plazilci.",
    ],
    handling: ["Ne popravljati letnic.", "Navdušiti se nad fosilom.", "Ne omenjati asteroida."],
    notes: [
      "¹ Ljudska republika Poljska (PRL): socialistična Poljska, do leta 1989. Slovenski bralec isto obdobje pozna iz stavkov, ki se začnejo z »za Jugoslavije«.",
    ],
  },
  meteorologiczny: {
    name: "Meteorološki dziaders",
    genitive: "Meteorološkega dziadersa",
    statusNote: "Populacija stabilna, dejavnost se poveča ob vsaki spremembi zračnega tlaka.",
    teaser: "Vreme napoveduje s kolenom. Uspešnost: 54 %.",
    summary: "Lublinska vrsta z razvitim barometrskim čutom. Vreme napoveduje s kolenom, uspešno v 54 % primerov.",
    description: [
      "Meteorološki dziaders napoveduje vreme na podlagi stanja kolena, križa in brazgotine po operaciji iz leta 1987. Po raziskavah Inštituta se njegove napovedi uresničijo v 54 % primerov. Vrsta to šteje za boljši rezultat od televizijskega, zato vremenskih napovedi na televiziji ne gleda, razen zato, da jih komentira.",
      "Vsaka sprememba zračnega tlaka pri vrsti sproži povečano sporazumevalno dejavnost. Na avtobusnih postajališčih in klopeh pred hišami izvaja meteorološka posvetovanja, ki se brez izjeme končajo z ugotovitvijo, da so bile včasih zime še zime.",
    ],
    habitat: "Okolica Lublina, klopi pred hišami, avtobusna postajališča. Povsod, kjer se da pogovoriti o vremenu.",
    activity: "Napovedovanje vremena na podlagi tegob. Komentiranje televizijskih napovedi.",
    calls: ["Dež bo, v kolenu me trga.", "Včasih so bile zime še zime."],
    enemies: "Vremenoslovec na televiziji, vremenska aplikacija, sončen dan, ki ga je koleno napovedalo kot deževnega.",
    fieldMarks: "Pogleda v nebo in reče »vreme se bo obrnilo«. Barometer v predsobi, ki ga preverja pogosteje kot telefon.",
    traits: [{ label: "Zaupanje v lastno koleno" }, { label: "Uspešnost napovedi" }, { label: "Zaupanje v vremenoslovce" }],
    symptoms: [
      "Dež napove s kolenom.",
      "V predsobi ima barometer in ga preverja pogosteje kot telefon.",
      "Pogleda v nebo in reče »vreme se bo obrnilo«.",
      "Napoved na televiziji komentira: »Kako pa oni to vedo?«",
      "Zimo leta 1979 pomni na centimeter snega natančno.",
      "Na vprašanje »Kako si?« odgovori »Tlak pada«.",
      "Meni, da je bilo vreme včasih bolj vremensko.",
    ],
    handling: [
      "Če on tako pravi, vzeti dežnik. Za vsak primer.",
      "Ne kazati mu vremenske aplikacije.",
      "Vprašati ga o zimi leta 1979 in se udobno namestiti.",
    ],
  },
  krupowkowy: {
    name: "Krupówkovski dziaders",
    genitive: "Krupówkovskega dziadersa",
    statusNote: "Populacija doseže vrh med zimskimi počitnicami in ob podaljšanih vikendih.",
    teaser: "Kupi oscypek in pravi, da je bil včasih večji.",
    summary: "Tatranska vrsta. Na Krupówkih kupi oscypek in pravi, da je bil včasih večji.",
    description: [
      "Krupówkovski dziaders prihaja v Zakopane od leta 1968 in od leta 1968 meni, da je bilo včasih bolje. Oscypki¹ so bili večji, cene nižje, gorali pa pristnejši. Kljub temu vsako leto kupi oscypek, ciupago² in pulover iz ovčje volne, ki ga potem vso sezono nosi v avtu.",
      "Precejšen del bivanja preživi v zastoju na cesti v Zakopane, ki ga komentira z naraščajočim ogorčenjem in brez kančka zavedanja, da v njem stoji tudi sam. Po Krupówkih³ se premika počasi, ogleda si vsako stojnico in primerja cene s tistimi, ki si jih je zapomnil ob prejšnjem obisku.",
    ],
    habitat: "Krupówki z okolico, Gubałówka, parkirišča v Zakopanah, vrsta za žičnico na Kasprowy Wierch.",
    activity: "Kupovanje oscypkov, ciupag in puloverjev iz ovčje volne. Primerjanje cen s prejšnjim obiskom.",
    calls: ["Včasih je bil oscypek večji.", "Sem hodim od oseminšestdesetega."],
    enemies: "Zastoj na cesti v Zakopane, cena oscypka, parkirišče za petdeset zlotov.",
    fieldMarks: "Tretja ciupaga v zbirki. Pulover iz ovčje volne, ki ga v avtu nosi tudi poleti.",
    traits: [
      { label: "Zbirka ciupag" },
      { label: "Primerjanje cen oscypka" },
      { label: "Potrpežljivost v zastoju pred Zakopanami" },
    ],
    symptoms: [
      "Pravi, da je bil oscypek včasih večji.",
      "Doma ima vsaj tri ciupage.",
      "V Zakopane prihaja od leta 1968.",
      "Stoji v zastoju na cesti v Zakopane in se pritožuje nad zastojem na cesti v Zakopane.",
      "Ceno parkirišča primerja s ceno prenočišča izpred let.",
      "Julija v avtu nosi pulover iz ovčje volne.",
      "Vsako leto se na Krupówkih fotografira z medvedkom.",
    ],
    handling: [
      "Ne spraševati o ceni oscypka. Povedal bo.",
      "Ne predlagati izleta v Tatre ob podaljšanem vikendu.",
      "Sprejeti ciupago v dar. Še eno.",
    ],
    notes: [
      "¹ Oscypek: prekajeni ovčji sir v obliki vretena z vtisnjenim vzorcem. Najbližji sorodnik na Slovenskem je trnič z Velike planine.",
      "² Ciupaga: goralska pohodna palica z ročajem v obliki sekirice, danes predvsem spominek.",
      "³ Krupówki: glavna sprehajalna ulica v Zakopanah, od enega konca do drugega stojnice, gostilne in spominki.",
    ],
  },
  bieszczadzki: {
    name: "Bieszczadski dziaders",
    genitive: "Bieszczadskega dziadersa",
    statusNote: "Populacija raste po zaslugi osebkov, ki so pustili vse.",
    teaser: "Že 30 let namerava pustiti vse in oditi v Bieszczade. Živi v Bieszczadih.",
    summary: "Podkarpatska vrsta. Že trideset let namerava pustiti vse in oditi v Bieszczade, v katerih živi.",
    description: [
      "Bieszczadski dziaders že trideset let namerava pustiti vse in oditi v Bieszczade¹. Ima spakiran nahrbtnik, puščeno brado in izdelan načrt. Edina ovira je, da v Bieszczadih že živi, kar zaplete logistiko odhoda.",
      "Vrsta se v razpršeni obliki pojavlja tudi po vsej državi: kot osebki, ki v lokalih, na svatbah in v službi izjavljajo, da bodo »pustili vse in odšli v Bieszczade«. Po ocenah Inštituta to stori manj kot odstotek populacije. Preostali ostanejo, nahrbtnik pa imajo.",
    ],
    habitat: "Bieszczady, polonine, okolica Wetline in Cisne. Tudi v načrtih prebivalcev vse Poljske.",
    activity: "Načrtovanje, kako bo pustil vse. Pripovedovanje o tem v gostilni pod polonino.",
    calls: ["Vse bom pustil in odšel v Bieszczade.", "Tukaj je prava svoboda, gospod moj."],
    enemies: "Signal mobilnega omrežja, turisti iz velikih mest, sporočilo od šefa.",
    fieldMarks: "Brada, puščena v okviru priprav. Nahrbtnik, spakiran od leta 1993.",
    traits: [{ label: "Pripravljenost pustiti vse" }, { label: "Dejanska opustitev česar koli" }, { label: "Navdušenje nad poloninami" }],
    symptoms: [
      "Že trideset let pravi, da bo pustil vse in odšel v Bieszczade.",
      "V predsobi ima spakiran nahrbtnik.",
      "V okviru priprav si pušča brado.",
      "Ve, kje na polonini ni signala, in to zelo hvali.",
      "Kadar govori o svobodi, reče »gospod moj«.",
      "V službi gleda fotografije polonin.",
      "Živi v Bieszczadih in še vedno načrtuje odhod vanje.",
    ],
    handling: [
      "Ne spraševati, kdaj bo končno odšel.",
      "Navdušiti se nad poloninami.",
      "Po štirih popoldne mu ne pisati. V duhu je že v Bieszczadih.",
    ],
    notes: [
      "¹ Bieszczady: redko poseljeno gorovje na jugovzhodu Poljske, s travnatimi slemeni, ki jim pravijo polonine. »Pustiti vse in oditi v Bieszczade« je na Poljskem ustaljen izraz za beg pred civilizacijo.",
    ],
  },
  weselny: {
    name: "Svatbeni dziaders",
    genitive: "Svatbenega dziadersa",
    statusNote: "Populacija stabilna. Na vsaki svatbi je navzoč vsaj en osebek.",
    teaser: "Kravata na čelu. Govor, za katerega ni nihče prosil.",
    summary:
      "Priložnostna vrsta, povezana s svatbami. Ocenjuje ansambel, ugiba vsebino kuvert, po polnoči pa kravato prestavi z vratu na čelo.",
    description: [
      "Svatbeni dziaders pride v dvorano v obleki s svoje poroke iz leta 1986 in takoj zasede mesto s pogledom na ansambel. Do polnoči ohranja resnost. Oceni govejo juho, preračuna ceno pogrinjka in prvi zakliče »gorzko«¹, navadno še preden mladoporočenca utegneta sesti.",
      "Po polnoči sledi preobrazba. Kravata se preseli z vratu na čelo, suknjič na naslonjalo stola, osebek pa ansambel zaprosi za mikrofon, da bi povedal »samo dve besedi«. Govor traja četrt ure in se večinoma nanaša na njegovo lastno poroko. Drugi dan svatbe z družino pretrese vsebino kuvert in navaja zneske na petdeset zlotov natančno, čeprav ni odprl nobene.",
    ],
    habitat: "Banketne dvorane, gostišča in gasilski domovi po vsej Poljski. Vedno za mizo s pogledom na ansambel.",
    activity: "Ocenjevanje ansambla. Govorniški nastopi. Ugibanje vsebine kuvert.",
    calls: ["Jaz bi samo dve besedi.", "Klaviaturist je dober, ostale bi zamenjal."],
    enemies: "DJ namesto ansambla, svatba brez polnočnih iger, povezovalec, ki ne da mikrofona iz rok.",
    fieldMarks: "Kravata na čelu, še vedno zavezana z windsorskim vozlom. Suknjič na naslonjalu stola.",
    traits: [
      { label: "Pripravljenost na govor" },
      { label: "Natančnost ocenjevanja kuvert" },
      { label: "Ohranjanje kravate na vratu po polnoči" },
    ],
    symptoms: [
      "Pride v obleki s svoje poroke.",
      "Zakliče »gorzko«, še preden mladoporočenca sedeta za mizo.",
      "Ansambel oceni po prvi skladbi. Klaviaturista posebej.",
      "Po polnoči si kravato zaveže okrog čela.",
      "Mikrofon zahteva za »samo dve besedi«. Govori petnajst minut.",
      "Pozna zneske v kuvertah, čeprav ni odprl nobene.",
      "Meni, da se je treba poročiti v mesecu s črko »r«.",
    ],
    handling: [
      "Ne podajati mu mikrofona. Vzel ga bo sam.",
      "Ne spraševati, koliko je dal v kuverto. Povedal bo, koliko so dali vsi drugi.",
      "Hvaliti kravato, ne glede na njen položaj.",
    ],
    occasion: "na svatbah",
    notes: ["¹ Gorzko (»grenko«): vzklik poljskih svatov, ob katerem se morata mladoporočenca poljubiti, da se vodka spet osladi."],
  },
  wigilijny: {
    name: "Svetovečerni dziaders",
    genitive: "Svetovečernega dziadersa",
    statusNote: "Pojavi se enkrat na leto, zato pa v skoraj vsakem domu.",
    teaser: "Prešteje jedi. Dobi enajst.",
    summary:
      "Priložnostna vrsta, dejavna en večer na leto. Prešteva jedi, pripoveduje o krapu v kadi in ob božičnih pesmih zaspi pred televizorjem.",
    description: [
      "Svetovečerni dziaders se razkrije na sveti večer¹, 24. decembra, približno takrat, ko nekdo pri oknu razglasi prvo zvezdo. Preden sede za mizo, prešteje jedi. Navadno jih našteje enajst: boršč z ušesci šteje kot eno jed, kompota iz suhega sadja pa ne priznava za jed. Če bi jih naštel dvanajst, bi štel še enkrat, po drugi metodi.",
      "Pri ribi preide na spominski del. Vsako leto z enakimi besedami pripoveduje o krapu, ki je tri dni plaval v kadi², tako da se nihče v hiši ni mogel okopati. Nato pojasni, kako je treba krapa razrezati na kolute, čeprav je to sam nazadnje počel leta 1998. Po večerji zasede naslanjač pred televizorjem in ob božičnih pesmih zaspi. Zbudi se za makovo potico in izjavi, da ni spal.",
    ],
    habitat:
      "Mesto za svetovečerno mizo najbliže pladnju s krapom, nato naslanjač pred televizorjem. Vsa Poljska, izključno 24. decembra.",
    activity: "Štetje jedi. Pripovedovanje o krapu v kadi. Dremež ob božičnih pesmih.",
    calls: ["Sem preštel. Enajst jih je.", "Saj ne spim, božične pesmi poslušam."],
    enemies: "Krap v filejih, boršč iz tetrapaka, predlog, da bi letos naročili catering.",
    fieldMarks: "Pulover z jelenčki čez praznično srajco, zapeto do vratu. Po večerji: naslanjač in oči, zaprte »samo za hip«.",
    traits: [{ label: "Glasno štetje jedi" }, { label: "Ponavljanje zgodbe o krapu" }, { label: "Budnost po večerji" }],
    symptoms: [
      "Prešteje jedi na mizi in na vsako pokaže z vilicami.",
      "Vsako leto pripoveduje o krapu, ki je plaval v kadi. Z enakimi besedami.",
      "Pojasnjuje, kako je treba krapa razrezati na kolute. Nad razrezanim krapom.",
      "Boršč oceni z eno besedo: »drugačen«.",
      "Darilo odvije tako, da bo papir uporaben še prihodnje leto.",
      "Ob božičnih pesmih zaspi pred televizorjem.",
      "Zbudi se za makovo potico in trdi, da ni spal.",
    ],
    handling: [
      "Ne prekinjati zgodbe o krapu v kadi. Vsi poznajo konec, a tradicija je tradicija.",
      "Pokazati mu dvanajsto jed. Najpogosteje je to kompot iz suhega sadja.",
      "Ne buditi ga ob božičnih pesmih.",
    ],
    occasion: "na sveti večer",
    notes: [
      "¹ Sveti večer: na Poljskem slovesna večerja (wigilia) z dvanajstimi postnimi jedmi, ki se začne, ko na nebu zasije prva zvezda. Slovenski bralec ta večer kropi in kadi po hiši.",
      "² Krap v kadi: krapa za sveti večer na Poljskem kupijo živega in ga do večerje hranijo v kopalni kadi.",
    ],
  },
  parapetowy: {
    name: "Okenski dziaders",
    genitive: "Okenskega dziadersa",
    statusNote: "Izpodriva ga videonadzor v soseski, ki vidi manj, zato pa snema.",
    teaser: "Ve, kdo se je vrnil ob 2.40. In s čim.",
    summary:
      "Priložnostna vrsta, opazovana izključno na oknu. Komolce naslanja na blazino in o dvorišču ve več kot upravnik.",
    description: [
      "Okenski dziaders zasede položaj na oknu, ki gleda na dvorišče, najraje v prvem ali drugem nadstropju, od koder ima najboljši pogled na parkirišče, smetnjake in vhod v stopnišče. Komolce naslanja na blazino, namenjeno izključno temu. Blazina je starejša od večine avtomobilov na parkirišču in precej bolje vzdrževana.",
      "Vrsta vodi neprekinjeno evidenco. Ve, kdo je parkiral na zelenici, kdo se je vrnil ob 2.40 in ali se je pripeljal s taksijem. Posebej oživi ob pogledu na kurirja: zabeleži velikost paketa in številko vhoda, kamor so ga odnesli, ter preveri, ali je kurir sploh pozvonil, preden je pustil obvestilo. Selitve spremlja od prve škatle do zadnje in nove stanovalce oceni po pohištvu.",
    ],
    habitat: "Okna, obrnjena na dvorišče, v blokih iz betonskih plošč in starih meščanskih hišah. Najraje prvo in drugo nadstropje.",
    activity: "Opazovanje parkirišča in smetnjakov. Beleženje ur vrnitev. Ocenjevanje selitev.",
    calls: ["Tisti iz štirice je spet parkiral na travi.", "Kurir je bil, pa ni pozvonil. Sem videl."],
    enemies: "Drevo, ki ga je upravnik posadil pod oknom, zunanje rolete, sosed, ki parkira za vogalom.",
    fieldMarks: "Blazina na okenski polici, komolci na blazini. Zavesa, odmaknjena za širino glave.",
    traits: [
      { label: "Poznavanje ur, ob katerih se vračajo sosedje" },
      { label: "Vedenje o tujih pošiljkah" },
      { label: "Pripravljenost umakniti se od okna" },
    ],
    symptoms: [
      "Na okenski polici ima blazino, namenjeno izključno naslanjanju komolcev.",
      "Ve, kdaj se vračajo vsi sosedje, na pet minut natančno.",
      "Vsebino tujih paketov ugiba po njihovi velikosti.",
      "Nove stanovalce oceni po pohištvu, ki ga ob selitvi nosijo v stanovanje.",
      "Ko se kaj dogaja zunaj dosega okna, se preseli v kuhinjo. Tam ima drugo okno.",
      "Pozimi opazuje skozi zaprto okno in z rokavom briše šipo.",
      "Na vprašanje »Kaj je novega?« poroča, kaj je novega pri sosedih.",
    ],
    handling: [
      "Ob vrnitvi po polnoči ne računati na to, da ni nihče videl.",
      "Vprašati ga, ali je bil kurir. Ve bolje kot aplikacija.",
      "Ob selitvi mu pomahati. Ocena pohištva bo milejša.",
    ],
    occasion: "na oknu",
  },
  kolejkowy: {
    name: "Čakalni dziaders",
    genitive: "Čakalnega dziadersa",
    statusNote: "Ogrožajo ga avtomati s številkami. Številko sicer vzame, ljudi pred sabo pa vseeno prešteje.",
    teaser: "Šteje ljudi pred sabo. Vsakih pet minut, na glas.",
    summary:
      "Priložnostna vrsta, ki se pojavlja v čakalnih vrstah na pošti, v banki in pri pultu z narezki. Šteje ljudi pred sabo in komentira hitrost postrežbe.",
    description: [
      "Čakalni dziaders poseljuje čakalne vrste na pošti, v banki, pri pultu z narezki in na sobotni tržnici. Ob prihodu najprej prešteje ljudi pred sabo, nato to stori še enkrat, na glas, in rezultat sporoči osebi za sabo. Vsakih nekaj minut posodobi stanje in navede ocenjeni čas čakanja, vedno za polovico previsok. Ob tem komentira delovni tempo gospe za okencem in ugotavlja, da je od štirih okenc odprto eno.",
      "Osebek skrbi za red. Osebo, ki stopi do okenca z besedami »jaz bi samo nekaj vprašal«, ustavi s pripombo: »Vsi bi tukaj samo nekaj vprašali.« To formulo sam uporablja izključno v vrstah, v katerih je, kot trdi, položaj povsem drugačen. Ko pride na vrsto, odda tri pakete, plača dve položnici in povpraša po priložnostnih znamkah, ne da bi se ozrl na vrsto.",
    ],
    habitat:
      "Pošte, bančne poslovalnice, pulti z narezki, sobotne tržnice. Največ jih je tam, kjer je odprto eno samo okence.",
    activity: "Štetje ljudi pred sabo. Komentiranje hitrosti postrežbe. Varovanje vrstnega reda.",
    calls: ["Vsi bi tukaj samo nekaj vprašali.", "Štiri okenca, odprto pa eno."],
    enemies: "Avtomat s številkami, samopostrežna blagajna, oseba, ki je »tukaj stala že prej, samo za hip je stopila stran«.",
    fieldMarks: "Obvestilo o pošiljki v roki, dokumenti v plastični srajčki. Stoji tako blizu osebe pred sabo, da se nihče ne more vriniti.",
    traits: [{ label: "Štetje ljudi pred sabo" }, { label: "Budnost pred vrivalci" }, { label: "Hitrost urejanja lastnih zadev" }],
    symptoms: [
      "Prešteje ljudi pred sabo. Nato še enkrat, na glas.",
      "Vsakih pet minut osebi za sabo sporoči, koliko časa bosta še stala.",
      "Ugotovi, da je od štirih okenc odprto eno, in vpraša, čemu so preostala tri.",
      "Na »jaz bi samo nekaj vprašal« odgovori »vsi bi tukaj samo nekaj vprašali«.",
      "Pri okencu uredi pet zadev in povpraša po šesti.",
      "Prosi za deset dek šunke, »čisto na tanko«, in rezine pogleda proti svetlobi.",
      "Na tržnici se postavi v najdaljšo vrsto, ker »tam mora biti dobro«.",
    ],
    handling: [
      "Ne stopati do okenca z besedami »jaz bi samo nekaj vprašal«.",
      "Ne držati mesta v vrsti in nato oditi. To si bo zapomnil.",
      "V primeru dvoma ga vprašati, kdo je zadnji. Ve.",
    ],
    occasion: "v čakalnih vrstah",
  },
  kibicowski: {
    name: "Navijaški dziaders",
    genitive: "Navijaškega dziadersa",
    statusNote: "Številčnost vsaki dve leti, junija, skokovito naraste.",
    teaser: "S kavča vidi bolje od sodnika. In bolje od trenerja.",
    summary:
      "Priložnostna vrsta, dejavna med prenosi tekem. S kavča ocenjuje sodnika, odpušča trenerja in ve, kako bi bilo treba streljati.",
    description: [
      "Navijaški dziaders zasede kavč četrt ure pred prvim žvižgom in ga ne zapusti do konca analize po tekmi. Tekmo gleda sklonjen naprej, s komolci na kolenih, pripravljen, da vsak hip vstane in pokaže, kako bi bilo treba centrirati. Vsako zapravljeno priložnost pospremi z besedami »to bi jaz zabil«, ne glede na oddaljenost od gola in kot.",
      "Razpolaga s popolnim sodniškim in trenerskim znanjem. Prepovedani položaj vidi brez ponovnega posnetka, trenerja med tekmo odpusti povprečno dvakrat in ga po zmagi brez pojasnila vrne na delovno mesto. Merilo mu ostajata reprezentanci s svetovnih prvenstev 1974 in 1982¹, njuni postavi pa recitira na pamet, najraje med polčasom, ko prekričuje oglase.",
    ],
    habitat: "Kavči in naslanjači pred televizorji po vsej Poljski. Med velikimi turnirji tudi navijaške cone.",
    activity: "Ocenjevanje sodnikov. Odpuščanje trenerja. Kazanje s kavča, kako bi bilo treba streljati.",
    calls: ["To bi jaz zabil.", "Trenerja bi jaz zamenjal že ob polčasu."],
    enemies: "Sistem VAR, oglasi med polčasom, komentator, ki hvali nasprotnika.",
    fieldMarks: "Šal okrog vratu, tudi julija. Sklonjen naprej, komolci na kolenih, daljinec v stisnjeni pesti.",
    traits: [
      { label: "Gotovost pri presoji prepovedanega položaja" },
      { label: "Poznavanje postave iz leta 1974" },
      { label: "Zaupanje v sodnika" },
    ],
    symptoms: [
      "Pravi »to bi jaz zabil«, tudi pri prostih strelih s štiridesetih metrov.",
      "Prepovedani položaj vidi hitreje od stranskega sodnika.",
      "Trenerja med tekmo odpusti dvakrat.",
      "Sodnika nagovarja neposredno, skozi televizor.",
      "Recitira postave s svetovnih prvenstev 1974 in 1982. Z rezervisti vred.",
      "Vstane s kavča, da pokaže, kako bi bilo treba centrirati.",
      "Po izgubljeni tekmi razglasi, da ne bo več gledal. Gleda naslednjo.",
    ],
    handling: [
      "Med akcijo ne hoditi pred televizorjem.",
      "Ne spraševati, kdo zmaguje. Vprašati, kdo bi moral.",
      "Po tekmi ne omenjati enajstmetrovk.",
    ],
    occasion: "ob prenosih tekem",
    notes: [
      "¹ Svetovni prvenstvi 1974 in 1982: na obeh je poljska reprezentanca osvojila tretje mesto. Slovenski bralec ima za to evropsko prvenstvo leta 2000.",
    ],
  },
  kempingowy: {
    name: "Kamperski dziaders",
    genitive: "Kamperskega dziadersa",
    statusNote: "Kampi ob morju se umikajo apartmajskim blokom.",
    teaser: "Prikolico nivelira že eno uro. Še ne.",
    summary:
      "Priložnostna vrsta, ki jo od maja do septembra srečamo v kampih. Eno uro nivelira prikolico, nato pa dva tedna sedi pred njo na zložljivem stolu.",
    description: [
      "Kamperski dziaders pride v kamp s prikolico, ki jo za avtomobilom vleče od leta 1988. Najpogosteje je to klasična prikolica Niewiadów¹, ki jo vsako zimo obnavlja v garaži. Postavitev tabora traja vse popoldne, največ časa pa vzame niveliranje. Libelo položi na tla prikolice, pod kolesa podloži deske in klade, preveri, prestavi in znova preveri. Mehurček mora stati natanko na sredini. Medtem družina utegne izprazniti avto, pojesti sendviče in se vrniti z jezera.",
      "Po niveliranju postavi predšotor, mizico in zložljivi stol, na katerem preživi preostanek dopusta. Kosilo kuha na dvoplamenskem plinskem kuhalniku, vsako novo prispelo prikolico pa oceni med vzvratno vožnjo, najprej molče, nato na glas. Upravnika kampa pozna po imenu, stalne goste pa po številkah parcel.",
    ],
    habitat: "Kampi ob jezerih Mazurije in Kašubije ter ob morju. Vedno ista parcela, zasedena od leta 1993.",
    activity: "Niveliranje prikolice. Postavljanje predšotora. Ocenjevanje, kako drugi vzvratno vozijo s prikolico.",
    calls: ["Še ne. Mehurček uhaja v levo.", "Volan na drugo stran, gospod."],
    enemies: "Poševna parcela, apartmajski blok s pogledom na morje, avtodom s samodejnim niveliranjem.",
    fieldMarks: "Libela v žepu. Zložljivi stol pod predšotorom, obrnjen proti poti med parcelami.",
    traits: [
      { label: "Natančnost niveliranja" },
      { label: "Ocenjevanje tuje vzvratne vožnje s prikolico" },
      { label: "Spoštovanje do avtodomov" },
    ],
    symptoms: [
      "Prikolico nivelira eno uro. Mehurček mora stati natanko na sredini.",
      "V prtljažniku vozi komplet klad za podlaganje pod kolesa.",
      "Postavi predšotor, tudi če ostane le eno noč.",
      "Dopust preživi na zložljivem stolu, obrnjen proti poti.",
      "Kuha na plinskem kuhalniku, tudi če je v kampu bife.",
      "Pri vzvratni vožnji svetuje vsakomur, ki pride s prikolico. S kretnjami in na glas.",
      "Stalne goste pozna po številkah parcel.",
    ],
    handling: [
      "Med niveliranjem ne stopati na stopnico prikolice.",
      "Pri vzvratni vožnji s prikolico ne gledati proti njemu.",
      "Ne trditi, da prikolica tako ali tako stoji ravno.",
    ],
    occasion: "v kampih",
    notes: [
      "¹ Niewiadów: poljska tovarna, katere majhne počitniške prikolice so desetletja vozile za poljskimi avtomobili. Slovenska ustreznica je Adria.",
    ],
  },
};
