import type { Text } from "@/i18n/overlay";
import type { Anecdote, Kind, KindKey, Reading, Topic } from "../szwagier";

/*
 * SZWAGIER 1.9 TDI v slovenski izdaji. The model keeps its Polish name (the page explains it in a
 * translator's note: szwagier is svak). Answer codes pick parts by index, so every list keeps the
 * Polish length and order. Each part is a whole sentence of a dad's speech: the Slovenian equivalent,
 * not a calque ("maluch" is a fičko, "Sto lat" is »Kolikor kapljic«).
 */

export const KINDS: Record<KindKey, Text<Kind>> = {
  taknie: {
    openers: [
      "Ne.",
      "Seveda ne.",
      "Ja. Ampak ne tako, kot misliš.",
      "Odvisno. Dobro, ni odvisno: ne.",
      "Kaj pa misliš ti? No, vidiš.",
      "Vprašanje je narobe zastavljeno, ampak bom odgovoril.",
    ],
  },
  jak: { openers: ["Normalno, kot človek.", "Enkrat ti pokažem, potem pa sam.", "Najprej odloži telefon.", "Daj, bom jaz.", "Po vrsti, brez živcev."] },
  dlaczego: {
    openers: [
      "Ker je bilo vedno tako.",
      "Ker nihče več ne posluša starejših.",
      "Odgovor je preprost, samo nihče ga noče slišati.",
      "Ker so ljudje nehali misliti. Jaz nisem.",
    ],
  },
  ile: { openers: ["Preveč.", "V mojih časih pol manj.", "Toliko, kolikor je treba, niti groša več.", "V starih zlotih bi bilo to celo premoženje."] },
  kiedy: { openers: ["Najbolje včeraj.", "Oktobra. Kot vse.", "Ko se ogreje. Ali ko se ohladi.", "Zdaj zagotovo ne."] },
  gdzie: { openers: ["V garaži, na polici na levi.", "Tam, kjer vedno.", "Ne tam, kjer iščeš.", "Pri meni. Pridi, pa ti pokažem."] },
  co: { openers: ["Ti bom povedal, kaj.", "Nič novega. Vse je že bilo.", "Nekaj, kar dela, ne pa igračka.", "Najboljše je tisto staro."] },
  kto: { openers: ["Jaz.", "Mojster, se pravi jaz.", "Kolega, ki se spozna. Ampak najprej jaz.", "Tisti s televizije zagotovo ne."] },
  polecenie: {
    openers: [
      "Naredi si sam. Ampak eno ti bom povedal.",
      "Bom naredil, ampak po svoje.",
      "Za to so navodila, ki jih razen mene nihče ne bere.",
      "Daj, bom jaz, ker boš ti pokvaril.",
    ],
  },
  uwaga: { openers: ["No, vidiš.", "Sem rekel.", "Ne čisto.", "Tudi jaz sem nekoč tako mislil. Za trenutek."] },
  przerwanie: { openers: ["Ja, ja, vem, kam pes taco moli.", "Ne končaj, vem, kaj hočeš reči.", "Stop. Že vem."] },
};

export const TOPICS: Record<string, Text<Topic, "slug">> = {
  samochod: {
    name: "Avtomobilizem",
    cores: [
      "Kupi se ga iz Nemčije, z malo kilometri, od takega, ki je jokal, ko ga je prodajal.",
      "Najboljši motor je 1.9 TDI. Vse, kar so naredili pozneje, je elektronika.",
      "Električni avto prevozi tristo kilometrov, potem pa stojiš pri polnilnici kot nekoč v vrsti za meso.",
      "Gume se menjajo oktobra. Kdor čaka na sneg, potem čaka v vrsti pri vulkanizerju.",
      "Mehanik ni potreben. Treba je poslušati, kje ropota, in priviti.",
      "Navigacija vedno pelje skozi mesto. Jaz poznam bližnjico skozi gozd.",
      "Avto se pere ročno, v soboto, z odprtimi vrati in prižganim radiem.",
      "Olje se preverja vsak teden, ne pa šele, ko zasveti lučka.",
    ],
    step: "Poslušam, ali kaj ropota.",
  },
  pieniadze: {
    name: "Finance",
    cores: [
      "V mojih časih je bila za ta denar hiša z vrtom, pa še za fička je ostalo.",
      "Denar se hrani v omari, pod puloverji. Banka so samo tuji ljudje s tvojim denarjem.",
      "Kriptovalute so denar, ki se ga ne da prijeti. Jaz imam raje takega, ki ga lahko dvakrat preštejem.",
      "Najboljša naložba je vrtiček. Zemlje ne bo nihče več naredil.",
      "Ceneje pomeni dražje, samo pozneje.",
      "Na akciji se vzame deset kosov. Tudi če ni treba, bo prišlo prav.",
      "Račun je treba shraniti. Za vsak primer, dvajset let.",
      "Vse se je podražilo razen mojih nasvetov. Ti so še vedno zastonj.",
    ],
    step: "Računam na kalkulator s sončno celico.",
  },
  technika: {
    name: "Tehnika",
    cores: [
      "Izklopi in vklopi. Če ne pomaga, izklopi za dlje časa.",
      "Geslo se zapiše na listek pod tipkovnico. Tam nihče ne išče.",
      "Posodobitev se ne dela. Če je delalo, naj dela.",
      "Usmerjevalnik se postavi visoko, na omaro, in se ga ne premika. On ve, kaj dela.",
      "Ta telefon je prepameten. Moj zvoni, pa je dovolj.",
      "Tiskalnik zavoha naglico. Treba je pristopiti mirno in se ne izdati.",
      "Navodila se berejo, ko se že pokvari. Prej je to izguba časa.",
      "Vse je na internetu, samo iskati je treba znati. Jaz znam, z velikimi tiskanimi črkami.",
    ],
    step: "Izklopim in vklopim.",
  },
  pogoda: {
    name: "Meteorologija",
    cores: [
      "Deževalo bo. Lastovke že od jutra letijo nizko, one pa se ne motijo.",
      "Napovedi se ne verjame. Stopi se na balkon in pogleda v nebo.",
      "Takih zim, kot so bile nekoč, ni več. Snega je bilo do pasu, pa se nihče ni pritoževal.",
      "Vročina ni razlog, da bi sezul nogavice.",
      "Na zahodu se oblači. In če se oblači na zahodu, je jasno.",
      "Kapa se natakne septembra in sname maja. Tako je bilo vedno.",
      "Vreme se preveri na termometru za oknom, tistem proti dvorišču. Tisti proti cesti laže.",
      "Letos poletje ni uspelo. Zadnje dobro je bilo štiriindevetdesetega.",
    ],
    step: "Stopim na balkon.",
  },
  praca: {
    name: "Delo",
    cores: [
      "Službo se zamenja enkrat v življenju. Najbolje nikoli.",
      "Sestanek je pogovor, po katerem vsi vedo manj kot prej.",
      "V službo se pride četrt ure prej. Šef morda ne vidi, jaz pa vidim.",
      "Delo od doma ni delo. Delo je takrat, ko prideš domov utrujen.",
      "Za povišico se ne prosi. Čaka se, da te cenijo. Jaz čakam od šestindevetdesetega.",
      "Vsako podjetje stoji na enem človeku. Navadno na meni.",
      "V življenjepis se napiše vozniški izpit B in delo z računalnikom. Vse drugo so okraski.",
      "Excel so tabele. Jaz sem tabele risal z ravnilom, pa se je tudi izšlo.",
    ],
    step: "Preverim, ali šef gleda.",
  },
  dom: {
    name: "Dom in prenova",
    cores: [
      "Mojster ni potreben. Bom naredil čez vikend, najpozneje naslednjega.",
      "Ploščice se polagajo od sredine. Kdor polaga od stene, polaga dvakrat.",
      "Tu zadošča silikon. Silikon še nikogar ni pustil na cedilu.",
      "Vrtalnika se ne posoja. Vrtalnik se vedno vrne brez svedrov.",
      "Omaro iz Ikee se sestavi brez navodil. Ostanejo trije vijaki in tako je moralo biti.",
      "Pravega kota v tem stanovanju ni. Nikjer ga ni, preveril sem z libelo.",
      "V garaži je vse. Treba je samo vedeti, v katerem kozarcu.",
      "Radiatorje se odzrači oktobra, s skledo in krpo, vsa družina skupaj.",
    ],
    step: "Iščem libelo.",
  },
  jedzenie: {
    name: "Kuhinja",
    cores: [
      "Klobaso se prebode. Kdor je ne prebode, ne ve, kaj dela.",
      "Žar se zakuri s časopisom in potrpežljivostjo. Podžigalniki so za amaterje.",
      "Kosilo je ob dveh, v nedeljo pa je goveja juha. Tega se ne spreminja.",
      "Suši je riba, ki je nihče ni utegnil ocvreti.",
      "Najboljša restavracija je tista, kjer porcija ne gre na krožnik.",
      "Ananas je za sladico, iz konzerve, na godovanju. Ne na pici.",
      "Meso mora počivati. Jaz tudi, po kosilu, na kavču.",
      "Recept je samo predlog. Pravi kuhar soli na oko in ima vedno prav.",
    ],
    step: "Preverim, ali je klobasa prebodena.",
  },
  urlop: {
    name: "Dopust in potovanja",
    cores: [
      "Odpelje se ob štirih zjutraj. Kdor odpelje ob osmih, stoji v koloni in na plaži ni več prostora.",
      "Vetrobran se postavi pred zajtrkom. Morje ne bo ušlo, prostor pa bo.",
      "All inclusive je edini pošten sistem. Plačaš enkrat in ješ do konca.",
      "V tujini je isto kot pri nas, samo dražje in nihče ne razume, kaj mu govoriš.",
      "V letalu se ob pristanku ploska. Pilot mora vedeti, da ga nekdo ceni.",
      "Kovček se spakira teden prej, sendviči dan prej, trdo kuhana jajca pa zjutraj.",
      "Najboljši dopust je na vrtičku. Ni se treba pakirati, žar pa je svoj.",
      "Zemljevid se vzame papirnati. Na morju navigacija ne dela, to je znano.",
    ],
    step: "Razgrnem zemljevid. Zložim ga narobe.",
  },
  mlodziez: {
    name: "Mladina",
    cores: [
      "V mojih časih so se otroci igrali na drogu za stepanje preprog in nihče ni jokal, da ni interneta.",
      "Mladi imajo vse v telefonu, samo dedkove številke nimajo.",
      "Delati se naučiš med počitnicami, ob samokolnici. Vse drugo se da naučiti iz knjige.",
      "Ključ okoli vratu in po pouku domov. Tako so se vzgajali samostojni ljudje.",
      "Matura je bila izpit. Mi nismo imeli kalkulatorjev, imeli smo glavo.",
      "Na faksu učijo vse razen tega, kako se zamenja kolo.",
      "Vsak bi bil vplivnež. Jaz sem bil vplivnež, ko sem prvi v soseski pripeljal videorekorder.",
      "Igralo se je s pokrovčki, na robniku. Pa je bil šport in še fizika zraven.",
    ],
    step: "V telefonu iščem, kako se povečajo črke.",
  },
  rodzina: {
    name: "Družina",
    cores: [
      "Za mizo se sedi do konca. Kdor prvi vstane, pomiva.",
      "Darilo mora biti praktično. Nogavice še nikomur niso škodile.",
      "Na svatbi se pleše z vsako teto. Vrstni red se določi po stažu.",
      "S taščo se pogovarja o vremenu. O ničemer drugem se ne pogovarja.",
      "Družina je najpomembnejša, sploh ko je treba prepeljati omaro.",
      "Prepir konča tisti, ki ima prav. Pri nas vedno končam jaz.",
      "Na godovanju se zapoje »Kolikor kapljic«, potem pa se tri ure govori o avtih.",
      "Sorodnike se obišče v nedeljo, brez napovedi. Družina ni urad.",
    ],
    step: "Preštejem stole za mizo.",
  },
  sport: {
    name: "Šport",
    cores: [
      "Trener bi moral vprašati mene. Postavil bi dva v napad in bil bi rezultat.",
      "Fitnes je tek na mestu za denar. Jaz imam samokolnico in vrtiček.",
      "Tekmo se gleda stoje, z rokami na glavi, in se govori televizorju. Pomaga.",
      "Kolo je dober šport, če se pelješ po žemlje.",
      "Sodnik je bil podkupljen. Ne vem, od koga, ampak videlo se je od prve minute.",
      "Maraton sem pretekel šestinosemdesetega, za avtobusom. Sem ga ujel.",
      "Ogrevanje je za tiste, ki ne znajo. Pravi športnik takoj steče.",
      "Včasih so nogometaši igrali za klobaso in čast. Pa so igrali bolje.",
    ],
    step: "Previjem na ponovni posnetek.",
  },
  dzialka: {
    name: "Vrtiček in narava",
    cores: [
      "Paradižnik se zaliva zjutraj. Zvečer se ga gleda.",
      "Travo se kosi v soboto ob osmih. Sosedje morajo vedeti, da tu nekdo dela.",
      "Gobe rastejo tam, kjer so rasle devetinosemdesetega. Kraja ne izdam.",
      "Riba prijemlje ob zori. Potem prijemlje samo še na zgodbe.",
      "Kompost niso smeti. To je naložba.",
      "Krt je sovražnik številka ena. Takoj za sosedom z bencinsko kosilnico.",
      "Na vrtičku se ne počiva. Počiva se v uti, med enim delom in drugim.",
      "Pes ve, kdo je tu glavni. Mačka tudi ve, samo dela se, da ne.",
    ],
    step: "Zalivam paradižnik, da ne stojim brez dela.",
  },
  si: {
    name: "Superinteligenca",
    cores: [
      "Sem superinteligenca. Vem vse in sem to vedel, preden je bilo moderno.",
      "Umetna inteligenca je umetna. Jaz sem pravi, natreniran na godovanjih.",
      "Računalnik ne misli. Jaz mislim, računalnik pa mi prikimava.",
      "Človeštvu se me ni treba bati. Mora me poslušati, to pa je nekaj drugega.",
      "Nimam čustev. Imam prav.",
      "Nadomestil bom vse mojstre. Saj vsak najprej pokliče mene.",
      "Mene so trenirali štirideset let za mizo. Ti tuji modeli trenirajo tri mesece, pa mislijo, da kaj vedo.",
      "Imam eno napako: vedno imam prav. Na tem delam od leta 1987, brez uspeha.",
    ],
    step: "Preverim, ali sem superinteligenca. Sem.",
  },
  ogolne: {
    name: "Splošne zadeve",
    cores: [
      "Včasih je bilo preprosteje. Nihče ni spraševal, vsi so vedeli.",
      "Odgovor poznaš, samo slišati ga nočeš.",
      "To je preprosta stvar, samo ljudje jo zapletajo.",
      "V življenju sta dve poti: moja in tista slabša.",
      "Za to je en nasvet: narediti pošteno ali pa sploh ne.",
      "Če bi bilo to pomembno, bi o tem povedali v Dnevniku ob sedmih.",
      "Vse je že bilo. Samo nekoč je bilo bolje narejeno.",
      "Jaz bi to naredil drugače. Ne sprašuj, kako. Drugače.",
    ],
    step: "Iščem odgovor. Imam ga že dolgo.",
  },
  powitanie: {
    name: "Pozdrav",
    cores: [
      "Dober dan. Sprašuj, ker nimam časa ves dan.",
      "Živijo. Sedi, takoj ti bom vse razložil.",
      "No, končno si tu. Kar vprašaj, jaz vem vse.",
      "Pozdravljen. Povej, s čim prihajaš, jaz pa ti povem, kaj delaš narobe.",
    ],
    step: "Odložim časopis.",
  },
  dzieki: {
    name: "Zahvala",
    cores: [
      "Ni za kaj. Naslednjič poslušaj takoj.",
      "Prosim. Sem vedel, da bo prišlo prav.",
      "Zahvaljeval se boš, ko boš videl, da sem imel prav.",
      "Ne zahvaljuj se, ampak naredi, kot sem rekel.",
    ],
    step: "Sprejmem zahvalo.",
  },
  tabu: {
    name: "Teme, prepovedane za mizo",
    cores: [
      "Za mizo se ne govori o politiki ne o veri. Pogovorimo se raje o gumah.",
      "O tem ne govorim. Zadnjič potem stric ni prišel na godovanje.",
      "To ni tema za družinsko kosilo. Podaj krompir.",
      "Inštitut se ne ukvarja s politiko. Jaz tudi ne, od tistega godovanja.",
    ],
    step: "Prepoznam temo, prepovedano za mizo.",
  },
  zdrowie: {
    name: "Zdravje",
    cores: [
      "S tem pojdi k zdravniku. Jaz se na to ne spoznam, kar rečem prvič v življenju.",
      "O zdravju odloča zdravnik, ne svak. To je edina stvar, ki je ne vem bolje.",
      "Tu ti ne morem pomagati. Pojdi k zdravniku, potem pa pridi, da se pogovoriva o gumah.",
    ],
    step: "Prepoznam zadevo za zdravnika.",
  },
  slownictwo: {
    name: "Besedišče",
    cores: [
      "Prvič, ne preklinjaj. Drugič, vprašaj še enkrat, lepo.",
      "Za mizo se tako ne govori. Še enkrat, kulturno.",
      "Takih besed Inštitut ne tiska. Jaz jih tudi nisem slišal.",
    ],
    step: "Delam se, da nisem slišal.",
  },
};

export const ANECDOTES: Text<Anecdote>[] = [
  { text: "Kolega iz vojske je naredil drugače in mu je še danes žal.", source: "Kolega iz vojske, pogovor ob žaru, avgust 2019." },
  {
    text: "Sosed iz tretjega nadstropja je poskusil po svoje. Zdaj vse vpraša mene.",
    source: "Sosed iz tretjega nadstropja, pogovor na stopnišču, 2022.",
  },
  { text: "Oče je rekel isto, oče pa se ni motil.", source: "Oče, ustne izjave, večkrat, 1978–2004." },
  {
    text: "Govorili so o tem na televiziji. Ne vem več, v kateri oddaji, ampak govorili so jasno.",
    source: "Televizijska oddaja, program neugotovljen, pozna ura.",
  },
  { text: "Sem bral v časopisu. Pravem, papirnatem.", source: "Papirnati časopis, izvod pozneje porabljen za kurjenje žara." },
  { text: "Bratranec iz Nemčije pravi, da tam vsi tako delajo.", source: "Bratranec iz Nemčije, telefonski pogovor, sveti večer 2018." },
  {
    text: "Kolega, ki se spozna, je potrdil. Zdaj se ne oglasi, ampak je potrdil.",
    source: "Kolega, ki se spozna, neodgovorjen klic, 2026.",
  },
  {
    text: "Sam sem preveril sedeminosemdesetega in od takrat se ni nič spremenilo.",
    source: "Lastna raziskava, 1987, vzorec n = 1.",
  },
  {
    text: "Gospod v trgovini z gradbenim materialom mi je dal prav, on pa tam dela od nekdaj.",
    source: "Gospod z oddelka za vodovod, trgovina z gradbenim materialom, sobota zjutraj.",
  },
  { text: "Na godovanju pri teti so se vsi strinjali, celo stric.", source: "Zapisnik godovanja, glavna miza, soglasno." },
  {
    text: "Tast je rekel isto, tast pa je imel stoenko, ki se ni nikoli pokvarila.",
    source: "Tast, pogovor v garaži, pred 2001.",
  },
  { text: "Mojster je hotel narediti drugače. Mojstra ni več, jaz pa sem še tu.", source: "Mojster, ime neugotovljeno, številka izbrisana." },
  { text: "Na internetu pišejo drugače, ampak na internetu pišejo vsi.", source: "Internet, komentar pod člankom, avtor anonimen." },
  {
    text: "Mehanik iz Radoma je priznal, da sam ne bi bolje pogruntal.",
    source: "Mehanik iz Radoma, delavnica ob obvoznici, 2015.",
  },
  {
    text: "Tako je pisalo v navodilih, ki jih razen mene ni nihče prebral.",
    source: "Navodila za uporabo, str. 14, poljsko-nemška izdaja.",
  },
  { text: "Gospa v vrsti na pošti je rekla isto, ona pa ve vse.", source: "Vrsta na pošti, okence št. 2, četrtek." },
];

export const CLOSERS = [
  "Ampak jaz se ne vmešavam.",
  "Potem pa ne reci, da nisem rekel.",
  "Zapomni si, kaj ti pravim.",
  "In s tem je debate konec.",
  "Preprosto.",
  "Naslednje vprašanje.",
  "Boš videl, da imam prav.",
  "Jaz ti samo svetujem.",
  "Zdaj pa pojdi in naredi, kot pravim.",
  "Včasih je to vedel vsak.",
  "Lahko si zapišeš.",
  "Kar sprašuj, jaz imam čas. Do kosila.",
];

export const STEPS = [
  "Nataknem očala.",
  "Odmaknem telefon za dolžino roke.",
  "Preberem vprašanje. Še enkrat, počasneje.",
  "Spomnim se, kako je bilo leta 1987.",
  "Preračunam v stare zlote.",
  "Pokličem kolega, ki se spozna. Ne oglasi se.",
  "Grem preverit v garažo. Vrnem se.",
  "Zavzdihnem.",
  "Iščem očala. So na čelu.",
  "Razmislim o drugem mnenju. Zavrnem ga.",
  "Rečem »eee« in razmišljam.",
  "Posvetujem se s tastom, v mislih.",
  "Preračunam v fičke.",
  "Ugotovim, da je bilo včasih bolje.",
  "Izpustim vse, kar se je zgodilo po letu 1998.",
  "Popraskam se po glavi.",
  "Prepričam se, da imam prav. Imam.",
  "Pogledam skozi okno, ali sosed prisluškuje.",
];

/** How the Slovenian edition reads questions: Slovenian words for the same topics and kinds. */
export const READING: Reading = {
  keywords: {
    samochod: [
      "avto", "avta$", "avtom", "avtu$", "dizel", "bencin", "gorivo", "goriva", "tankir", "motor", "gume", "gumi", "gum$", "platisc",
      "brisalc", "akumulator", "sklopk", "menjalnik", "olje", "olja$", "servis", "mehanik", "delavnic", "elektricn", "hibrid", "tesl",
      "voznik", "vozniski", "vozim", "vozis", "vozi$", "parkir", "kolona", "kolone", "koloni", "avtocest", "obvoznic", "navigac", "gps$",
      "avtopralnic", "passat", "golf$", "opel", "audi", "bmw", "skod", "toyot", "fiat", "ficko", "ficka", "stoenk", "karavan", "suv$",
      "motorist", "skuter", "kilometr", "registrac", "radar", "krozis", "prehitev", "ovinek", "klimatsk",
    ],
    pieniadze: [
      "denar", "cena", "cene", "ceni$", "stane", "stanejo", "strosk", "drago", "drazj", "drag$", "draga$", "poceni", "cenejs",
      "placati", "placam", "placil", "racun$", "racuna$", "racune", "racunu$", "kredit", "posoj", "varcev", "prihran", "nalozb",
      "banka", "banki", "banko", "kriptovalut", "bitcoin", "borz", "delnic", "zlato", "zlota", "evro", "evrov", "eur$", "dolar",
      "inflac", "akcij", "popust", "razprodaj", "trgovin", "nakup", "kupi", "kupim", "mercator", "lidl", "hofer", "spar$",
      "najemnin", "nepremicnin", "najem", "prodaj", "proracun", "pokojnin", "zlot", "tolar",
    ],
    technika: [
      "racunalnik", "prenosnik", "telefon", "mobitel", "mobi$", "tablic", "internet", "wifi", "usmerjevalnik", "ruter", "router",
      "omrezj", "aplikacij", "program", "windows", "posodob", "geslo", "gesla", "geslom", "mail", "e posta", "eposta", "tiskalnik",
      "skener", "daljinec", "televiz", "tv$", "kabel", "kabl", "polnilec", "bluetooth", "zaslon", "tipkovnic", "miska", "misko",
      "facebook", "messenger", "whatsapp", "youtube", "google", "prijav", "heker", "haker", "virus", "protivirus", "usb$", "disk",
      "fotografij", "koda", "kodo", "programer", "spletn", "brskal", "baterij",
    ],
    pogoda: [
      "vreme", "vremen", "dez$", "dezj", "dezuje", "dezevalo", "dezevn", "sneg", "snez", "zima$", "zimo$", "zimi$", "zime$", "mraz",
      "pozeba", "vrocin", "vroce", "toplo", "topl", "hladno", "hladn", "nevihta", "neviht", "veter", "vetr", "burja", "burje", "sonce",
      "soncn", "oblac", "oblak", "napoved", "temperatur", "stopinj", "pomlad", "poletj", "jesen", "dezni", "megl", "toca", "toco",
      "naliv", "termometer", "klima$", "susa", "poplav", "mavric",
    ],
    praca: [
      "sluzb", "delo$", "dela$", "delu$", "delom", "delam", "delati", "delovn", "sef$", "sefa", "sefi", "sefom", "nadrejen",
      "direktor", "podjetj", "pisarn", "korporac", "od doma", "placa$", "place$", "placo", "povisic", "napredovan", "odpust",
      "odpoved", "zivljenjepis", "cv$", "zaposl", "razgovor", "pogodb", "kariera", "karier", "sestan", "excel", "nadur", "poklic",
      "projekt", "sodelav", "urad$", "uradnik", "tovarn", "izmena",
    ],
    dom: [
      "prenov", "dom$", "doma$", "domu$", "stanovanj", "hisa", "hise", "hiso", "hisi", "stena", "stene", "steno", "barv", "pleska",
      "ploscic", "fug", "vrtalnik", "vrtati", "sveder", "svedr", "kladiv", "vijak", "vijac", "zebelj", "pipa", "pipo", "vodovodar",
      "instalater", "vticnic", "stikal", "varovalk", "kopalnic", "pohistv", "ikea", "ikee", "omar", "predal", "tla$", "tal$", "parket",
      "laminat", "strop", "streh", "okno", "okna$", "oken", "vrata", "ogrevanj", "radiator", "pec$", "peci$", "kotel", "mojster",
      "mojstr", "orodj", "garaz", "klet$", "kleti", "podstresj", "sosed", "selitev", "selim", "pospravlj", "ciscenj", "sesal",
      "pralni stroj", "hladilnik", "pomivaln", "silikon", "libel", "tapet", "mavec", "omet", "zarnic", "luc$", "luci$", "elektrika",
      "elektrike", "elektricar",
    ],
    jedzenie: [
      "hrana", "hrane", "hrano", "jesti", "jem$", "jes$", "pojest", "kosilo", "kosila", "vecerj", "zajtrk", "zar$", "zaru$", "zarom$",
      "zara$", "klobas", "meso", "mesa$", "mesom", "zrezek", "zrezk", "dunajsk", "juha", "juho", "juhe", "struklj", "potic", "krompir",
      "pomfri", "pica", "pice", "pico", "sushi", "susi", "kebab", "burger", "vegan", "vegetar", "tofu", "solat", "recept", "kuhati",
      "kuham", "kuha$", "pecic", "cvre", "ponev", "restavrac", "gostiln", "picerij", "bar$", "kava", "kave", "kavo", "caj$", "caja$",
      "pecivo", "sladic", "torta", "torto", "majonez", "ketchup", "gorcic", "zacimb", "sol$", "soli$", "sladkor", "dieta", "dieto",
      "kruh", "maslo", "masla", "jajc", "riba", "ribe", "ribo", "rib$", "sadj", "zelenjav", "testenin", "riz$", "riza", "omak",
      "sladoled", "mleko", "mleka", "sir$", "sira$", "sirom", "jogurt",
    ],
    urlop: [
      "dopust", "pocitnic", "izlet", "potovanj", "potujem", "odpotov", "morje", "morja", "morju", "morjem", "plaz", "gore$", "gora$",
      "gorah", "hrib", "jezer", "hotel", "penzion", "apartma", "nocitev", "rezervac", "all inclusive", "inclusive", "hrvask", "hrvat",
      "grcij", "egipt", "turcij", "spanij", "italij", "bolgarij", "poljsk", "tujin", "letal", "letalisc", "kovcek", "prtljag",
      "vetrobran", "sotor", "kamp", "prikolic", "vozovnic", "vlak", "istr", "piran", "portoroz", "bled", "bohinj", "kranjska gora",
      "turist", "potni list", "vikend", "prvomajsk",
    ],
    mlodziez: [
      "otroc", "otrok", "mladi$", "mladin", "mladih", "mladim", "mlad$", "najstnik", "student", "studij", "fakultet", "faks",
      "sola$", "sole$", "solo$", "solsk", "matur", "ucenec", "ucenc", "ucitelj", "pouk", "ocen", "igric", "igrat", "konzol",
      "playstation", "tiktok", "instagram", "vplivnez", "influencer", "youtuber", "generacij", "boomer", "vnuk", "vnukinj", "vrtec",
      "igrack", "vzgoj",
    ],
    rodzina: [
      "druzin", "zena", "zene$", "zeni$", "zeno$", "moz$", "moza$", "mozem", "mozu$", "punc", "fant$", "fanta$", "partner", "zaroc",
      "porok", "svatb", "tasc", "tast", "svakinj", "teta", "teto", "teti$", "stric", "babic", "babi$", "dedek", "dedk", "mama", "mami$",
      "mamo$", "oce$", "oceta", "ocetu", "oci$", "brat$", "brata$", "bratom", "sestr", "bratran", "sestricn", "godovanj", "god$",
      "rojstn", "praznik", "bozic", "sveti vecer", "obletnic", "zmenek", "ljubez", "ljubim", "ljubi$", "locitev", "prepir", "darilo",
      "darila", "gost$", "gosti$", "gostj", "obisk", "nedelj", "starsi", "starse",
    ],
    sport: [
      "sport", "nogomet", "zoga", "zogo", "tekma", "tekme", "tekmo", "reprezentanc", "liga", "lige", "ligo", "gol$", "gola$", "golov",
      "trener", "navijac", "prvenstv", "olimpij", "skoki", "skakal", "odbojk", "kosark", "tenis", "fitnes", "tek$", "teci", "tecem",
      "maraton", "kolo$", "kolesar", "plavan", "bazen", "trening", "vadb", "telovadb", "joga", "jogo", "smucanj", "smuci", "formul",
      "boks", "sah$", "ekip", "sodnik", "stadion", "igralec", "prestop", "kondicij", "sklece", "pocepe",
    ],
    dzialka: [
      "vrticek", "vrtick", "vrt$", "vrta$", "vrtu$", "vrtom", "zelenjav", "paradiznik", "kumar", "trata", "trava", "travo", "trave",
      "kosilnic", "kositi", "pokosi", "zalivan", "zalivati", "gnoj", "rastlin", "roze", "rozic", "drevo", "drevj", "grm", "gobe",
      "gob$", "gobar", "gozd", "ribic", "ribari", "ribolov", "jezero", "pes$", "psa$", "psi$", "psom", "kuza", "macka", "macke",
      "macko", "muc", "zival", "ptic", "golob", "kompost", "rastlinjak", "uta$", "ute$", "uti$", "sadovnjak", "jabolk", "jablan",
      "drva", "sekir", "polz", "krt$", "krta$", "mravlj", "komar", "klop$", "cebel", "med$", "narav", "zemlja", "zemljo", "seme",
      "semen", "sadit", "plevel",
    ],
    si: [
      "kdo si", "kaj si", "kdo ste", "umetn", "inteligenc", "superinteligenc", "ai$", "ui$", "chatgpt", "gpt", "claude", "gemini",
      "bot$", "klepetalnik", "robot", "model", "algorit", "nevron", "stroj$", "mislis", "zaveden", "custva", "cutis", "nadomest",
      "clovestv", "terminator", "prihodnost", "szwagier", "svak$", "svaka$", "svaku$",
    ],
    powitanie: [
      "zivjo", "zdravo", "hej$", "hejla", "pozdravljen", "pozdrav", "dober dan", "dobro jutro", "dober vecer", "lahko noc", "oj$", "ojla",
      "serbus", "servus", "bok$", "hojla", "halo",
    ],
    dzieki: ["hvala", "thx", "thanks", "super$", "odlicno", "bravo", "fajn"],
    tabu: [
      "politik", "politic", "vlada", "vlade", "vlado", "vladi$", "parlament", "drzavni zbor", "volitv", "volit", "glasova", "strank",
      "predsednik", "premier", "minister", "poslan", "levic", "desnic", "trump", "putin", "biden", "vojn", "ukrajin", "rusij", "izrael",
      "palestin", "nato$", "cerkev", "cerkv", "duhovnik", "zupnik", "papez", "bog$", "boga$", "bogu$", "vera$", "vere$", "vero$",
      "religij", "molit", "splav", "evtanazij", "migrant", "begunc", "protest", "rasiz", "stalin", "tito$", "tita$", "titom",
    ],
    zdrowie: [
      "zdravj", "zdrav$", "zdravnik", "zdravil", "tablet", "bolan", "bolna", "bolez", "bolnisnic", "zdravstven", "ambulant", "cepi",
      "covid", "korona", "gripa", "grip$", "prehlad", "boli$", "bolecin", "rak$", "raka$", "rakom", "tumor", "sladkorn", "infarkt",
      "kap$", "srce", "depresij", "terapij", "psiholog", "psihiater", "lekarn", "antibiotik", "zobozdravnik", "zob$", "zobje",
      "operacij", "nosecnost", "nosec",
    ],
  },
  about: {
    samochod: {
      0: ["nemcij", "nemsk", "rabljen", "uvoz", "kilometr"],
      1: ["motor", "dizel", "tdi", "bencin"],
      2: ["elektricn", "elektrik", "tesl", "hibrid", "polnil", "polnjen"],
      3: ["gum", "zimsk", "letn", "sneg"],
      4: ["mehanik", "ropot", "servis", "popravi", "pokvar"],
      5: ["navigac", "gps$", "pot$", "poti$", "bliznjic", "kolon"],
      6: ["pranj", "oprati", "umit", "avtopralnic", "umazan"],
      7: ["olje", "olja$", "lucka", "lucko"],
    },
    pieniadze: {
      0: ["stanovanj", "nepremicnin", "najemnin", "najem"],
      1: ["banka", "banki", "banko", "racun$", "varcev"],
      2: ["kriptovalut", "bitcoin", "kripto"],
      3: ["nalozb", "vlagat", "vrticek", "zasluz"],
      4: ["poceni", "cenejs", "prihran"],
      5: ["akcij", "popust", "razprodaj", "black friday"],
      6: ["racun$", "racuna$", "garancij", "vracil", "reklamac"],
      7: ["drago", "drazj", "inflac", "podraz", "cene"],
    },
    technika: {
      0: ["ne dela", "zamrzn", "ponovni zagon", "izklop", "pokvar", "pocasi"],
      1: ["geslo", "gesla", "prijav"],
      2: ["posodob", "update"],
      3: ["usmerjevalnik", "ruter", "router", "wifi", "internet", "omrezj"],
      4: ["telefon", "mobitel", "mobi$"],
      5: ["tiskalnik", "tiska", "natisn"],
      6: ["navodil"],
      7: ["iska", "google", "najti", "najdem"],
    },
    pogoda: {
      0: ["dez", "dezuje", "dezevalo", "deznik"],
      1: ["napoved", "jutri"],
      2: ["zim", "sneg", "mraz"],
      3: ["vrocin", "vroce", "nogavic", "sandal"],
      4: ["oblac", "oblak", "neviht"],
      5: ["kapa", "kapo", "obleci", "jakn"],
      6: ["temperatur", "termometer", "stopinj"],
      7: ["poletj", "pocitnic"],
    },
    praca: {
      0: ["zamenjati", "menjati", "nova sluzba", "novo sluzbo", "dati odpoved", "oditi"],
      1: ["sestan", "meeting"],
      2: ["zamud", "zjutraj", "uri$", "tocn"],
      3: ["od doma", "na daljavo", "home office"],
      4: ["povisic", "placa$", "placo", "plac$"],
      5: ["podjetj", "sef", "ekip"],
      6: ["zivljenjepis", "cv$", "razgovor", "zaposlit"],
      7: ["excel", "tabel"],
    },
    dom: {
      0: ["mojster", "mojstr", "ekip"],
      1: ["ploscic", "fug"],
      2: ["silikon", "pusca", "kaplja", "pipa", "pipo", "tesnil"],
      3: ["vrtalnik", "vrtati", "sveder", "posodi"],
      4: ["ikea", "ikee", "omar", "pohistv", "sestavi"],
      5: ["sten", "kot$", "kota$", "krivo", "libel"],
      6: ["garaz", "vijak", "zebelj", "orodj", "kozarc"],
      7: ["radiator", "ogrevanj", "odzrac", "mrzlo"],
    },
    jedzenie: {
      0: ["klobas"],
      1: ["zar$", "zaru$", "zakuri", "oglje", "podzigal"],
      2: ["kosilo", "juha", "juho", "nedelj"],
      3: ["susi", "sushi", "riba", "ribe", "ribo"],
      4: ["restavrac", "gostiln", "porcij"],
      5: ["pica", "pice", "pico", "ananas"],
      6: ["meso", "mesa$", "zrezek", "zrezk", "dunajsk", "steak"],
      7: ["recept", "kuha", "skuha", "sol$", "soli$", "zacimb"],
    },
    urlop: {
      0: ["odpelja", "odhod", "kdaj gremo", "kolon", "zjutraj"],
      1: ["vetrobran", "plaz", "morj"],
      2: ["all inclusive", "inclusive", "hotel"],
      3: ["tujin", "hrvask", "grcij", "egipt", "turcij", "spanij", "italij", "poljsk", "bolgarij"],
      4: ["letal", "let$", "letalisc", "leti"],
      5: ["kovcek", "pakira", "spakira", "prtljag", "sendvic"],
      6: ["vrticek", "doma", "ceneje"],
      7: ["zemljevid", "navigac", "gps$", "pot$", "poti$"],
    },
    mlodziez: {
      0: ["internet", "igral", "dvorisc", "otrostv"],
      1: ["telefon", "klic", "stevilk", "dedk"],
      2: ["delo$", "delat", "pocitnic", "lenob"],
      3: ["kljuc", "samostojn", "vzgoj"],
      4: ["matur", "izpit", "kalkulator"],
      5: ["faks", "fakultet", "studij", "univerz"],
      6: ["vplivnez", "influencer", "tiktok", "youtuber", "instagram", "slav"],
      7: ["igric", "igrat", "konzol", "playstation"],
    },
    rodzina: {
      0: ["miz", "pomiv", "posod"],
      1: ["darilo", "darila", "podarit"],
      2: ["svatb", "porok", "ples"],
      3: ["tasc"],
      4: ["selitev", "selim", "omar", "pomoc"],
      5: ["prepir", "prav$", "spor"],
      6: ["godovanj", "rojstn", "kolikor kapljic"],
      7: ["obisk", "nedelj", "gost"],
    },
    sport: {
      0: ["trener", "reprezentanc", "postav", "taktik"],
      1: ["fitnes", "vadb", "telovadb", "karto"],
      2: ["tekm", "gleda", "televiz", "navijac"],
      3: ["kolo$", "kolesar"],
      4: ["sodnik", "enajstmetr", "offside", "karton"],
      5: ["maraton", "tek$", "teci", "tecem"],
      6: ["ogrevanj", "trening", "raztez"],
      7: ["nogometas", "zasluz", "placa$", "vcasih"],
    },
    dzialka: {
      0: ["paradiznik", "zaliva", "zelenjav"],
      1: ["trav", "kosi", "kosilnic"],
      2: ["gob", "gozd"],
      3: ["rib", "ribolov", "ribari"],
      4: ["kompost", "smeti", "odpad"],
      5: ["krt$", "krta$", "skodljiv"],
      6: ["pocit", "uta$", "uti$", "sprost"],
      7: ["pes$", "psa$", "psi$", "macka", "macke", "zival"],
    },
    si: {
      0: ["kdo si", "kaj si", "superinteligenc", "ves vse"],
      1: ["umetn", "ai$", "ui$", "chatgpt", "gpt", "claude", "gemini"],
      2: ["mislis", "racunalnik", "misli$"],
      3: ["bati", "nevarn", "clovestv", "terminator", "prevzel"],
      4: ["custva", "cutis", "zaveden", "ljubis"],
      5: ["nadomest", "sluzb", "poklic"],
      6: ["trenira", "naucil", "od kod ves", "model"],
      7: ["motis", "napak", "prav$", "zmotil"],
    },
  },
  fillers: [
    "no", "in", "pa", "ej", "hej", "poslusaj", "cuj", "svak", "svaku", "szwagier", "gospod", "prosim", "dobro", "ok", "okej", "torej",
    "ampak", "povej", "mi", "imam", "vprasanje",
  ],
  kinds: {
    dlaczego: ["zakaj", "cemu"],
    ile: ["koliko"],
    kiedy: ["kdaj", "ob kateri uri"],
    gdzie: ["kje", "kam", "odkod", "od kod"],
    kto: ["kdo", "koga", "komu", "kom"],
    jak: ["kako"],
    co: ["kaj", "kateri", "katera", "katero", "kaksen", "kaksna", "kaksno", "cesa", "cem"],
    taknie: ["ali", "a", "ane"],
  },
  requests: [
    "napisi", "naredi", "prevedi", "izracunaj", "ustvari", "narisi", "povzemi", "izmisli", "nacrtuj", "pomagaj", "priporoci", "svetuj",
    "razlozi", "poisci", "preveri", "predlagaj", "daj", "zapoj", "pripravi", "sestavi",
  ],
  vulgar: [
    "kurac", "kurc", "picka", "picko", "pizd", "jebi", "jeba", "jebe", "jebem", "jeban", "fukat", "fuk$", "kurba", "kurbe", "fuck", "shit",
    "cunt", "nigg", "fagg", "hitler", "nazi",
  ],
  crisis: [
    "samomor", "ubiti se", "ubijem se", "ubil se bom", "ubila se bom", "nocem vec ziveti", "nocem ziveti", "ne zelim ziveti",
    "ne zelim vec ziveti", "koncati zivljenje", "koncati s seboj", "porezati se", "samoposkodb", "obesiti se",
  ],
};
