import type { Locale } from "@/i18n/config";
import { overlayList } from "@/i18n/overlay";
import * as sl from "./sl/bingo";

/*
 * Dziaders Bingo. A card is 24 squares drawn from the occasion's pool by a seed, around a free
 * centre. Changing a pool reshuffles every card of that occasion, so add squares in batches and
 * never between Friday and Monday: someone is playing at a wedding.
 * Keep squares under ~45 characters, they have to fit a fifth of a phone screen.
 */

export type Occasion = {
  /** URL segment and part of every card code. Never change it. */
  slug: string;
  name: string;
  /** "Bingo weselne". */
  title: string;
  /** Where and when to play, one line. */
  intro: string;
  /** Translator's notes (op. prev.), Slovenian edition only. */
  notes?: string[];
  squares: string[];
};

export const OCCASIONS: Occasion[] = [
  {
    slug: "wesele",
    name: "Wesele",
    title: "Bingo weselne",
    intro: "Od oczepin do poprawin. Najlepiej grać przy stole wujków, z dala od orkiestry.",
    squares: [
      "Wujek tańczy z krawatem na głowie",
      "„Gorzko!” jeszcze przed zupą",
      "„Na moim weselu to było trzy dni”",
      "„To nie jest muzyka”",
      "Głośny komentarz, ile kto dał w kopercie",
      "Marynarka zdjęta przed 21:00",
      "Wujek uczy kelnera nalewać",
      "„A kiedy dzieci?”",
      "Ciasto wynoszone w serwetce",
      "Pytanie, ile kosztowała sala",
      "Kłótnia o trasę dojazdu",
      "Ktoś nagrywa całe wesele w pionie",
      "Wujek tańczy sam. Z pasją.",
      "Przemówienie bez zaproszenia",
      "„Schabowy był lepszy w remizie”",
      "Prośba do DJ-a: ciszej. Potem: głośniej",
      "„Kaczuszki” tańczone na poważnie",
      "Zdjęcie grupowe trwa dwadzieścia minut",
      "Spór o miejsce przy stole",
      "Wujek sprawdza, czy rosół jest gorący",
      "„Ja tu tylko na chwilę”, godzina 4:00",
      "Trzecia wersja historii, jak się poznali",
      "Rozmowa telefoniczna na głośniku",
      "Pytanie, czy jest jeszcze bigos",
      "Buty zdjęte pod stołem",
      "Wujek tańczy z każdą ciocią po kolei",
      "„Ja bym to inaczej zorganizował”",
      "Sprawdzanie wyniku meczu pod stołem",
      "„Kiedyś grała orkiestra, nie DJ”",
      "Pierwszy taniec oceniony na głos",
      "Kwiaty ze stołu zabrane do domu",
      "Toast, który trwa dłużej niż ślub",
      "Krawat w kieszeni marynarki",
      "Kelner pytany, skąd jest rosół",
    ],
  },
  {
    slug: "wigilia",
    name: "Wigilia",
    title: "Bingo wigilijne",
    intro: "Od pierwszej gwiazdki do drzemki po makowcu. Karty rozdawać po barszczu.",
    squares: [
      "„U mamy karp był lepszy”",
      "Łuska karpia chowana do portfela",
      "„A kiedy ślub?”",
      "Drzemka po barszczu",
      "Spór: uszka z grzybami czy z kapustą",
      "Wujek liczy, czy jest dwanaście potraw",
      "„Ja wam powiem, jak jest”",
      "Instrukcja prezentu czytana na głos",
      "Telewizor włączony „tylko na chwilę”",
      "„Za moich czasów był prawdziwy śnieg”",
      "Pierwsza gwiazdka wypatrywana z zegarkiem",
      "Opowieść o ościach przy każdym kęsie",
      "Prezent: skarpety. Znowu.",
      "„Kto to tyle naszykował?”",
      "Jedzenie pakowane na wynos",
      "Dyskusja o cenach karpia",
      "Drzemka w fotelu z pilotem w ręce",
      "Kompot z suszu: połowa pije, połowa nie",
      "„W tym roku mało śniegu”",
      "Szczegółowe pytania o pracę",
      "Życzenia nagrywane telefonem w pionie",
      "Prezent z paragonem, „żeby wymienić”",
      "„Pierogi trochę za twarde”",
      "Pilot w foliowym woreczku",
      "„Mnie już nic nie trzeba”",
      "Ktoś siada przy talerzu dla wędrowca",
      "Spór, kto rozdaje prezenty",
      "„Kiedyś choinki były prawdziwe”",
      "Śledź w trzech wersjach, każda „najlepsza”",
      "Telefon z życzeniami na głośniku",
      "Makowiec znika przed kolacją",
      "„Jedzenia starczy do Sylwestra”",
      "Pytanie, czy karp pływał w wannie",
      "Rozmowa o tym, kto przyjedzie na drugi dzień",
    ],
  },
  {
    slug: "majowka",
    name: "Długi weekend",
    title: "Bingo majówkowe",
    intro: "Grill, działka, prognoza co kwadrans. Gra kończy się, kiedy zacznie padać.",
    squares: [
      "Rozpalanie bez podpałki w żelu",
      "Spór, kiedy przewrócić karkówkę",
      "„W tym roku zimna majówka”",
      "Własny grill, bo „na tym się nie da”",
      "Prognoza sprawdzana co kwadrans",
      "Opowieść o korku na zakopiance",
      "Fartuch „Mistrz grilla”",
      "Kiełbasa przypalona „specjalnie”",
      "Dmuchanie w węgiel do utraty tchu",
      "„U nas na działce jest lepiej”",
      "Leżak rozkładany przez dziesięć minut",
      "Kłótnia o muzykę z głośnika",
      "Sałatka jarzynowa w maju",
      "Rozmowa o komarach",
      "Worek węgla jednak za mały",
      "Sąsiad zagląda przez płot",
      "Ocena cudzego grilla",
      "Deszcz punktualnie o 15:00",
      "„Ja bym w góry pojechał”",
      "Szaszłyki bez warzyw",
      "Drzemka z gazetą na twarzy",
      "Rozmowa o cenie paliwa",
      "Kosiarka sąsiada o 8:00",
      "Szczypce zostawione na ruszcie",
      "Dwie musztardy i spór o trzecią",
      "„Karkówka musi odpocząć”",
      "Folia aluminiowa na ruszcie",
      "Ile kosztował grill, ze szczegółami",
      "Wykład o rozpalaniu ognia",
      "Kurtka zakładana o 18:00",
      "Plan na jutro: to samo",
      "Grill czyszczony dopiero w czerwcu",
    ],
  },
  {
    slug: "morze",
    name: "Nad morzem",
    title: "Bingo plażowe",
    intro: "Od parawanu o świcie do gofrów o zachodzie. Gra się między falochronami.",
    squares: [
      "Parawan rozstawiony przed 7:00",
      "Skarpety do sandałów",
      "„Za te pieniądze to w Grecji…”",
      "Woda „orzeźwiająca”, 14 stopni",
      "Narzekanie na cenę gofrów",
      "Parking za 30 zł i komentarz",
      "Kanapki z jajkiem na plaży",
      "Gazeta na twarzy przy opalaniu",
      "Mewa kradnie frytkę",
      "„Tu wiało, przenosimy się”",
      "Leżak rozkładany piętnaście minut",
      "Radio na plaży",
      "Kąpielówki z 1998 roku",
      "Spór o miejsce na parawan",
      "„Bałtyk jest najzdrowszy”",
      "Ktoś zakopany w piasku po szyję",
      "Materac dmuchany ustami",
      "Muszelka z napisem „Pozdrowienia”",
      "Pobudka o 5:30, „żeby zdążyć”",
      "Saszetka z dokumentami na brzuchu",
      "Czterdzieste zdjęcie zachodu słońca",
      "Ocena ryby w smażalni",
      "Wujek płynie „do boi” i z powrotem",
      "„Jutro będzie lepsza pogoda”",
      "Kłótnia, kto pilnuje rzeczy",
      "Ręcznik zostawiony na noc",
      "„W Chałupach jest lepiej”",
      "Rozmowa z sąsiadem zza parawanu",
      "Parawan pożyczony od sąsiada",
      "Temperatura wody sprawdzana w aplikacji",
      "Kapelusz kupiony na deptaku",
      "Opalenizna w kształcie koszulki",
    ],
  },
  {
    slug: "imieniny",
    name: "Imieniny",
    title: "Bingo imieninowe",
    intro: "Od kapci w przedpokoju do pożegnania w przedpokoju. Karty rozdawać po pierwszym „Sto lat”.",
    squares: [
      "„Nie zdejmujcie butów!” Wszyscy zdejmują",
      "Kapcie dla gości o dwa numery za małe",
      "Sałatka jarzynowa w kryształowej misie",
      "Podświetlany barek w meblościance",
      "Wujek puka w meblościankę: „Lite drewno”",
      "Pięć osób na wersalce dla trzech",
      "Krzesła pożyczone od sąsiadów",
      "Taboret z kuchni dla najmłodszego",
      "Telewizor chodzi cały wieczór bez głosu",
      "„Sto lat” zaczęte za wysoko",
      "Drugie „Sto lat”, bo ktoś się spóźnił",
      "Widelec o kieliszek: wujek prosi o ciszę",
      "„Tylko dwa słowa”. Mówi pół godziny",
      "„A co u ciebie w pracy?”",
      "„A ile ci tam płacą? Na rękę?”",
      "Cudza pensja liczona na serwetce",
      "„Ja w twoim wieku miałem już mieszkanie”",
      "Porównywanie rachunków za ogrzewanie",
      "Nóżki w galarecie: je tylko wujek",
      "Na obrusie cerata, „żeby się nie zaplamił”",
      "Szukanie wazonu na trzeci bukiet",
      "Bombonierka z zeszłych imienin",
      "„Urodziny? U nas się obchodziło imieniny”",
      "„Gdzie zaparkowałeś? Tam nie wolno”",
      "Narada mężczyzn na balkonie",
      "Kieliszki z trzech różnych kompletów",
      "Herbata w szklance z koszyczkiem",
      "Sąsiad stuka w kaloryfer o 22:00",
      "Pożegnanie w przedpokoju trwa godzinę",
      "„Daj śrubokręt, zaraz to dokręcę”",
      "„Kto wam kładł te płytki?”",
      "Tort podany, kiedy nikt już nie może",
      "Spór, czy do sałatki daje się jabłko",
      "Album ze zdjęciami wyjęty po torcie",
    ],
  },
  {
    slug: "podroz",
    name: "Podróż autem",
    title: "Bingo w podróży",
    intro: "Od pakowania bagażnika do stacji, która „zaraz będzie”. Gra się na tylnym siedzeniu, po cichu.",
    squares: [
      "„Kto otworzył okno?”",
      "„Zaraz będzie stacja”, od stu kilometrów",
      "„Tu kiedyś była dziura”",
      "„Nie wyprzedzaj mnie”, i dodaje gazu",
      "Nawigacja wyciszona po trzecim „zawróć”",
      "Atlas samochodowy z 1997 roku",
      "Kanapki zawinięte w sreberko",
      "Jajka na twardo i sól w papierku",
      "„Patrz, jak on jedzie”",
      "„Prawko to on chyba z chipsów ma”",
      "Ocenianie kierowców po rejestracji",
      "„Kto prowadzi, ten wybiera radio”",
      "Radio trzeszczy, ale „zaraz złapie”",
      "Średnia prędkość podawana co godzinę",
      "„Siku przed wyjazdem, bo nie stajemy”",
      "„Na suwak? Niech stoi jak wszyscy”",
      "Jazda lewym pasem od samej Łodzi",
      "Mruganie długimi, bo „za zakrętem stoją”",
      "Klimatyzacja wyłączona, „bo więcej pali”",
      "Tankowanie do równej kwoty, co do grosza",
      "Spalanie podane z dokładnością do setnej",
      "Wykład o trzymaniu kierownicy",
      "„Jeszcze kawałek”, i tak przez 200 km",
      "Termos z herbatą na leśnym parkingu",
      "Tata nie pyta o drogę, bo „wie”",
      "Skrót, który wydłuża trasę o godzinę",
      "„Tyle za autostradę? Rozbój w biały dzień”",
      "Bagażnik pakuje tylko tata. Według planu",
      "Propozycja zmiany za kółkiem: odrzucona",
      "Szyba myta przy każdym tankowaniu",
      "Kopnięcie w oponę na każdym postoju",
      "„Maluchem to się jechało dwa dni”",
      "Hamowanie tuż przed fotoradarem",
      "„Hot dog za tyle? Zjemy kanapki”",
    ],
  },
];

/** The free centre square, the same on every card. */
export const FREE_SQUARE = "„Za moich czasów…”";

/* Editions: the Polish occasions above with each edition's text laid over them. */

const EDITIONS = {
  pl: { occasions: OCCASIONS, free: FREE_SQUARE },
  sl: { occasions: overlayList("bingo.OCCASIONS", OCCASIONS, (occasion) => occasion.slug, sl.OCCASIONS), free: sl.FREE_SQUARE },
} satisfies Record<Locale, { occasions: Occasion[]; free: string }>;

/** The occasions in the edition's language: same order, slugs and pools (by index) as OCCASIONS. */
export const getOccasions = (locale: Locale): Occasion[] => EDITIONS[locale].occasions;

/** The free centre square in the edition's language. */
export const freeSquare = (locale: Locale): string => EDITIONS[locale].free;
