/*
 * Kartka z kalendarza (/kalendarz): what the Institute's tear-off calendar prints. Content is
 * picked by the date (src/lib/tear-off.ts), so the lists repeat in different combinations.
 * No saints, no church feasts and no real holidays: the calendar has its own observances.
 */

/** Rhymed proverbs, ten per month, January first: PROVERBS[0] is January. The two lines are joined with " / ". */
export const PROVERBS: string[][] = [
  [
    "Gdy w styczniu trzaska mróz, / tata pół godziny grzeje wóz.",
    "Gdy na drodze leży śnieg, / tata ma na wszystko drugi bieg.",
    "Gdy minus dwadzieścia na termometrze, / tata wynosi śmieci w samym swetrze.",
    "W styczniu w domu się nie grzeje, / w styczniu się zakłada sweter i nadzieję.",
    "Postanowienia tata spisuje w kalendarzu, / a ten kalendarz od lutego leży w garażu.",
    "Kto w styczniu pierwszy odśnieży podjazd, / ten do wiosny komentuje cudzy wyjazd.",
    "Choinka w styczniu gubi igły w dywanie, / a tata mówi: „Postoi, nic się nie stanie”.",
    "Gdy w styczniu studniówki i bale, / tata opowiada, jak tańczył poloneza wspaniale.",
    "Kto w styczniu na grillu kiełbasę opieka, / ten na majówkę już na nic nie czeka.",
    "Styczniowy rachunek za prąd i grzanie / tata czyta rodzinie na głos, na śniadanie.",
  ],
  [
    "Gdy w lutym mróz na całego, / tata sprawdza akumulator, ale u sąsiada, nie swojego.",
    "Luty krótki, ale srogi: / tata odśnieża tylko połowę drogi.",
    "W walentynki kwiat z przeceny, / bo pachnie tak samo, a nie ma tej ceny.",
    "Gdy w lutym sople wiszą u rynny, / tata wie dokładnie, kto jest winny.",
    "W lutym ferie, w lutym stok: / tata zjeżdża pługiem, jak co rok.",
    "W lutym tata w garażu siedzi przy piecyku / i sortuje śrubki w słoikach, w równym szyku.",
    "Gdy w lutym zamarznie w piwnicy rura, / tata grzeje ją suszarką, a mama: „Gdzie moja fryzura?”",
    "Gdy w lutym kot śpi na kaloryferze, / tata mówi, że grzeje się dla kota, i w to wierzy.",
    "Gdy na parkingu w lutym lód jak szkło, / tata staje na dwóch miejscach, bo „tak wyszło”.",
    "Kto w lutym do skarpet sandały przymierza, / ten w lipcu wie dokładnie, w co się ubrać zamierza.",
  ],
  [
    "W marcu jak w garncu: / tata ma czapkę, parasol i krem z filtrem w pokrowcu.",
    "W marcu zegary trzeba przestawić, / tata przestawia wszystkie, a w aucie każe zostawić.",
    "Kto w marcu zimowe opony zdejmuje, / ten w kwietniu od taty wykład otrzymuje.",
    "W marcu tata na działce kopie grządki, / a sąsiadowi przez płot tłumaczy porządki.",
    "W marcu porządki w piwnicy trwają do nocy: / tata przekłada kartony z kąta w kąt, bez niczyjej pomocy.",
    "W marcu za oknem jeszcze szaro, / a tata sieje pomidory na parapecie, z wiarą.",
    "Marcowy wiatr, marcowa słota, / a tata już rozpala grilla, bo to sobota.",
    "Kto w marcu parawan z piwnicy wynosi, / ten nad morzem w lipcu o miejsce nie prosi.",
    "Gdy w marcu śnieg jeszcze spadnie, / tata mówi: „A nie mówiłem?” i pamięta to dokładnie.",
    "Gdy kolano w marcu deszcz przepowiada, / tata zdejmuje pranie, zanim prognoza cokolwiek powiada.",
  ],
  [
    "Kwiecień plecień, wszystko przeplata, / a tata w sandałach, bo według niego to lato.",
    "Na prima aprilis tata żart opowiada, / ten sam od lat: rodzina się śmieje, bo tak wypada.",
    "Kto w kwietniu opony na letnie zakłada, / ten od taty słyszy, że w maju śnieg jeszcze spada.",
    "W kwietniu pierwszy grill sezon otwiera, / tata pierwszą kiełbasę z rusztu sam wybiera.",
    "Gdy w kwietniu przymrozek na kwiatach, / tata okrywa jabłonkę firanką, jak w dawnych latach.",
    "W kwietniu rower wyjmuje się z piwnicy, / tata pompuje koła i jedzie do sklepu na końcu ulicy.",
    "Gdy sąsiad w kwietniu kosi trawę jako pierwszy, / tata kosi tego samego dnia, tylko krócej i szerzej.",
    "Kto w kwietniu na przegląd jedzie do „swojego”, / ten wraca z pieczątką i bez niczego złego.",
    "Gdy w kwietniu raz śnieg, a raz pogoda, / tata wozi w bagażniku łopatę i parawan: miejsca nie szkoda.",
    "W kwietniu na działce pali się liście, / a sąsiad dzwoni po straż, oczywiście.",
  ],
  [
    "Majówka bez grilla to tylko wolne, / tata trzyma szczypce, a reszta ma ręce swobodne.",
    "W maju, gdy kwitną kasztany, / tata ma urlop nad morzem dawno zaplanowany.",
    "W połowie maja wracają chłody, / tata sadzi pomidory później, nie dla mody.",
    "W maju matury piszą młodzi, / a tata mówi, że jego była trudniejsza, i o to chodzi.",
    "Majowy deszcz chleba dodaje, / a tata i tak podlewa, bo deszczu nie uznaje.",
    "Kto w maju sandały z szafy wyjmuje, / ten białe skarpety od razu kupuje.",
    "W maju pod marketem budowlanym tłok, / tata staje na dwóch miejscach, bo auto ma bok.",
    "Majowe słońce wszystko budzi, / tata wstaje o piątej i budzi ludzi.",
    "W sobotę w maju o siódmej rano / tata kosi trawę. Sąsiadów nie pytano.",
    "Gdy w maju burza grzmi nad działką, / tata wyjmuje antenę i siedzi z latarką.",
  ],
  [
    "W czerwcu dzieci niosą świadectwa z paskiem, / a tata mówi, że jego pasek był szerszy, i mówi to z naciskiem.",
    "W czerwcu wesela co sobota, / tata krawat na czoło wkłada, gdy przyjdzie ochota.",
    "Gdy w czerwcu mundial albo mistrzostwa Europy, / tata z kanapy strzela gole, aż drżą mu stopy.",
    "W czerwcu na działce wszystko rośnie, / tata mierzy cukinię i mówi o niej podniośle.",
    "Pod koniec czerwca zaczynają się wakacje, / tata już pakuje auto: ma na to swoje racje.",
    "W czerwcu komary nad wodą latają, / tata mówi, że go nie gryzą, bo komary tatę znają.",
    "Gdy w czerwcu upał, tata okna zamyka, / bo „ciepło wpada”, a zasłony to jego taktyka.",
    "Kto w czerwcu grilla codziennie rozpala, / ten w lipcu szczypiec dotknąć nie pozwala.",
    "Na Dzień Ojca krawat albo skarpety: / tata mówi, że nic nie potrzebuje, i bierze, niestety.",
    "Czerwcowe truskawki liczy się co rano, / żeby było wiadomo, ile zjedzono.",
  ],
  [
    "W lipcu parawan o szóstej trzydzieści, / bo potem na plaży nikt się nie zmieści.",
    "Nad morzem w lipcu smażona ryba: / tata pyta o cenę za sto gramów i mówi „chyba”.",
    "W lipcu klima w aucie wyłączona, / bo „więcej pali”: rodzina ugotowana, ale oszczędzona.",
    "W lipcu na kempingu jedno jest pewne: / tata poziomuje przyczepę, aż dzieci są senne.",
    "Gdy w lipcu na urlopie deszcz pada, / tata obiecuje słońce, bo tak mu kolano gada.",
    "W lipcu w korku tata zna objazd, / który kończy się w polu, ale to i tak lepszy przejazd.",
    "W upał tata pije gorącą herbatę, / bo „gorące chłodzi”, i ma na to teorię na całą chatę.",
    "W lipcu wczasy, w lipcu ośrodek: / tata o siódmej zajmuje stolik, sam środek.",
    "W lipcu wiśnie zrywa się z drabiny, / tata trzyma drabinę i mówi, jak zrywać, od godziny.",
    "W lipcu przy drodze bób i jagody, / tata porównuje ceny na każdym straganie, dla przygody.",
  ],
  [
    "W sierpniu morze najcieplejsze, / a tata mówi, że w osiemdziesiątym było cieplejsze.",
    "Gdy w sierpniu gwiazdy spadają z nieba, / tata życzy sobie miejsca pod blokiem: więcej nie trzeba.",
    "W sierpniu po deszczu grzyby są w lesie, / tata zna miejsca i tę tajemnicę w sercu niesie.",
    "W sierpniu śliwki węgierki w skrzynce, / tata smaży powidła w każdej wolnej chwilce.",
    "Po sierpniowym urlopie tata ma relację / o każdym korku, objeździe i każdej stacji.",
    "W sierpniu na działce pomidory, / tata nosi je sąsiadom, aż wszyscy mają wory.",
    "W sierpniu ostatni grill przed szkołą, / tata wspomina swoją szkołę: było trudniej, ale wesoło.",
    "Gdy w sierpniu osy krążą nad stołem, / tata ściga je gazetą z programem, z wielkim mozołem.",
    "W sierpniu w bloku remont u sąsiada, / tata staje w drzwiach: „Kto panu to tak układa?”",
    "Pod koniec sierpnia parawan wraca z plaży, / tata go myje i chowa do piwnicy, gdzie o lecie marzy.",
  ],
  [
    "Gdy wrzesień jesień przynosi, / tata już o termin na opony zimowe prosi.",
    "We wrześniu grzyby zbiera się od świtu, / tata wraca z koszem i z opowieścią pełną zachwytu.",
    "Gdy we wrześniu babie lato na łące, / tata wie, że zima będzie lekka, bo tak mówią zające.",
    "We wrześniu działka oddaje plony, / tata wozi cukinie, aż bagażnik zielony.",
    "Gdy we wrześniu ostatni raz kosi trawnik, / tata czyści kosiarkę z namaszczeniem, jak ławnik.",
    "We wrześniu wieczory coraz chłodniejsze, / tata zakłada sweter, a kaloryfery są coraz zimniejsze.",
    "We wrześniu jabłka spadają z jabłoni, / tata zbiera każde, a sąsiad się broni.",
    "Wrześniowy wieczór, mecz ligowy, / tata krzyczy na sędziego, choć telewizor nowy.",
    "Gdy jaskółki we wrześniu odlatują, / tata w piwnicy słoiki liczy i pilnuje.",
    "We wrześniu wracają zadania domowe, / tata tłumaczy je po swojemu i wszystkim kręci się w głowie.",
  ],
  [
    "W październiku zmienia się opony, / tata zmienił we wrześniu i jest zadowolony.",
    "Gdy w październiku rusza ogrzewanie, / tata zakręca kaloryfery: „Najpierw sweter, potem gadanie”.",
    "Gdy w październiku czas się zmienia, / tata ma w aucie dobrą godzinę, bez przestawienia.",
    "W październiku liście w ogrodzie / tata grabi codziennie, wbrew przyrodzie.",
    "W październiku pierwsze przymrozki, / tata okrywa róże workami po ziemniakach: to jego troski.",
    "W październiku tata kisi kapustę w beczce / i opowiada o niej przy każdej rodzinnej wycieczce.",
    "Październik złoty, las kolorowy, / a tata już liczy dni do Wigilii, gotowy.",
    "W październiku deszcze i słoty, / tata w garażu naprawia, co się da, z braku innej roboty.",
    "W październiku wieczory długie i ciemne, / tata ogląda programy o pociągach: wszystkie przyjemne.",
    "W październiku zbiera się kasztany, / tata robi z nich ludzika z wąsami, wyjątkowo udany.",
  ],
  [
    "Listopad, liście, deszcz i opad, / a tata mówi: „Kiedyś to był listopad”.",
    "W listopadzie za oknem szaro i buro, / tata uszczelnia okna taśmą, wyjątkowo ponuro.",
    "Gdy w listopadzie pierwszy śnieg poprószy, / tata skrobie szyby, choć słońce zaraz wszystko wysuszy.",
    "W listopadzie wieczory długie jak wąż, / tata opowiada o wakacjach, a rodzina słucha wciąż.",
    "Gdy w listopadzie grzeje kaloryfer, / tata go przykręca: „Grzeje dla sąsiada”. Taki ma szyfr.",
    "Gdy w listopadzie promocje w gazetce, / tata kupuje trzy wiertarki: druga za grosz, a trzecia w pakiecie.",
    "W listopadzie mgła i błoto, / a tata myje auto, bo sobota to sobota.",
    "Gdy w listopadzie śliwki w occie gotowe, / tata częstuje nimi gości: to sprawy honorowe.",
    "W listopadzie tata buduje karmnik dla ptaków, / z dachem, rynną i fundamentem: bez żadnych braków.",
    "W listopadzie rachunki za ogrzewanie rosną, / tata zakłada drugi sweter i czuje się jak wiosną.",
  ],
  [
    "W grudniu choinka, w grudniu karp w wannie, / tata go pilnuje do Wigilii, uważnie i starannie.",
    "W grudniu tata kupuje prezenty w ostatniej chwili / i mówi, że kiedyś prezentów nie było, a wszyscy się cieszyli.",
    "Gdy w grudniu lampki migają na balkonie, / tata liczy prąd i o dziesiątej gasi je po swojej stronie.",
    "W grudniu tata wybiera choinkę godzinę, / a potem bierze pierwszą z brzegu: tę jedyną.",
    "W grudniu w domu goście i rodzina, / a tata w garażu: tam jest spokój i jego godzina.",
    "W grudniu tata lampki z zeszłego roku / rozplątuje do nocy, w skupieniu i bez zbędnego kroku.",
    "Gdy w grudniu Indeks dobija do klinicznego, / to znaczy, że rodzina zjeżdża do stołu wigilijnego.",
    "W grudniu kartki z życzeniami pisze się ręcznie, / tata pisze wszystkie tak samo: krótko, zwięźle i niezręcznie.",
    "Gdy w grudniu śnieg sypie całą noc, / tata o piątej odśnieża, bo ma w sobie moc.",
    "W Sylwestra o północy tata strzela szampanem, / a o pół do pierwszej śpi w fotelu przed ekranem.",
  ],
];

/** "Porada na dziś": a household tip in the dziaders' own logic. */
export const TIPS: string[] = [
  "Paragon chowa się do portfela, a portfel do szuflady. Po trzech latach można wyrzucić portfel.",
  "Karton od telewizora trzyma się do końca gwarancji, a potem do końca telewizora. Potem przyda się do następnego.",
  "Światło gasi się w pokoju, z którego się wychodzi, nawet jeśli ktoś w nim jeszcze siedzi.",
  "Ciśnienie w oponach sprawdza się kopnięciem. Jeśli noga się odbije, wszystko jest w normie.",
  "Kaloryfer nie potrzebuje więcej niż dwójki. Reszta ciepła jest w swetrze, który leży w szafie.",
  "Wodę na herbatę gotuje się na jedną szklankę. Druga osoba może poczekać na swoją kolej.",
  "Reklamówkę po zakupach składa się w trójkąt i chowa do reklamówki z reklamówkami. Trójkąt zajmuje mniej miejsca niż kwadrat.",
  "Pilota od telewizora najlepiej przechowywać w foliowym woreczku. Woreczek wymienia się co cztery lata, pilota nigdy.",
  "Samochód myje się w sobotę rano, nawet jeśli w niedzielę ma padać. Deszcz spłukuje tylko brud, który już był.",
  "Do sklepu chodzi się z listą. Lista jest po to, żeby wiedzieć, czego się nie kupiło.",
  "Kiedy coś nie działa, najpierw się to wyłącza, a potem uderza z boku. Instrukcja jest w trzeciej kolejności.",
  "Okna myje się gazetą. Płyn do szyb to chemia, a gazeta to jeszcze informacja.",
  "Na działkę jedzie się z zapasem wody, choć na działce jest kran. Kran może nie chcieć.",
  "Słoiki po dżemie myje się i trzyma na zapas. Zapas słoików trzyma się na wypadek nowego dżemu.",
  "Gdy w telewizji zapowiadają deszcz, warto zapytać kolano. Kolano nie ma reklam.",
  "Benzynę tankuje się do pełna, nawet jeśli jest drożej niż wczoraj. Jutro może być jeszcze drożej.",
  "Śrubki sortuje się według rozmiaru w słoikach po kawie. Słoiki po kawie sortuje się według marki kawy.",
  "Gościom podaje się kapcie. Kapcie dla gości mają jeden rozmiar, który na każdego pasuje tak samo źle.",
  "Lodówkę zamyka się od razu. Zastanawiać się można przy zamkniętej.",
  "Mięso na grilla kupuje się dzień wcześniej, żeby karkówka mogła swoje odstać. Kiełbasa niczego nie musi.",
  "W samochodzie wozi się koc, linkę, łopatę i papierową mapę. Nawigacja może się nie znać, mapa nie ma zdania.",
  "Przed urlopem zakręca się wodę, gaz i cierpliwość. Cierpliwość odkręca się dopiero na miejscu.",
  "Wiadro na miejscu parkingowym nie jest śmieciem. Jest rezerwacją.",
  "Instrukcję obsługi przechowuje się w segregatorze, w koszulce. Przeczytać ją można, kiedy urządzenie przestanie działać.",
  "Telefon trzyma się w etui z klapką, a klapkę zamyka po każdej rozmowie. Ekran nie lubi przeciągów.",
  "Do restauracji idzie się po obiedzie w domu. Wtedy można spokojnie ocenić porcje.",
  "Bułki z przeceny zamraża się od razu. Po rozmrożeniu smakują jak bułki z przeceny, tylko później.",
  "Na wesele zabiera się kopertę i zeszyt. Koperta jest na prezent, zeszyt na koszty, długopis na wszelki wypadek.",
  "Kartka za wycieraczką powinna zawierać słowo „uprzejmie”. Bez niego to tylko kartka.",
  "Prąd oszczędza się wieczorem. Wystarczy jedna lampa, w pokoju z telewizorem, i telewizor.",
  "Do grilla nie trzeba rozpałki w żelu. Wystarczy gazeta z zeszłego tygodnia, zapałki i godzina dyskusji.",
  "Hydraulika wzywa się po trzeciej własnej naprawie. Wtedy przynajmniej wiadomo, czego nie robić.",
  "Aplikację w telefonie ustawia syn. Potem się jej nie rusza, żeby się nie rozstroiła.",
  "Przy promocji „druga sztuka gratis” kupuje się dwie sztuki. Trzecia też by się przydała, ale na trzecią nie ma promocji.",
  "Zegarek w samochodzie można zostawić na czasie zimowym. Przez pół roku i tak pokazuje dobrze.",
  "Szklanki po musztardzie są najtrwalsze w całym domu. Kryształy stoją w meblościance, szklanki po musztardzie pracują.",
  "Dywan odkurza się w sobotę, a trzepie raz w roku, na trzepaku. Trzepak to też mebel, tylko wspólny.",
  "Do urzędu dokumenty nosi się w koszulce foliowej. Urzędnik od razu widzi, że ma do czynienia z kimś przygotowanym.",
  "Przyczepę kempingową poziomuje się do skutku. Skutek przychodzi zwykle w dniu wyjazdu.",
  "Na wakacje wyjeżdża się o czwartej rano, żeby ominąć korki. O czwartej rano korki wyjeżdżają razem z nami.",
  "Grzyby zbiera się o świcie, a miejsc nie zdradza nikomu. Nawet grzybom.",
  "Gdy goście wychodzą, światło na klatce schodowej gasi się po trzecim piętrze. Dalej znają drogę.",
  "Nowy sprzęt podłącza się bez instrukcji. Jeśli zadziała, instrukcja była zbędna. Jeśli nie zadziała, była źle napisana.",
  "Sąsiadowi, który parkuje krzywo, zostawia się kartkę. Sąsiadowi, który parkuje prosto, też, na wszelki wypadek.",
  "Herbatę z jednej torebki parzy się dwa razy. Za drugim razem jest łagodniejsza i wychodzi taniej.",
  "Telewizor ogląda się z trzech metrów. Bliżej siada się tylko podczas meczu, żeby lepiej doradzać trenerowi.",
  "Kluczyki od samochodu wiesza się na gwoździu przy drzwiach. Gwóźdź jest jeden, żeby nikt się nie pomylił.",
  "Długopis w domu ma swoje miejsce. Jeśli go tam nie ma, ktoś go wziął i trzeba ustalić kto.",
  "Przed zakupem samochodu pyta się szwagra. Potem kupuje się inny, ale szwagier był zapytany.",
  "Na parapecie trzyma się poduszkę. Bez poduszki obserwacja podwórka jest niepełna i męcząca dla łokci.",
  "Paragon sprawdza się przy kasie, przy wyjściu i w domu. Za trzecim razem zwykle się zgadza.",
  "Przed burzą wyjmuje się antenę z telewizora. Telewizor jest stary, ale burza też.",
  "Na rodzinny obiad przychodzi się kwadrans przed czasem. Wtedy jest czas sprawdzić, co się zmieniło w meblościance.",
  "Wiertarkę pożycza się sąsiadowi z uprzejmości, a odbiera z wykładem o wierceniu.",
  "Kartkę z kalendarza zrywa się rano. Kto zrywa wieczorem, żyje na kredyt.",
  "Rachunek za prąd czyta się na głos, przy całej rodzinie. Wtedy każdy wie, kto zostawił ładowarkę w kontakcie.",
  "Kaloryfer odpowietrza się co roku, nawet jeśli grzeje. Kaloryfer musi wiedzieć, kto tu rządzi.",
  "Nowe buty rozchodzi się w domu, w kapciach. Kapcie są pod spodem, buty na wierzchu, i tak przez tydzień.",
  "W pociągu siada się przodem do kierunku jazdy. Tyłem jadą tylko ci, co się nie znają.",
  "Kosiarkę po sezonie czyści się dokładniej niż samochód. Samochód jeździ cały rok, kosiarka zasłużyła na odpoczynek.",
];

/** "Zalecenie Instytutu na dziś": one short imperative line. */
export const ORDERS: string[] = [
  "Dziś nie rozpalać grilla podpałką w żelu.",
  "Sprawdzić ciśnienie w oponach. Kopnąć dla pewności.",
  "Zgasić światło w pokoju, z którego się wyszło.",
  "Nie dotykać pilota bez zgody właściciela.",
  "Zapytać w kolejce tylko o jedną rzecz. Naprawdę jedną.",
  "Odłożyć szczypce na stół. Na minutę, dla ćwiczenia.",
  "Przeczytać instrukcję do pierwszego wykrzyknika.",
  "Powiedzieć „dzień dobry” sąsiadowi w słuchawkach. Raz.",
  "Nie komentować cudzego parkowania przed dziewiątą.",
  "Pozwolić nawigacji wybrać trasę. Bez dyskusji, do pierwszego zakrętu.",
  "Wynieść jeden karton z piwnicy. Nie wnosić dwóch.",
  "Nie mówić „za moich czasów” do obiadu.",
  "Odczytać temperaturę za oknem i jej nie komentować.",
  "Przepuścić kogoś w kolejce do kasy. Policzyć do dziesięciu.",
  "Sprawdzić, czy kaloryfer na pewno musi stać na dwójce.",
  "Napisać wiadomość małymi literami. Bez podpisu.",
  "Zrobić zrzut ekranu, a nie zdjęcie telewizora.",
  "Pochwalić czyjś grill gazowy. Szczerze, jeśli się da.",
  "Nie przestawiać niczego w cudzej kuchni.",
  "Kartkę za wycieraczkę zostawić w szufladzie. Niech poczeka.",
  "Zjeść obiad w restauracji bez uwag do kelnera.",
  "Nie pytać nikogo, ile dał za samochód.",
  "Policzyć reklamówki w reklamówce. Wynik zachować dla siebie.",
  "Wstać z fotela w samolocie dopiero przy otwartych drzwiach.",
  "Odebrać telefon od córki bez „kto mówi?”.",
  "Przejechać przez miasto bez trąbienia. Z wyjątkiem zielonego.",
  "Wysłuchać do końca jednej piosenki z tego wieku.",
  "Nie zaglądać do cudzego koszyka w sklepie.",
  "Usiąść przy grillu jako gość. Po prostu usiąść.",
  "Kupić jedną rzecz bez gazetki. Na próbę.",
  "Odłożyć poziomicę przed zmrokiem.",
  "Nie sprawdzać, czy sąsiad dobrze posegregował szkło.",
  "Zjeść bułkę w cenie regularnej. Instytut wie, że to trudne.",
  "Zadzwonić do kogoś bez „halo, słychać mnie?”.",
  "Pozwolić komuś innemu zerwać kartkę z kalendarza.",
  "Nie podpowiadać sędziemu w telewizorze, co ma gwizdać.",
  "Przyznać rację prognozie pogody. Raz, po cichu.",
  "Zostawić parawan w bagażniku do jutra.",
  "Oddać wiertarkę bez wykładu o wierceniu.",
  "Nie liczyć, ile kosztowało wesele. Ani jedno danie.",
];

/** Invented observances on fixed dates, "MM-DD". Never a real holiday, never 24–26 December. */
export const OBSERVANCES: { date: string; name: string; note: string }[] = [
  { date: "01-05", name: "Dzień Zapowiedzi Wyniesienia Choinki", note: "Choinkę zapowiada się wynieść. Termin ustala się później." },
  { date: "01-15", name: "Dzień Skrobania Szyb", note: "Obchodzony kartą od lodówki, bo skrobaczka jest w drugim samochodzie." },
  { date: "01-28", name: "Dzień Rozgrzewania Silnika", note: "Pół godziny na biegu jałowym, w imię tradycji i sąsiedzkiej ciekawości." },
  { date: "02-09", name: "Dzień Sortowania Śrubek", note: "Według rozmiaru, w słoikach po kawie. Nadmiar śrubek przechodzi do słoików po ogórkach." },
  { date: "02-15", name: "Dzień Kwiatów z Przeceny", note: "Dzień po wiadomym święcie wszystko jest o połowę tańsze. Kwiat to kwiat." },
  { date: "02-21", name: "Dzień Kabli Rozruchowych", note: "Kable pożycza się sąsiadowi razem z wykładem o akumulatorach." },
  { date: "03-07", name: "Dzień Kartonu od Telewizora", note: "Kartony trzyma się do końca gwarancji, a potem dłużej, bo się przydadzą." },
  { date: "03-22", name: "Dzień Wynoszenia Parawanu z Piwnicy", note: "Do lipca zostały trzy miesiące, ale przygotowanie to podstawa." },
  { date: "04-02", name: "Dzień Tego Samego Żartu", note: "Wczorajszy żart opowiada się dziś jeszcze raz, dla tych, którzy nie słyszeli." },
  { date: "04-09", name: "Dzień Pierwszego Koszenia", note: "Obchodzony w sobotę o siódmej rano, niezależnie od tego, jaki to dzień tygodnia." },
  { date: "04-18", name: "Dzień Swojego Diagnosty", note: "Diagnosta zna auto od lat i ogląda je z szacunkiem, z daleka." },
  { date: "05-08", name: "Dzień Szczypiec", note: "Szczypce przekazuje się tylko w wyjątkowych okolicznościach. Dziś takich nie ma." },
  { date: "05-20", name: "Dzień Białej Skarpety", note: "Do sandałów, rzecz jasna. Długość skarpety: do połowy łydki, bez dyskusji." },
  { date: "05-29", name: "Dzień Wspominania Majówki", note: "O majówce opowiada się do sierpnia. Od sierpnia opowiada się o urlopie." },
  { date: "06-05", name: "Dzień Cukinii", note: "Cukinię mierzy się, waży i rozdaje sąsiadom, którzy mają własne." },
  { date: "06-17", name: "Dzień Krawata na Czole", note: "Obchodzony po północy, przy stole wujków, na każdym weselu w kraju." },
  { date: "07-10", name: "Dzień Parawanu", note: "Parawan stawia się o 6:30, zanim słońce zdąży się zorientować." },
  { date: "07-19", name: "Dzień Poziomowania Przyczepy", note: "Kończy się, gdy pęcherzyk stanie na środku albo gdy zajdzie słońce." },
  { date: "07-29", name: "Dzień Ryby za Sto Gramów", note: "Cenę smażonej ryby czyta się na głos, z niedowierzaniem, dwa razy." },
  { date: "08-07", name: "Dzień Objazdu przez Pole", note: "Objazd jest zawsze krótszy, nawet jeśli jest dłuższy." },
  { date: "08-21", name: "Dzień Pomidora z Działki", note: "Pomidora z działki nie porównuje się z niczym, zwłaszcza ze sklepowym." },
  { date: "08-28", name: "Dzień Ostatniego Grilla przed Szkołą", note: "Kiełbasa ta sama, ale wszyscy mówią o zeszytach." },
  { date: "09-04", name: "Dzień Zeszytu w Kratkę", note: "Zeszyt w kratkę kupuje się na zapas, na wypadek rachunków do sprawdzenia." },
  { date: "09-18", name: "Dzień Milczącego Grzybiarza", note: "Miejsc się nie zdradza. Nawet w dniu święta." },
  { date: "09-26", name: "Dzień Reklamówki z Reklamówkami", note: "Dziś przelicza się zapasy. Wyniku nie podaje się do wiadomości publicznej." },
  { date: "10-01", name: "Dzień Otwarcia Instytutu", note: "1 października 2026 roku Instytut otworzył się dla publiczności. Szczypce oddano na jeden dzień." },
  { date: "10-02", name: "Narodowy Dzień Spisu", note: "Tego dnia ruszył Narodowy Spis Dziadersów. Każde badanie się liczy, anonimowo." },
  { date: "10-15", name: "Dzień Zimowych Opon", note: "Kto zmienił we wrześniu, ma dziś prawo do uśmiechu z wyższością." },
  { date: "10-24", name: "Światowy Dzień Kabla Nieznanego Przeznaczenia", note: "Kabel zostaje w szufladzie. Kiedyś się okaże, do czego jest." },
  { date: "11-07", name: "Dzień Uszczelniania Okien", note: "Wata, taśma i przekonanie, że ciepło ucieka tylko przez okna sąsiadów." },
  { date: "11-19", name: "Dzień Kartki za Wycieraczką", note: "Pisze się wielkimi literami, uprzejmie, na odwrocie paragonu." },
  { date: "11-28", name: "Dzień Swetra Zamiast Kaloryfera", note: "Kaloryfer zostaje na dwójce. Swetry wydaje się z szafy, po jednym na domownika." },
  { date: "12-08", name: "Dzień Rozplątywania Lampek", note: "Lampki z zeszłego roku rozplątuje się w skupieniu. Trwa to do zmroku albo dłużej." },
  { date: "12-15", name: "Dzień Karpia w Wannie", note: "Kąpiel w łazience przenosi się na po świętach. Karp ma pierwszeństwo." },
  { date: "12-30", name: "Dzień Planowania Sylwestra w Domu", note: "Plan jest prosty: telewizor, szampan o północy, sen o pół do pierwszej." },
];
