export type Status = "EX" | "EW" | "CR" | "EN" | "VU" | "NT" | "LC";

export const STATUSES: { code: Status; label: string }[] = [
  { code: "EX", label: "wymarły" },
  { code: "EW", label: "wymarły na wolności" },
  { code: "CR", label: "krytycznie zagrożony" },
  { code: "EN", label: "zagrożony" },
  { code: "VU", label: "narażony" },
  { code: "NT", label: "bliski zagrożenia" },
  { code: "LC", label: "najmniejszej troski" },
];

export type SpeciesKey =
  | "grill"
  | "parking"
  | "budowa"
  | "moto"
  | "wakacje"
  | "facebook"
  | "smart"
  | "dzialka"
  | "wedka"
  | "korpo"
  | "zeglarz"
  | "grzybiarz"
  | "przygraniczny"
  | "oszczednosciowy"
  | "uzdrowiskowy"
  | "gorski"
  | "festiwalowy"
  | "golebiarz"
  | "jurajski"
  | "meteorologiczny"
  | "krupowkowy"
  | "bieszczadzki";

export type Species = {
  key: SpeciesKey;
  code: string;
  /** URL segment. Stable: never change it once published. */
  slug: string;
  name: string;
  /** "7 objawów Dziadersa Grillowego". */
  genitive: string;
  /** Hybrid name halves, for species the test can diagnose: "Grillowo-Motoryzacyjny". */
  prefix?: string;
  suffix?: string;
  latin: string;
  authority: string;
  status: Status;
  statusNote: string;
  teaser: string;
  summary: string;
  description: string[];
  habitat: string;
  activity: string;
  calls: string[];
  enemies: string;
  fieldMarks: string;
  traits: { label: string; value: number }[];
  symptoms: string[];
  handling: string[];
  /** Activity per month, January to December, 0–3. */
  calendar: number[];
  related: SpeciesKey[];
  /** Voivodeship code for regional species. */
  region?: string;
  isNew?: boolean;
};

export const SPECIES: Species[] = [
  {
    key: "grill",
    code: "DZI-01",
    slug: "dziaders-grillowy",
    name: "Dziaders Grillowy",
    genitive: "Dziadersa Grillowego",
    prefix: "Grillowo",
    suffix: "Grillowy",
    latin: "Dziadersus grillensis",
    authority: "Nowak, 1989",
    status: "LC",
    statusNote: "Populacja rośnie od majówki do pierwszych przymrozków.",
    teaser: "Nie oddaje szczypiec.",
    summary:
      "Gatunek pospolity, aktywny od majówki do pierwszych przymrozków. Rozpoznawany po szczypcach, których nie oddaje nikomu.",
    description: [
      "Dziaders Grillowy jest najlepiej poznanym gatunkiem w Atlasie. Pojawia się wraz z pierwszym ciepłym weekendem i zajmuje stanowisko przy ruszcie, którego nie opuszcza do końca imprezy. Szczypce traktuje jak insygnia władzy: oddaje je wyłącznie w razie nagłej potrzeby i odbiera natychmiast po powrocie.",
      "Gatunek ma silnie rozwinięty zmysł oceny. Z odległości kilkunastu metrów rozpoznaje źle rozpalony grill, za wcześnie przewróconą karkówkę i podpałkę w żelu. Swoje obserwacje komunikuje głośno, zwykle zaczynając od słów „Nie tak się rozpala”.",
    ],
    habitat: "Ogrody, działki i balkony z widokiem na cudzy grill. Sezonowo cała Polska.",
    activity: "Przejmowanie szczypiec. Ocenianie, jak inni rozpalają.",
    calls: ["Nie tak się rozpala.", "Karkówka musi swoje odstać."],
    enemies: "Grill gazowy, rozpałka w żelu, gość, który przyniósł halloumi.",
    fieldMarks: "Fartuch z napisem. Szczypce trzymane w dłoni także z dala od rusztu.",
    traits: [
      { label: "Kontrola nad szczypcami", value: 97 },
      { label: "Nieufność wobec grilla gazowego", value: 91 },
      { label: "Gotowość do oddania rusztu", value: 6 },
    ],
    symptoms: [
      "Przejmuje szczypce, zanim gospodarz zdąży je odłożyć.",
      "Rozpala wyłącznie gazetą i zapałkami. Podpałka w żelu to dla niego „chemia”.",
      "Sprawdza karkówkę palcem i ogłasza, że jeszcze nie.",
      "Komentuje każdy cudzy grill w promieniu stu metrów.",
      "Ma fartuch z napisem i nosi go z dumą.",
      "Uważa, że kiełbasa z grilla gazowego to nie jest kiełbasa z grilla.",
      "Po wszystkim długo czyści ruszt, opowiadając o rusztach, które miał kiedyś.",
    ],
    handling: [
      "Nie podchodzić do rusztu bez zaproszenia.",
      "Chwalić karkówkę, nawet przypaloną.",
      "Nie wspominać o grillu gazowym ani o halloumi.",
    ],
    calendar: [0, 0, 0, 1, 3, 3, 3, 3, 2, 1, 0, 0],
    related: ["dzialka", "moto", "wakacje"],
  },
  {
    key: "parking",
    code: "DZI-02",
    slug: "dziaders-parkingowy",
    name: "Dziaders Parkingowy",
    genitive: "Dziadersa Parkingowego",
    prefix: "Parkingowo",
    suffix: "Parkingowy",
    latin: "Dziadersus parkingus",
    authority: "Wiśniewski, 1994",
    status: "LC",
    statusNote: "Populacja stabilna, silnie terytorialna.",
    teaser: "Parkuje na dwóch miejscach, żeby nikt nie obił.",
    summary:
      "Gatunek silnie terytorialny. Zajmuje dwa miejsca parkingowe naraz i broni trzeciego, które uważa za swoje od 1997 roku.",
    description: [
      "Dziaders Parkingowy żyje w ścisłym związku z miejscem postojowym. Pod blokiem ma „swoje” miejsce, do którego nie ma żadnego tytułu prawnego, ale którego broni z pełną determinacją. Pod marketem wybiera natomiast dwa miejsca naraz i ustawia samochód dokładnie na linii, żeby nikt nie obił drzwi.",
      "Gatunek prowadzi bogatą korespondencję. Kartki zostawiane za wycieraczkami cudzych samochodów należą do najlepiej udokumentowanych zjawisk w zbiorach Instytutu. Są pisane odręcznie, wielkimi literami i zawsze zawierają słowo „uprzejmie”.",
    ],
    habitat: "Parkingi pod blokami i marketami. W niedziele także przed kościołami.",
    activity: "Zajmowanie dwóch miejsc naraz. Pilnowanie „swojego” miejsca pod blokiem.",
    calls: ["To jest moje miejsce od dziewięćdziesiątego siódmego.", "Pan tu nie stanie."],
    enemies: "Strefa płatnego parkowania, kierowca SUV-a, malowanie nowych linii.",
    fieldMarks: "Wyjeżdżając, zostawia na miejscu wiadro.",
    traits: [
      { label: "Terytorialność", value: 96 },
      { label: "Precyzja parkowania", value: 31 },
      { label: "Znajomość przepisów", value: 12 },
    ],
    symptoms: [
      "Zna numery rejestracyjne wszystkich samochodów sąsiadów.",
      "Parkuje na dwóch miejscach, żeby nikt nie obił drzwi.",
      "Zostawia kartki za wycieraczkami. Zawsze odręcznie.",
      "Wyjeżdżając, zostawia na swoim miejscu wiadro albo krzesło.",
      "Krąży po parkingu, aż zwolni się miejsce przy samym wejściu.",
      "Uważa strefę płatnego parkowania za zamach na wolność.",
      "Wieczorem sprawdza z balkonu, czy samochód nadal stoi.",
    ],
    handling: [
      "Nie parkować na „jego” miejscu, nawet jeśli jest wolne od trzech tygodni.",
      "Nie zabierać wiadra.",
      "Na kartkę za wycieraczką nie odpowiadać kartką.",
    ],
    calendar: [3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3],
    related: ["moto", "korpo"],
  },
  {
    key: "budowa",
    code: "DZI-03",
    slug: "dziaders-budowlany",
    name: "Dziaders Budowlany",
    genitive: "Dziadersa Budowlanego",
    prefix: "Budowlano",
    suffix: "Budowlany",
    latin: "Dziadersus aedificator",
    authority: "Kamiński, 1991",
    status: "NT",
    statusNote: "Wypierany przez filmy instruktażowe w internecie.",
    teaser: "„Kto panu to tak zrobił?”",
    summary: "Ekspert od cudzych remontów. Na każdym placu budowy pyta: „Kto panu to tak zrobił?”.",
    description: [
      "Dziaders Budowlany najczęściej przebywa w marketach budowlanych, gdzie spędza sobotnie przedpołudnia na oglądaniu narzędzi, których nie kupi. Jeżeli kupi, to „na zapas”. W domu ma co najmniej trzy wiertarki i żadnego pasującego wiertła.",
      "Gatunek jest szczególnie aktywny w obecności fachowców. Stoi w drzwiach, obserwuje, komentuje i opowiada, jak sam robił to w 1994 roku. Własnych remontów zwykle nie kończy, ale ma do nich kompletny plan, narysowany ołówkiem stolarskim na kartonie.",
    ],
    habitat: "Place budowy, markety budowlane, cudze remonty.",
    activity: "Komentowanie pracy fachowców. Kupowanie narzędzi „na zapas”.",
    calls: ["Kto panu to tak zrobił?", "Ja bym to inaczej poprowadził."],
    enemies: "Płyta kartonowo-gipsowa, fachowiec z kosztorysem, poziomica laserowa.",
    fieldMarks: "Ołówek stolarski za uchem, ostatnio używany w 2003 roku.",
    traits: [
      { label: "Krytyka cudzych fug", value: 93 },
      { label: "Pewność siebie przy elektryce", value: 88 },
      { label: "Kończenie rozpoczętych remontów", value: 14 },
    ],
    symptoms: [
      "Pyta fachowca: „Kto panu to tak zrobił?”, nawet jeśli zrobił to ten sam fachowiec.",
      "Nosi ołówek stolarski za uchem. Także w kościele.",
      "Kupuje narzędzia „na zapas”.",
      "Remont łazienki zaczął w 2019 roku. Postęp: 70%.",
      "Ocenia fugi u znajomych, zanim zdejmie buty.",
      "Nie czyta instrukcji. Zostają mu „zapasowe” śrubki.",
      "Stuka knykciem w każdą ścianę i mówi „karton-gips” tonem diagnozy.",
    ],
    handling: [
      "Nie pytać o zdanie w sprawie remontu, chyba że ma się wolne popołudnie.",
      "Nie pożyczać mu poziomicy laserowej. Nie odda, bo „nie działa”.",
      "Chwalić stare fugi.",
    ],
    calendar: [1, 1, 2, 3, 3, 2, 2, 2, 3, 2, 1, 1],
    related: ["parking", "dzialka", "smart"],
  },
  {
    key: "moto",
    code: "DZI-04",
    slug: "dziaders-motoryzacyjny",
    name: "Dziaders Motoryzacyjny",
    genitive: "Dziadersa Motoryzacyjnego",
    prefix: "Motoryzacyjno",
    suffix: "Motoryzacyjny",
    latin: "Dziadersus automobilis",
    authority: "Kowalski, 1987",
    status: "LC",
    statusNote: "Lokalnie liczniejszy w okolicach stacji diagnostycznych.",
    teaser: "„Panie, tego już teraz nie robią.”",
    summary:
      "Gatunek pospolity na parkingach marketów budowlanych. Uważa, że silnik poniżej dwóch litrów to nieporozumienie.",
    description: [
      "Dziaders Motoryzacyjny ocenia ludzi po samochodach, a samochody po dźwięku zamykanych drzwi. Przed zakupem kopie w opony i nasłuchuje, choć nigdy nie wyjaśnił, czego. Uważa, że najlepsze samochody produkowano do 2004 roku, a wszystko, co powstało później, „ma za dużo elektroniki”.",
      "Silnie reaguje na automatyczne skrzynie biegów, samochody elektryczne i system start-stop, który wyłącza natychmiast po uruchomieniu silnika. Opony na zimowe zmienia zawsze przed pierwszym przymrozkiem i zawsze o tym informuje.",
    ],
    habitat: "Parkingi marketów budowlanych, garaże, grupy motoryzacyjne.",
    activity: "Podważanie zasadności silników poniżej dwóch litrów.",
    calls: ["Panie, tego już teraz nie robią.", "Diesel to jest diesel."],
    enemies: "Automatyczna skrzynia biegów, samochód elektryczny, system start-stop.",
    fieldMarks: "Przed zakupem kopie w opony. Brelok od samochodu, którego nie ma od 2004 roku.",
    traits: [
      { label: "Kopanie w opony przed zakupem", value: 94 },
      { label: "Nieufność wobec automatu", value: 88 },
      { label: "Tolerancja systemu start-stop", value: 4 },
    ],
    symptoms: [
      "Kopie w opony przed zakupem. I po zakupie.",
      "Wyłącza system start-stop przy każdym uruchomieniu silnika.",
      "Mówi „Panie, tego już teraz nie robią”.",
      "Pamięta cenę oleju napędowego z 2009 roku.",
      "Nosi brelok od samochodu, którego nie ma od dwudziestu lat.",
      "Pyta „A ile pali?” zamiast „Jak się jeździ?”.",
      "Uważa samochód elektryczny za zabawkę. Diesel to jest diesel.",
    ],
    handling: [
      "Nie chwalić automatycznej skrzyni biegów.",
      "Zapytać o ciśnienie w oponach. Rozmowa potrwa godzinę, ale będzie miła.",
      "Nie parkować obok niego zbyt blisko.",
    ],
    calendar: [1, 1, 2, 3, 2, 1, 2, 1, 2, 3, 3, 1],
    related: ["parking", "budowa", "grill"],
  },
  {
    key: "wakacje",
    code: "DZI-05",
    slug: "dziaders-wakacyjny",
    name: "Dziaders Wakacyjny",
    genitive: "Dziadersa Wakacyjnego",
    prefix: "Wakacyjno",
    suffix: "Wakacyjny",
    latin: "Dziadersus parawanus",
    authority: "Zieliński, 1999",
    status: "LC",
    statusNote: "W lipcu migruje nad morze. Wraca z kompletem magnesów na lodówkę.",
    teaser: "Parawan, sandały, skarpety. Godzina 6:30.",
    summary: "Gatunek migrujący. W lipcu pojawia się nad morzem, gdzie o 6:30 rozstawia parawan.",
    description: [
      "Dziaders Wakacyjny spędza jedenaście miesięcy w roku na planowaniu dwóch tygodni urlopu. Nad morzem jest wcześniej niż słońce: parawan stoi o 6:30, ręczniki leżą na leżakach o 6:45, a o 7:00 gatunek komentuje już ceny gofrów.",
      "Za granicą szuka czegoś, co przypomina schabowego. Jeżeli nie znajdzie, sięga po kanapki przywiezione z domu. Z każdego wyjazdu wraca z kompletem magnesów na lodówkę i opalenizną w kształcie koszulki.",
    ],
    habitat: "Pas nadmorski od Świnoujścia po Krynicę Morską. Sezonowo także Chorwacja.",
    activity: "Rozstawianie parawanu o świcie. Rezerwowanie leżaków ręcznikiem.",
    calls: ["Tu jest zajęte.", "Nad naszym morzem przynajmniej wiadomo, co się je."],
    enemies: "Zakaz parawanów, wiatr od morza, all inclusive bez schabowego.",
    fieldMarks: "Sandały ze skarpetą, saszetka na pasku, opalenizna w kształcie koszulki.",
    traits: [
      { label: "Wczesność rozstawienia parawanu", value: 95 },
      { label: "Opór wobec kremu z filtrem", value: 71 },
      { label: "Akceptacja cen gofrów", value: 7 },
    ],
    symptoms: [
      "Rozstawia parawan przed wschodem słońca.",
      "Rezerwuje leżaki ręcznikiem.",
      "Nosi sandały z białymi skarpetami frotte.",
      "Porównuje ceny gofrów z cenami z 1998 roku.",
      "W hotelu all inclusive szuka schabowego.",
      "Ma saszetkę na pasku, a w niej paszport, gotówkę i kanapkę.",
      "Mówi, że nad naszym morzem przynajmniej wiadomo, co się je.",
    ],
    handling: [
      "Nie rozstawiać parawanu w jego polu widzenia.",
      "Nie pytać o ceny gofrów.",
      "Przyjąć magnes na lodówkę z wdzięcznością.",
    ],
    calendar: [0, 0, 0, 0, 1, 2, 3, 3, 1, 0, 0, 0],
    related: ["grill", "facebook", "krupowkowy"],
  },
  {
    key: "facebook",
    code: "DZI-06",
    slug: "dziaders-facebookowy",
    name: "Dziaders Facebookowy",
    genitive: "Dziadersa Facebookowego",
    prefix: "Facebookowo",
    suffix: "Facebookowy",
    latin: "Dziadersus facebookensis",
    authority: "Lewandowski, 2012",
    status: "LC",
    statusNote: "Najszybciej rosnąca populacja w Atlasie.",
    teaser: "Udostępnia. Nie czyta. Komentuje wielkimi literami.",
    summary: "Najszybciej rosnąca populacja w Atlasie. Udostępnia, zanim przeczyta, i komentuje wielkimi literami.",
    description: [
      "Dziaders Facebookowy żyje w grupach lokalnych, łańcuszkach i sekcjach komentarzy. Treści ocenia po tytule, a tytuły po tym, jak bardzo go zdenerwowały. Udostępnia „na wszelki wypadek”, zwykle z dopiskiem „UDOSTĘPNIJ, ZANIM USUNĄ!!!”.",
      "Gatunek ma zdjęcie profilowe z rybą albo z samochodem i podpisuje się imieniem i nazwiskiem pod każdym komentarzem, także pod własnym postem. Od kilku lat zasiedla również rodzinne komunikatory, gdzie co rano wysyła obrazki z kawą i życzeniami miłego dnia.",
    ],
    habitat: "Grupy lokalne, komentarze pod artykułami, łańcuszki.",
    activity: "Udostępnianie bez czytania. Pisanie wielkimi literami.",
    calls: ["UDOSTĘPNIJ, ZANIM USUNĄ!!!", "Kto pamięta?"],
    enemies: "Sprawdzanie faktów, link do źródła, wnuk tłumaczący, że to fotomontaż.",
    fieldMarks: "Zdjęcie profilowe z rybą albo z samochodem. Minimum trzy wykrzykniki.",
    traits: [
      { label: "Użycie caps locka", value: 92 },
      { label: "Wiara w łańcuszki", value: 78 },
      { label: "Czytanie artykułu przed komentarzem", value: 3 },
    ],
    symptoms: [
      "Pisze wielkimi literami. Także „Dzień dobry”.",
      "Udostępnia artykuły, których nie przeczytał.",
      "Stawia co najmniej trzy wykrzykniki.",
      "Pyta „Kto pamięta?” pod zdjęciem syfonu do wody sodowej.",
      "Co rano wysyła rodzinie obrazek z kawą.",
      "Podpisuje komentarze imieniem i nazwiskiem.",
      "Wierzy w łańcuszki. Na wszelki wypadek.",
    ],
    handling: [
      "Nie wysyłać mu linku do sprawdzania faktów. Zostanie udostępniony jako dowód spisku.",
      "Reagować serduszkiem. To wystarczy.",
      "Wyciszyć rodzinną grupę, zamiast z niej wychodzić.",
    ],
    calendar: [3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3],
    related: ["korpo", "smart", "festiwalowy"],
  },
  {
    key: "smart",
    code: "DZI-07",
    slug: "dziaders-smart-home",
    name: "Dziaders Smart-Home",
    genitive: "Dziadersa Smart-Home",
    prefix: "Technologiczno",
    suffix: "Technologiczny",
    latin: "Dziadersus technologicus",
    authority: "Wójcik, 2023",
    status: "VU",
    statusNote: "Gatunek młody, opisany w 2023 roku. Populacja zależna od wnuków.",
    teaser: "Inteligentne żarówki wyłącza wyłącznikiem.",
    summary: "Gatunek młody, opisany w 2023 roku. Kupuje inteligentne urządzenia i obsługuje je pstryczkiem.",
    description: [
      "Dziaders Smart-Home jest najmłodszym gatunkiem w Atlasie. Ma inteligentne żarówki, inteligentny odkurzacz i inteligentny termostat, a korzysta z nich wyłącznie ręcznie. Aplikację zainstalował wnuk, hasło do Wi-Fi wisi na karteczce pod routerem, a router na noc jest wyłączany, „żeby odpoczął”.",
      "Populacja jest silnie zależna od młodszych członków rodziny, wzywanych telefonicznie do każdej aktualizacji. Gatunek nie ufa chmurze, za to ufa dyskom zewnętrznym, które trzyma w szufladzie z kablami.",
    ],
    habitat: "Nowe osiedla, domy jednorodzinne z bramą na pilota.",
    activity: "Kupowanie inteligentnych urządzeń i obsługiwanie ich ręcznie.",
    calls: ["Wnuczek mi to ustawił.", "Po co mi aplikacja, jak jest pstryczek?"],
    enemies: "Aktualizacja oprogramowania, hasło do Wi-Fi, weryfikacja dwuetapowa.",
    fieldMarks: "Hasło do Wi-Fi na karteczce przyklejonej pod routerem.",
    traits: [
      { label: "Liczba urządzeń smart w domu", value: 84 },
      { label: "Zależność od wnuka", value: 97 },
      { label: "Korzystanie z aplikacji", value: 9 },
    ],
    symptoms: [
      "Inteligentne żarówki wyłącza wyłącznikiem.",
      "Wyłącza router na noc, żeby odpoczął.",
      "Trzyma hasło do Wi-Fi na karteczce pod routerem.",
      "Dzwoni, żeby sprawdzić, czy doszedł e-mail.",
      "Mówi do asystenta głosowego coraz głośniej.",
      "Robi telefonem zdjęcie ekranu komputera.",
      "Każdą aktualizację odkłada „na później”.",
    ],
    handling: [
      "Nie zmieniać hasła do Wi-Fi.",
      "Po instalacji aplikacji spisać wszystko na kartce. Wielkimi literami.",
      "Nie mówić mu, że odkurzacz może jeździć sam.",
    ],
    calendar: [3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3],
    related: ["facebook", "korpo", "budowa"],
    isNew: true,
  },
  {
    key: "dzialka",
    code: "DZI-08",
    slug: "dziaders-dzialkowy",
    name: "Dziaders Działkowy",
    genitive: "Dziadersa Działkowego",
    prefix: "Działkowo",
    suffix: "Działkowy",
    latin: "Dziadersus hortensis",
    authority: "Szymański, 1983",
    status: "LC",
    statusNote: "Altana z 1983 roku. Plany jej rozbudowy również.",
    teaser: "Altana z 1983 roku. Plany rozbudowy też.",
    summary: "Mieszkaniec rodzinnych ogrodów działkowych. Altana z 1983 roku, plany rozbudowy również.",
    description: [
      "Dziaders Działkowy spędza na działce czas od otwarcia sezonu w marcu do ostatniego dnia kopania marchwi. Prowadzi uprawy z rozmachem przemysłowym, a plony porównuje z plonami sąsiada zza siatki, któremu jednocześnie doradza, jak należy wiązać pomidory.",
      "Altana stanowi centrum terytorium. Zbudowana w 1983 roku z blachy, boazerii i drzwi od starej szafy, od 1983 roku czeka na rozbudowę. W środku stoi radio nastawione na jedną stację i wszystkie przedmioty, które „jeszcze się przydadzą”.",
    ],
    habitat: "Rodzinne ogrody działkowe. Altany z blachy i boazerii.",
    activity: "Porównywanie pomidorów. Doradzanie sąsiadom zza siatki.",
    calls: ["U mnie to już dawno zawiązane.", "Kiedyś to były pomidory."],
    enemies: "Nornica, ślimak bez skorupy, zarząd ogrodu.",
    fieldMarks: "Słomkowy kapelusz. Radio nastawione na jedną stację od 1991 roku.",
    traits: [
      { label: "Rywalizacja pomidorowa", value: 91 },
      { label: "Kontrola nad sąsiednią miedzą", value: 77 },
      { label: "Tolerancja wobec kretów", value: 2 },
    ],
    symptoms: [
      "Porównuje swoje pomidory z pomidorami sąsiada. Na głos.",
      "Doradza zza siatki, nie pytany o zdanie.",
      "Ma altanę z 1983 roku i plan jej rozbudowy z tego samego roku.",
      "Słucha radia nastawionego na jedną stację od 1991 roku.",
      "Przywozi rodzinie cukinie w ilościach hurtowych.",
      "Zna każdego kreta na działce. Żadnego nie toleruje.",
      "Uważa, że „kupne to nie to samo”.",
    ],
    handling: [
      "Przyjmować cukinię. Każdą.",
      "Nie chwalić pomidorów z supermarketu.",
      "Niczego w altanie nie dotykać.",
    ],
    calendar: [0, 0, 2, 3, 3, 3, 3, 3, 3, 2, 1, 0],
    related: ["grill", "budowa", "wedka"],
  },
  {
    key: "wedka",
    code: "DZI-09",
    slug: "dziaders-wedkarski",
    name: "Dziaders Wędkarski",
    genitive: "Dziadersa Wędkarskiego",
    prefix: "Wędkarsko",
    suffix: "Wędkarski",
    latin: "Dziadersus piscator",
    authority: "Dąbrowski, 1978",
    status: "NT",
    statusNote: "Ostoje znikają pod domkami letniskowymi.",
    teaser: "Wstaje o 4:00. Nie łowi nic. Wraca zadowolony.",
    summary: "Wstaje o czwartej, nie łowi nic i wraca zadowolony. Ryba, której nie złowił, była taka.",
    description: [
      "Dziaders Wędkarski prowadzi nocno-poranny tryb życia. O czwartej siedzi już nad wodą, w kamizelce z czternastoma kieszeniami, z termosem i w całkowitym milczeniu, które przerywa tylko po to, żeby powiedzieć, że dziś nie biorą.",
      "Gatunek słynie z opowieści. Złowione ryby rosną z każdym opowiadaniem, a te, które się urwały, osiągają rozmiary zagrażające żegludze. Naturalnym wrogiem jest kolega, który złowił więcej, i kajakarz, który „wszystko spłoszył”.",
    ],
    habitat: "Brzegi jezior, zalewy, kanały. Zawsze „sprawdzone miejsce”.",
    activity: "Wstawanie o czwartej. Milczenie. Niełowienie.",
    calls: ["Taka była.", "Dziś nie brały."],
    enemies: "Kajakarz, ciśnienie atmosferyczne, kolega, który złowił.",
    fieldMarks: "Kamizelka z czternastoma kieszeniami, termos, brak ryby.",
    traits: [
      { label: "Wczesność pobudki", value: 96 },
      { label: "Przesada w opisie złowionej ryby", value: 88 },
      { label: "Liczba złowionych ryb", value: 4 },
    ],
    symptoms: [
      "Wstaje o czwartej, także w niedzielę.",
      "Rozkłada ręce, opowiadając o rybie. Za każdym razem szerzej.",
      "Podsumowuje dzień słowami „dziś nie brały”.",
      "Ma kamizelkę z czternastoma kieszeniami i wie, co jest w każdej.",
      "Obwinia ciśnienie atmosferyczne.",
      "Ma „sprawdzone miejsce”, którego nie zdradzi nawet rodzinie.",
      "Wraca bez ryby, ale w doskonałym humorze.",
    ],
    handling: [
      "Nie pytać, ile złowił.",
      "Nie przepływać obok kajakiem.",
      "Gratulować ryby, której nikt nie widział.",
    ],
    calendar: [1, 1, 2, 3, 3, 3, 3, 3, 3, 2, 1, 1],
    related: ["dzialka", "zeglarz", "grzybiarz"],
  },
  {
    key: "korpo",
    code: "DZI-10",
    slug: "dziaders-korporacyjny",
    name: "Dziaders Korporacyjny",
    genitive: "Dziadersa Korporacyjnego",
    prefix: "Korporacyjno",
    suffix: "Korporacyjny",
    latin: "Dziadersus corporatus",
    authority: "Kaczmarek, 2008",
    status: "LC",
    statusNote: "Odporny na kolejne restrukturyzacje.",
    teaser: "Drukuje maile. Mówi „zróbmy calla”.",
    summary:
      "Gatunek biurowy. Drukuje maile, zwołuje spotkania, które mogły być mailem, i kończy każdą wiadomość „Pozdrawiam serdecznie”.",
    description: [
      "Dziaders Korporacyjny zasiedla biurowce klasy A, sale konferencyjne i biurko przy oknie, które zajmuje od czasów, gdy firma mieściła się w innym budynku. Mówi „zróbmy calla”, ale po każdym callu drukuje notatkę, którą następnie skanuje i rozsyła mailem.",
      "Gatunek jest odporny na kolejne restrukturyzacje, transformacje cyfrowe i zmiany komunikatorów. Pracy zdalnej nie uznaje: „Kiedyś to się pracowało, a nie home office”. W piątki nosi krawat, żeby pokazać, że piątek to też dzień roboczy.",
    ],
    habitat: "Biurowce klasy A, sale konferencyjne, biurko przy oknie.",
    activity: "Drukowanie maili. Zwoływanie spotkań, które mogły być mailem.",
    calls: ["Zróbmy calla.", "Kiedyś to się pracowało, a nie home office."],
    enemies: "Praca zdalna, komunikator firmowy, młodszy kierownik.",
    fieldMarks: "„Pozdrawiam serdecznie” w każdej wiadomości, także na czacie.",
    traits: [
      { label: "Spotkania, które mogły być mailem", value: 93 },
      { label: "Drukowanie maili", value: 86 },
      { label: "Zaufanie do chmury", value: 8 },
    ],
    symptoms: [
      "Drukuje maile, żeby je przeczytać.",
      "Kończy każdą wiadomość „Pozdrawiam serdecznie”, także na czacie.",
      "Zwołuje spotkanie, żeby omówić poprzednie spotkanie.",
      "Dzwoni, żeby zapytać, czy dotarł mail.",
      "Mówi „zróbmy calla”, a potem przychodzi osobiście.",
      "Ma w szufladzie zszywacz, którego nikomu nie pożycza.",
      "Uważa, że praca zdalna to urlop.",
    ],
    handling: [
      "Odpowiadać mailem na mail. Nie emotikoną.",
      "Nie przesuwać jego zszywacza.",
      "Na spotkaniu, które mogło być mailem, zachować spokój.",
    ],
    calendar: [2, 2, 2, 2, 2, 2, 1, 1, 3, 2, 2, 3],
    related: ["facebook", "smart", "parking"],
  },
  {
    key: "zeglarz",
    code: "DZI-11",
    slug: "dziaders-zeglarski",
    name: "Dziaders Żeglarski",
    genitive: "Dziadersa Żeglarskiego",
    latin: "Dziadersus nauticus",
    authority: "Kowalczyk, 1978",
    status: "NT",
    statusNote: "Ostatni rejs odbył w 1978 roku i od tego czasu o nim opowiada.",
    teaser: "„Pływam tu od siedemdziesiątego ósmego.”",
    summary:
      "Gatunek przybrzeżny Krainy Wielkich Jezior. Pływa tu od siedemdziesiątego ósmego, choć ostatni raz w siedemdziesiątym ósmym.",
    description: [
      "Dziaders Żeglarski zamieszkuje pomosty i tawerny Mazur, skąd z dezaprobatą obserwuje współczesne żeglarstwo. Każdą łódź ocenia po sposobie klarowania lin, każdą załogę po znajomości szant, a każdy wiatr po tym, czy „to jest prawdziwy wiatr”. Zwykle nie jest.",
      "Ostatni rejs gatunek odbył w 1978 roku i od tego czasu opowiada o nim z rosnącą liczbą szczegółów. Czapkę kapitańską nosi przez cały sezon, mimo braku jachtu, patentu i planów na ich zdobycie.",
    ],
    habitat: "Pomosty i tawerny Krainy Wielkich Jezior Mazurskich. Najliczniej w Giżycku i Mikołajkach.",
    activity: "Opowiadanie o rejsach. Ocenianie, jak inni klarują liny.",
    calls: ["Pływam tu od siedemdziesiątego ósmego.", "To nie jest prawdziwy wiatr."],
    enemies: "Motorówka, czarter z nawigacją w telefonie, zakaz wstępu na pomost.",
    fieldMarks: "Czapka kapitańska bez jachtu. Węzeł żeglarski na każdym sznurku w domu, łącznie z firanką.",
    traits: [
      { label: "Znajomość węzłów", value: 96 },
      { label: "Pewność siebie przy cudzym sterze", value: 91 },
      { label: "Tolerancja dla motorówek", value: 3 },
    ],
    symptoms: [
      "Nosi czapkę kapitańską, choć nie ma jachtu.",
      "Wiąże węzeł ratowniczy na sznurku od firanki.",
      "Ocenia z pomostu każdy manewr cudzej łodzi.",
      "Śpiewa szanty o 23:00. Wszystkie zwrotki.",
      "Twierdzi, że dzisiejszy wiatr to nie jest prawdziwy wiatr.",
      "Kuchnię nazywa kambuzem, a podłogę pokładem.",
      "O rejsie z 1978 roku opowiada co tydzień, za każdym razem dłużej.",
    ],
    handling: [
      "Nie cumować w jego obecności.",
      "Znać przynajmniej jedną szantę. Wystarczy refren.",
      "Nie pokazywać mu nawigacji w telefonie.",
    ],
    calendar: [0, 0, 0, 1, 2, 3, 3, 3, 1, 0, 0, 0],
    related: ["wedka", "wakacje"],
    region: "WN",
  },
  {
    key: "grzybiarz",
    code: "DZI-12",
    slug: "dziaders-grzybiarski",
    name: "Dziaders Grzybiarski",
    genitive: "Dziadersa Grzybiarskiego",
    latin: "Dziadersus fungorum",
    authority: "Sokołowski, 1985",
    status: "LC",
    statusNote: "Populacja eksploduje we wrześniu, po pierwszych porządnych deszczach.",
    teaser: "Zna miejsca. Nie powie.",
    summary: "Gatunek leśny, aktywny we wrześniu i październiku. Zna miejsca od czterdziestu lat i nie powie ich nikomu.",
    description: [
      "Dziaders Grzybiarski pojawia się w lesie przed świtem, w dniu po pierwszym porządnym deszczu. Porusza się szybko i bezszelestnie, a na pytania o drogę odpowiada wymijająco. Swoje stanowiska zna od czterdziestu lat i chroni je skuteczniej niż niejedno państwo swoje granice.",
      "Gatunek gardzi aplikacjami do rozpoznawania grzybów i atlasami, bo sam jest nieomylny, przynajmniej we własnej opinii. Po powrocie z lasu stawia koszyk w widocznym miejscu i czeka, aż ktoś zapyta. Na pytanie „Gdzie?” odpowiada „W lesie”.",
    ],
    habitat: "Lasy Podlasia, ze szczególnym uwzględnieniem Puszczy Knyszyńskiej. Dokładne stanowiska objęte tajemnicą.",
    activity: "Zbieranie grzybów przed świtem. Ukrywanie miejsc. Porównywanie koszyków.",
    calls: ["Ja te miejsca znam od czterdziestu lat.", "Tu kiedyś to rosły prawdziwki."],
    enemies: "Grzybiarz z aplikacją, susza, turysta, który „tylko spaceruje”.",
    fieldMarks: "Wiklinowy koszyk, nożyk z drewnianą rączką, kalosze nawet przy bezdeszczowej pogodzie.",
    traits: [
      { label: "Dyskrecja w sprawie miejsc", value: 99 },
      { label: "Wczesność wyjścia do lasu", value: 93 },
      { label: "Zaufanie do atlasu grzybów", value: 11 },
    ],
    symptoms: [
      "Wychodzi do lasu przed świtem, żeby nikt nie widział, dokąd idzie.",
      "Na pytanie „Gdzie?” odpowiada „W lesie”.",
      "Porównuje swój koszyk z cudzymi na leśnym parkingu.",
      "Mówi, że kiedyś to rosły prawdziwki.",
      "Grzyba zawsze kroi przy ziemi, nigdy nie wyrywa. I robi z tego wykład.",
      "Suszy grzyby na nitce nad kaloryferem.",
      "Zna miejsca od czterdziestu lat. Nie powie.",
    ],
    handling: [
      "Nie iść za nim do lasu.",
      "Nie pytać o miejsca.",
      "Przyjąć słoik suszonych grzybów i nie pytać o pochodzenie.",
    ],
    calendar: [0, 0, 0, 0, 1, 1, 2, 3, 3, 3, 1, 0],
    related: ["dzialka", "wedka", "meteorologiczny"],
    region: "PD",
  },
  {
    key: "przygraniczny",
    code: "DZI-13",
    slug: "dziaders-przygraniczny",
    name: "Dziaders Przygraniczny",
    genitive: "Dziadersa Przygranicznego",
    latin: "Dziadersus transfrontalis",
    authority: "Nowicki, 2004",
    status: "LC",
    statusNote: "Populacja wzrosła po 2004 roku, wraz z otwarciem granic.",
    teaser: "Jedzie 40 km, żeby zatankować 3 grosze taniej.",
    summary:
      "Gatunek wędrowny pasa przygranicznego. Pokonuje 40 kilometrów, żeby kupić coś 3 grosze taniej, i jest z tego dumny.",
    description: [
      "Dziaders Przygraniczny zamieszkuje województwo lubuskie i regularnie migruje za granicę po paliwo, kawę, proszek do prania i przekonanie, że „tam jest taniej”. Różnicę w cenie zna z dokładnością do grosza, ale koszt dojazdu konsekwentnie pomija.",
      "Z każdej wyprawy wraca z pełnym bagażnikiem i opowieścią o oszczędnościach, które wyliczył w drodze powrotnej. Szczególnie ceni zakupy hurtowe, bo „opłaca się, jak się weźmie więcej”.",
    ],
    habitat: "Pas przygraniczny województwa lubuskiego. Stacje paliw, targowiska i parkingi marketów po obu stronach granicy.",
    activity: "Porównywanie cen po obu stronach granicy. Tankowanie do pełna, także kanistrów.",
    calls: ["Tam jest taniej o trzy grosze.", "Opłaca się, jak się weźmie więcej."],
    enemies: "Kurs walut, kolejka na granicy, pytanie o koszt paliwa na dojazd.",
    fieldMarks: "Kanister w bagażniku. Paragony z dwóch krajów w schowku.",
    traits: [
      { label: "Precyzja porównywania cen", value: 97 },
      { label: "Wliczanie kosztów dojazdu", value: 4 },
      { label: "Wykorzystanie bagażnika", value: 100 },
    ],
    symptoms: [
      "Jedzie 40 km, żeby zatankować 3 grosze taniej.",
      "Wozi kanister. Na wszelki wypadek.",
      "Kupuje proszek do prania w opakowaniach na pięć lat.",
      "Pamięta kursy walut z ostatnich dwudziestu lat.",
      "Zna godziny, o których na granicy nie ma kolejki.",
      "Pomija koszt paliwa w rachunku oszczędności.",
      "Mówi „tam jest taniej” o każdym kraju sąsiednim.",
    ],
    handling: [
      "Nie liczyć przy nim kosztów dojazdu.",
      "Przyjąć zagraniczną kawę i okazać zdziwienie, że tak tanio.",
      "Nie wspominać o promocji w osiedlowym sklepie. Pojedzie sprawdzić.",
    ],
    calendar: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3],
    related: ["moto", "oszczednosciowy"],
    region: "LB",
  },
  {
    key: "oszczednosciowy",
    code: "DZI-14",
    slug: "dziaders-oszczednosciowy",
    name: "Dziaders Oszczędnościowy",
    genitive: "Dziadersa Oszczędnościowego",
    latin: "Dziadersus parsimoniosus",
    authority: "Grabowski, 1996",
    status: "LC",
    statusNote: "Populacja stabilna, aktywność rośnie w okresie przecen.",
    teaser: "Przechowuje reklamówki w reklamówce.",
    summary:
      "Gatunek wielkopolski. Przechowuje reklamówki w reklamówce, gasi światło za domownikami i zna wszystkie gazetki promocyjne.",
    description: [
      "Dziaders Oszczędnościowy prowadził gospodarkę obiegu zamkniętego, zanim stało się to modne. Reklamówki przechowuje w reklamówce, słoiki myje i segreguje według wielkości, a folię aluminiową wygładza i używa ponownie. Przed każdymi zakupami studiuje gazetki promocyjne z uwagą należną aktom prawnym.",
      "Gatunek gasi światło za domownikami, zakręca kran w trakcie mycia zębów i pilnuje, żeby okna nie były otwarte przy włączonym ogrzewaniu. Jest przy tym bardzo dumny i zwykle ma rację, co dodatkowo utrudnia dyskusję.",
    ],
    habitat: "Wielkopolska, ze szczególnym zagęszczeniem w Poznaniu. Promocje w promieniu dziesięciu kilometrów.",
    activity: "Gromadzenie reklamówek, słoików i gazetek promocyjnych. Gaszenie światła za innymi.",
    calls: ["Nie wyrzucaj, to się wypłucze.", "Zgaś światło, prąd nie jest za darmo."],
    enemies: "Opłata za reklamówkę, otwarte okno przy włączonym ogrzewaniu, paragon bez rabatu.",
    fieldMarks: "Reklamówka z reklamówkami pod zlewem. Słoiki posegregowane według wielkości.",
    traits: [
      { label: "Gromadzenie reklamówek", value: 98 },
      { label: "Znajomość gazetek promocyjnych", value: 94 },
      { label: "Wydatki bez wyraźnej potrzeby", value: 2 },
    ],
    symptoms: [
      "Przechowuje reklamówki w reklamówce.",
      "Gasi światło za każdym, kto wyszedł z pokoju.",
      "Myje folię aluminiową i używa jej ponownie.",
      "Zna gazetki promocyjne lepiej niż program telewizyjny.",
      "Segreguje słoiki według wielkości.",
      "Mówi „Nie wyrzucaj, to się wypłucze”.",
      "Pamięta, ile kosztował każdy przedmiot w domu.",
    ],
    handling: [
      "Nie wyrzucać reklamówek w jego obecności.",
      "Zgasić światło, zanim on to zrobi.",
      "Nie mówić, ile się zapłaciło.",
    ],
    calendar: [3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3],
    related: ["przygraniczny", "dzialka"],
    region: "WP",
  },
  {
    key: "uzdrowiskowy",
    code: "DZI-15",
    slug: "dziaders-uzdrowiskowy",
    name: "Dziaders Uzdrowiskowy",
    genitive: "Dziadersa Uzdrowiskowego",
    latin: "Dziadersus balnearius",
    authority: "Pietrzak, 1971",
    status: "LC",
    statusNote: "Populacja odnawia się co dwa tygodnie, w rytmie turnusów.",
    teaser: "Ciechocinek, tężnie, dancing. Więcej nie trzeba mówić.",
    summary: "Gatunek kuracyjny. Zasiedla tężnie i dancingi Ciechocinka w rytmie dwutygodniowych turnusów.",
    description: [
      "Dziaders Uzdrowiskowy pojawia się w uzdrowisku w rytmie turnusów i natychmiast przejmuje kontrolę nad ławką przy tężni. Rano wdycha solankę, po południu chodzi na zabiegi, a wieczorem wkłada marynarkę i rusza na dancing, gdzie prezentuje kroki opanowane w latach siedemdziesiątych.",
      "Gatunek prowadzi bogate życie towarzyskie. Każdy turnus kończy się wymianą adresów, obietnicą kontaktu i stwierdzeniem, że „na turnusie było lepiej niż w domu”. Po powrocie przez tydzień opowiada o zabiegach z dokładnością do minuty.",
    ],
    habitat: "Uzdrowiska, ze szczególnym uwzględnieniem Ciechocinka. Tężnie, deptaki i sale taneczne domów zdrojowych.",
    activity: "Wdychanie solanki przy tężniach. Dancingi. Porównywanie turnusów.",
    calls: ["Na turnusie było lepiej niż w domu.", "Pani pozwoli do tańca?"],
    enemies: "Koniec turnusu, deszcz na deptaku, orkiestra grająca za szybko.",
    fieldMarks: "Marynarka na dancing, karta zabiegów w kieszeni, opalenizna z ławki przy tężni.",
    traits: [
      { label: "Frekwencja na dancingach", value: 95 },
      { label: "Znajomość zabiegów", value: 88 },
      { label: "Chęć powrotu do domu", value: 9 },
    ],
    symptoms: [
      "Zajmuje ławkę przy tężni o siódmej rano.",
      "Ma marynarkę przeznaczoną wyłącznie na dancing.",
      "Zna nazwy wszystkich zabiegów i wie, na co pomagają.",
      "Prosi do tańca słowami „Pani pozwoli?”.",
      "Przywozi rodzinie wodę mineralną, której nikt nie wypije.",
      "Porównuje turnusy: „W zeszłym roku orkiestra była lepsza”.",
      "Po powrocie opowiada o zabiegach z dokładnością do minuty.",
    ],
    handling: [
      "Nie odmawiać tańca bez ważnego powodu.",
      "Pytać o zabiegi. Lubi o nich mówić.",
      "Nie siadać na jego ławce przy tężni.",
    ],
    calendar: [1, 1, 2, 2, 3, 3, 3, 3, 3, 2, 1, 1],
    related: ["festiwalowy", "wakacje"],
    region: "KP",
  },
  {
    key: "gorski",
    code: "DZI-16",
    slug: "dziaders-gorski",
    name: "Dziaders Górski",
    genitive: "Dziadersa Górskiego",
    latin: "Dziadersus montanus",
    authority: "Pawlak, 1988",
    status: "NT",
    statusNote: "Szlaki coraz częściej zajmują osoby w butach trekkingowych.",
    teaser: "Na Śnieżkę w sandałach. W każdym schronisku pyta, ile kosztuje herbata.",
    summary: "Gatunek wysokogórski Sudetów. Wchodzi na Śnieżkę w sandałach i w każdym schronisku komentuje cenę herbaty.",
    description: [
      "Dziaders Górski zdobywa szczyty Karkonoszy w sandałach, skarpetach i z poczuciem wyższości wobec osób w specjalistycznym obuwiu. Na szlaku porusza się zaskakująco szybko i wyprzedza turystów z kijkami, komentując, że kijki są „dla emerytów”, choć sam jest na emeryturze.",
      "W każdym schronisku gatunek zatrzymuje się, żeby zapytać o cenę herbaty, po czym wyciąga własny termos. Pamięta czasy, gdy na Śnieżkę szło się na piechotę z Karpacza, a herbata kosztowała tyle, co dziś wejście do toalety.",
    ],
    habitat: "Szlaki Karkonoszy i Gór Stołowych, schroniska, parkingi pod szlakami.",
    activity: "Zdobywanie szczytów w nieprzystosowanym obuwiu. Komentowanie cen w schroniskach.",
    calls: ["Ile za herbatę? Za moich czasów to było za darmo.", "Kiedyś szło się na piechotę z Karpacza."],
    enemies: "Cena herbaty w schronisku, wyciąg krzesełkowy, turysta z kijkami.",
    fieldMarks: "Sandały ze skarpetami na wysokości 1600 m n.p.m. Termos z herbatą, żeby nie płacić w schronisku.",
    traits: [
      { label: "Tempo podejścia", value: 84 },
      { label: "Przygotowanie sprzętowe", value: 7 },
      { label: "Komentowanie cen w schronisku", value: 98 },
    ],
    symptoms: [
      "Wchodzi na Śnieżkę w sandałach.",
      "W każdym schronisku pyta o cenę herbaty.",
      "Pije herbatę z własnego termosu na tarasie schroniska.",
      "Wyprzedza turystów z kijkami i komentuje kijki.",
      "Pamięta, ile kosztował nocleg w schronisku w 1985 roku.",
      "Uważa wyciąg za oszustwo.",
      "Na szczycie mówi: „Kiedyś było widać więcej”.",
    ],
    handling: [
      "Nie proponować wyciągu.",
      "Zabrać dla niego herbatę w termosie. Doceni gest i oszczędność.",
      "Nie komentować sandałów.",
    ],
    calendar: [1, 1, 1, 1, 2, 3, 3, 3, 3, 2, 1, 1],
    related: ["krupowkowy", "wakacje", "jurajski"],
    region: "DS",
  },
  {
    key: "festiwalowy",
    code: "DZI-17",
    slug: "dziaders-festiwalowy",
    name: "Dziaders Festiwalowy",
    genitive: "Dziadersa Festiwalowego",
    latin: "Dziadersus cantans",
    authority: "Szczepański, 1963",
    status: "LC",
    statusNote: "Co roku od nowa potwierdza, że kiedyś piosenki były lepsze.",
    teaser: "Co roku ogląda festiwal, żeby się upewnić, że kiedyś piosenki były lepsze.",
    summary: "Gatunek telewizyjny. Co roku ogląda festiwal piosenki, żeby się upewnić, że kiedyś piosenki były lepsze.",
    description: [
      "Dziaders Festiwalowy ogląda wszystkie festiwale piosenki, choć nie podoba mu się żaden. Robi to z poczucia obowiązku: ktoś musi potwierdzić, że kiedyś piosenki były lepsze, wykonawcy śpiewali, a nie krzyczeli, a prowadzący mówili wyraźnie.",
      "Gatunek zna refreny wszystkich przebojów sprzed 1985 roku i śpiewa je razem z telewizorem, nie znając zwrotek. Nowych wykonawców ocenia wyłącznie według tego, czy „to jest śpiewanie”. Zwykle nie jest.",
    ],
    habitat: "Przed telewizorem w czerwcu, w trakcie festiwalu piosenki. Okazjonalnie amfiteatry.",
    activity: "Oglądanie festiwali piosenki. Porównywanie wykonawców z wykonawcami sprzed lat.",
    calls: ["Kiedyś to były piosenki.", "To nie jest śpiewanie, to jest krzyczenie."],
    enemies: "Autotune, rap, prowadzący, który mówi za szybko.",
    fieldMarks: "Śpiewa refreny przebojów z lat siedemdziesiątych, nie znając zwrotek. Pilot w ręce, na wypadek reklam.",
    traits: [
      { label: "Znajomość refrenów sprzed 1985 roku", value: 97 },
      { label: "Tolerancja dla autotune'a", value: 3 },
      { label: "Głośność śpiewania z telewizorem", value: 82 },
    ],
    symptoms: [
      "Ogląda festiwal tylko po to, żeby go skrytykować.",
      "Mówi „Kiedyś to były piosenki”.",
      "Śpiewa refreny, nie znając zwrotek.",
      "Rozpoznaje autotune po pierwszej sekundzie.",
      "Uważa rap za mówienie do muzyki.",
      "Pamięta, kto wygrał festiwal w 1979 roku.",
      "Podgłaśnia tylko piosenki sprzed czterdziestu lat.",
    ],
    handling: [
      "Nie włączać rapu w samochodzie.",
      "Zapytać o ulubioną piosenkę z lat siedemdziesiątych. Usłyszy się ją w całości.",
      "Nie dyskutować o wynikach festiwalu.",
    ],
    calendar: [1, 1, 1, 1, 1, 3, 2, 2, 1, 1, 1, 3],
    related: ["uzdrowiskowy", "facebook"],
    region: "OP",
  },
  {
    key: "golebiarz",
    code: "DZI-18",
    slug: "dziaders-golebiarz",
    name: "Dziaders Gołębiarz",
    genitive: "Dziadersa Gołębiarza",
    latin: "Dziadersus columbarius",
    authority: "Kubica, 1952",
    status: "NT",
    statusNote: "Gołębniki ustępują miejsca parkingom.",
    teaser: "Gołębnik ma nowszy dach niż dom.",
    summary: "Gatunek śląski. Hoduje gołębie pocztowe, a gołębnik ma nowszy dach niż dom.",
    description: [
      "Dziaders Gołębiarz od kilkudziesięciu lat hoduje gołębie pocztowe i traktuje je z czułością, jakiej nie okazuje nikomu innemu. Gołębnik jest regularnie remontowany, ocieplany i odnawiany, podczas gdy dach domu czeka na swoją kolej od 1986 roku.",
      "W niedziele lotowe gatunek nie odchodzi od gołębnika i wypatruje powrotów z dokładnością do sekundy. Każdy powrót z zagranicy relacjonuje rodzinie ze szczegółami godnymi transmisji sportowej.",
    ],
    habitat: "Gołębniki na dachach i w ogrodach Górnego Śląska. Wystawy i loty konkursowe.",
    activity: "Hodowla gołębi pocztowych. Wypatrywanie powrotów. Remontowanie gołębnika.",
    calls: ["Wróciła! Z Holandii, w dziewięć godzin!", "Gołębie to nie jest hobby, to jest sport."],
    enemies: "Jastrząb, sąsiad narzekający na gołębie, deszczowa niedziela lotowa.",
    fieldMarks: "Zegar konkursowy na honorowym miejscu w domu. Gołębnik z nowym dachem obok domu ze starym.",
    traits: [
      { label: "Inwestycje w gołębnik", value: 98 },
      { label: "Znajomość rodowodów gołębi", value: 95 },
      { label: "Inwestycje w dach domu", value: 6 },
    ],
    symptoms: [
      "Gołębnik ma nowszy dach niż dom.",
      "W niedzielę lotową nie odchodzi od okna.",
      "Zna rodowody gołębi do piątego pokolenia.",
      "O gołębiach mówi „ona” i „on”, o sąsiadach „ci tam”.",
      "Uważa, że gołębie to sport, a nie hobby.",
      "Relacjonuje powrót gołębia z Holandii jak finał mundialu.",
      "Nienawidzi jastrzębi. Z wzajemnością.",
    ],
    handling: [
      "Nie mówić o gołębiach „ptaki”.",
      "Nie pytać o dach domu.",
      "W niedzielę lotową nie dzwonić.",
    ],
    calendar: [1, 1, 2, 3, 3, 3, 3, 3, 2, 1, 1, 1],
    related: ["dzialka", "wedka"],
    region: "SL",
  },
  {
    key: "jurajski",
    code: "DZI-19",
    slug: "dziaders-jurajski",
    name: "Dziaders Jurajski",
    genitive: "Dziadersa Jurajskiego",
    latin: "Dziadersus jurassicus",
    authority: "Kwiatkowski, 1999",
    status: "VU",
    statusNote: "Twierdzi, że widział, jak wymierały dinozaury, i nie zamierza być następny.",
    teaser: "Pamięta czasy, gdy wszystko było lepsze. Łącznie z dinozaurami.",
    summary:
      "Gatunek świętokrzyski o wyjątkowo długiej pamięci. Pamięta czasy, gdy wszystko było lepsze, łącznie z dinozaurami.",
    description: [
      "Dziaders Jurajski ma najdłuższą pamięć w Atlasie. Jego wspomnienia z każdym rokiem sięgają dalej: zaczynał od czasów PRL, przez okres międzywojenny, aż doszedł do jury, kiedy, jak twierdzi, wszystko było lepsze, większe i tańsze. Łącznie z dinozaurami.",
      "Gatunek zamieszkuje okolice Gór Świętokrzyskich, które uważa za jedne z najstarszych gór w Europie i jednocześnie za góry, które „kiedyś były wyższe”. Pierwsze twierdzenie jest prawdziwe. Drugie również, choć nie z powodów, które podaje.",
    ],
    habitat: "Góry Świętokrzyskie, okolice Łysicy, parki dinozaurów i jaskinie. Ławki pod sklepem w Kielcach.",
    activity: "Wspominanie dawnych czasów, sięgających coraz dalej wstecz.",
    calls: ["Za moich czasów to dopiero były dinozaury.", "Kiedyś góry były wyższe."],
    enemies: "Fakty historyczne, przewodnik z dyplomem, wnuk z encyklopedią.",
    fieldMarks: "Opowieści, które zaczynają się od „Za moich czasów” i sięgają mezozoiku.",
    traits: [
      { label: "Głębokość wspomnień", value: 100 },
      { label: "Zgodność wspomnień z faktami", value: 8 },
      { label: "Przywiązanie do Łysicy", value: 91 },
    ],
    symptoms: [
      "Każdą opowieść zaczyna od „Za moich czasów”.",
      "Jego „czasy” sięgają coraz dalej wstecz.",
      "Twierdzi, że kiedyś góry były wyższe. Ma rację, ale nie z tego powodu.",
      "Poprawia przewodników w parkach dinozaurów.",
      "Uważa, że dinozaury wymarły, bo nie umiały się dostosować.",
      "Nosi w kieszeni skamieniałość i pokazuje ją bez pytania.",
      "Mówi, że kiedyś to były gady.",
    ],
    handling: [
      "Nie prostować dat.",
      "Zachwycić się skamieniałością.",
      "Nie wspominać o asteroidzie.",
    ],
    calendar: [1, 1, 1, 2, 2, 3, 3, 3, 2, 1, 1, 1],
    related: ["festiwalowy", "gorski"],
    region: "SK",
  },
  {
    key: "meteorologiczny",
    code: "DZI-20",
    slug: "dziaders-meteorologiczny",
    name: "Dziaders Meteorologiczny",
    genitive: "Dziadersa Meteorologicznego",
    latin: "Dziadersus barometricus",
    authority: "Zając, 1979",
    status: "LC",
    statusNote: "Populacja stabilna, aktywność rośnie przy każdej zmianie ciśnienia.",
    teaser: "Prognozuje pogodę kolanem. Skuteczność: 54%.",
    summary: "Gatunek lubelski o rozwiniętym zmyśle barometrycznym. Prognozuje pogodę kolanem ze skutecznością 54%.",
    description: [
      "Dziaders Meteorologiczny prognozuje pogodę na podstawie stanu kolana, krzyża i blizny po operacji z 1987 roku. Według badań Instytutu jego prognozy sprawdzają się w 54% przypadków. Gatunek uważa to za wynik lepszy od telewizyjnego i dlatego prognoz w telewizji nie ogląda, chyba że po to, żeby je skomentować.",
      "Każda zmiana ciśnienia wywołuje u gatunku wzmożoną aktywność komunikacyjną. Na przystankach i ławkach przed domami prowadzi konsultacje meteorologiczne, które niezmiennie kończą się stwierdzeniem, że kiedyś to były zimy.",
    ],
    habitat: "Lubelszczyzna, ławki przed domami, przystanki autobusowe. Wszędzie, gdzie można omówić pogodę.",
    activity: "Prognozowanie pogody na podstawie dolegliwości. Komentowanie prognoz telewizyjnych.",
    calls: ["Będzie padać, czuję w kolanie.", "Kiedyś to były zimy."],
    enemies: "Synoptyk w telewizji, aplikacja pogodowa, słoneczny dzień, który kolano zapowiadało jako deszczowy.",
    fieldMarks: "Patrzy w niebo i mówi „idzie zmiana”. Barometr w przedpokoju, sprawdzany częściej niż telefon.",
    traits: [
      { label: "Zaufanie do własnego kolana", value: 99 },
      { label: "Skuteczność prognoz", value: 54 },
      { label: "Zaufanie do synoptyków", value: 12 },
    ],
    symptoms: [
      "Przepowiada deszcz kolanem.",
      "Ma barometr w przedpokoju i sprawdza go częściej niż telefon.",
      "Patrzy w niebo i mówi „idzie zmiana”.",
      "Komentuje prognozę w telewizji: „A skąd oni to wiedzą?”.",
      "Pamięta zimę 1979 roku z dokładnością do centymetra śniegu.",
      "Na pytanie „Jak się masz?” odpowiada „Ciśnienie spada”.",
      "Uważa, że kiedyś pogoda była bardziej pogodowa.",
    ],
    handling: [
      "Jeśli on tak mówi, zabrać parasol. Na wszelki wypadek.",
      "Nie pokazywać mu aplikacji pogodowej.",
      "Zapytać o zimę 1979 roku i usiąść wygodnie.",
    ],
    calendar: [3, 3, 2, 2, 1, 1, 2, 1, 1, 2, 2, 3],
    related: ["dzialka", "gorski", "grzybiarz"],
    region: "LU",
  },
  {
    key: "krupowkowy",
    code: "DZI-21",
    slug: "dziaders-krupowkowy",
    name: "Dziaders Krupówkowy",
    genitive: "Dziadersa Krupówkowego",
    latin: "Dziadersus tatricus",
    authority: "Gąsienica, 1974",
    status: "LC",
    statusNote: "Populacja osiąga szczyt w ferie i długie weekendy.",
    teaser: "Kupuje oscypka i mówi, że kiedyś był większy.",
    summary: "Gatunek tatrzański. Kupuje oscypka na Krupówkach i mówi, że kiedyś był większy.",
    description: [
      "Dziaders Krupówkowy przyjeżdża do Zakopanego od 1968 roku i od 1968 roku uważa, że kiedyś było lepiej. Oscypki były większe, ceny niższe, a górale prawdziwsi. Mimo to co roku kupuje oscypka, ciupagę i sweter z owczej wełny, który nosi potem w samochodzie przez cały sezon.",
      "Znaczną część pobytu gatunek spędza w korku na zakopiance, który komentuje z rosnącym oburzeniem i bez cienia refleksji, że sam w nim stoi. Po Krupówkach porusza się wolno, ogląda każde stoisko i porównuje ceny z zapamiętanymi z poprzedniej wizyty.",
    ],
    habitat: "Krupówki i okolice, Gubałówka, parkingi w Zakopanem, kolejka na Kasprowy Wierch.",
    activity: "Kupowanie oscypków, ciupag i swetrów z owczej wełny. Porównywanie cen z poprzednią wizytą.",
    calls: ["Kiedyś oscypek był większy.", "Ja tu przyjeżdżam od sześćdziesiątego ósmego."],
    enemies: "Korek na zakopiance, cena oscypka, parking za pięćdziesiąt złotych.",
    fieldMarks: "Trzecia ciupaga w kolekcji. Sweter z owczej wełny noszony w samochodzie także latem.",
    traits: [
      { label: "Kolekcja ciupag", value: 87 },
      { label: "Porównywanie cen oscypka", value: 96 },
      { label: "Cierpliwość w korku na zakopiance", value: 11 },
    ],
    symptoms: [
      "Mówi, że kiedyś oscypek był większy.",
      "Ma w domu co najmniej trzy ciupagi.",
      "Przyjeżdża do Zakopanego od 1968 roku.",
      "Stoi w korku na zakopiance i narzeka na korek na zakopiance.",
      "Porównuje cenę parkingu z ceną noclegu sprzed lat.",
      "W lipcu nosi w samochodzie sweter z owczej wełny.",
      "Co roku robi sobie zdjęcie z misiem na Krupówkach.",
    ],
    handling: [
      "Nie pytać o cenę oscypka. Powie.",
      "Nie proponować wyjazdu w Tatry w długi weekend.",
      "Przyjąć w prezencie ciupagę. Kolejną.",
    ],
    calendar: [3, 3, 1, 1, 2, 2, 3, 3, 1, 1, 1, 2],
    related: ["gorski", "wakacje", "bieszczadzki"],
    region: "MA",
  },
  {
    key: "bieszczadzki",
    code: "DZI-22",
    slug: "dziaders-bieszczadzki",
    name: "Dziaders Bieszczadzki",
    genitive: "Dziadersa Bieszczadzkiego",
    latin: "Dziadersus fugiens",
    authority: "Ostrowski, 1975",
    status: "LC",
    statusNote: "Populacja rośnie dzięki osobnikom, które rzuciły wszystko.",
    teaser: "Od 30 lat planuje rzucić wszystko i wyjechać w Bieszczady. Mieszka w Bieszczadach.",
    summary:
      "Gatunek podkarpacki. Od trzydziestu lat planuje rzucić wszystko i wyjechać w Bieszczady, w których mieszka.",
    description: [
      "Dziaders Bieszczadzki od trzydziestu lat planuje rzucić wszystko i wyjechać w Bieszczady. Ma spakowany plecak, zapuszczoną brodę i dopracowany plan. Jedyną przeszkodą jest to, że w Bieszczadach już mieszka, co komplikuje logistykę wyjazdu.",
      "Gatunek występuje także w formie rozproszonej na terenie całego kraju: jako osobniki, które w barach, na weselach i w pracy deklarują, że „rzucą wszystko i wyjadą w Bieszczady”. Według szacunków Instytutu robi to mniej niż jeden procent populacji. Reszta zostaje, ale ma plecak.",
    ],
    habitat: "Bieszczady, połoniny, okolice Wetliny i Cisnej. Także w planach mieszkańców całej Polski.",
    activity: "Planowanie rzucenia wszystkiego. Opowiadanie o tym w barze pod połoniną.",
    calls: ["Rzucę wszystko i wyjadę w Bieszczady.", "Tu jest prawdziwa wolność, panie."],
    enemies: "Zasięg sieci komórkowej, turyści z dużych miast, wiadomość od szefa.",
    fieldMarks: "Broda zapuszczona w ramach przygotowań. Plecak spakowany od 1993 roku.",
    traits: [
      { label: "Gotowość do rzucenia wszystkiego", value: 99 },
      { label: "Faktyczne rzucenie czegokolwiek", value: 2 },
      { label: "Zachwyt nad połoninami", value: 95 },
    ],
    symptoms: [
      "Od trzydziestu lat mówi, że rzuci wszystko i wyjedzie w Bieszczady.",
      "Trzyma spakowany plecak w przedpokoju.",
      "Zapuszcza brodę w ramach przygotowań.",
      "Wie, gdzie na połoninie nie ma zasięgu, i bardzo to chwali.",
      "Mówi „panie”, kiedy mówi o wolności.",
      "Ogląda w pracy zdjęcia połonin.",
      "Mieszka w Bieszczadach i nadal planuje do nich wyjechać.",
    ],
    handling: [
      "Nie pytać, kiedy w końcu wyjedzie.",
      "Zachwycić się połoninami.",
      "Nie pisać do niego po szesnastej. Duchem jest już w Bieszczadach.",
    ],
    calendar: [1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 1, 1],
    related: ["krupowkowy", "wedka", "korpo"],
    region: "PK",
  },
];

export const ESTIMATED_SPECIES = 312;

export const speciesByKey = (key: SpeciesKey) => SPECIES.find((species) => species.key === key)!;

export const speciesBySlug = (slug: string) => SPECIES.find((species) => species.slug === slug);

export const statusLabel = (status: Status) => STATUSES.find((item) => item.code === status)?.label ?? status;
