/** Slovenian URL slugs of the Komisja cases, keyed by the Polish slug. Never change a published slug. */
export const CASE_SLUGS: Record<string, string> = {
  "klucze-w-zamku": "kljuci-v-kljucavnici",
  "kartony-po-sprzetach": "skatle-za-selitev",
  "halo-w-wiadomosci": "halo-v-sporocilu",
  "recznik-na-lezaku": "brisaca-na-lezalniku",
  "stek-za-drogi": "biftek-predrag",
  "mecz-z-radiem": "tekma-z-radiem",
  "mycie-w-sobote": "pranje-v-soboto",
  "kontrola-segregacji": "nadzor-locevanja",
  "biuro-o-6-40": "pisarna-ob-6-40",
  "duza-czcionka": "najvecja-pisava",
  "zeszyt-weselny": "svatbeni-zvezek",
  "wstawanie-w-samolocie": "vstajanje-v-letalu",
  "reklamowki-w-kieszeni": "vrecke-v-zepu",
  "folia-na-fotelach": "folija-na-sedezih",
  "segregator-instrukcji": "registrator-navodil",
  "kto-mowi": "s-kom-govorim",
  "kalkulator-z-drukarka": "kalkulator-s-tiskalnikom",
  "dzien-dobry": "dober-dan",
  "zdjecie-telewizora": "vremenska-napoved",
  smacznego: "dober-tek",
  "przecena-pieczywa": "znizane-zemlje",
  "klodka-na-termostacie": "obesanka-na-termostatu",
  "zegar-w-samochodzie": "ura-v-avtu",
  "wielkie-litery": "velike-crke",
  "kubek-szefa": "loncek-sefa",
  "rekord-nad-morze": "rekord-do-morja",
  "lawka-pod-blokiem": "klop-pred-blokom",
  "rozmowy-na-glosniku": "telefon-na-zvocniku",
  "kolejka-przed-otwarciem": "vrsta-pred-trgovino",
  "prasowany-papier": "likanje-papirja",
};
