/** Slovenian URL slugs of the Atlas species, keyed by the Polish slug. Never change a published slug. */
export const SPECIES_SLUGS: Record<string, string> = {
  "dziaders-grillowy": "zarni-dziaders",
  "dziaders-parkingowy": "parkirni-dziaders",
  "dziaders-budowlany": "gradbeni-dziaders",
  "dziaders-motoryzacyjny": "avtomobilski-dziaders",
  "dziaders-wakacyjny": "pocitniski-dziaders",
  "dziaders-facebookowy": "facebookovski-dziaders",
  "dziaders-smart-home": "smart-home-dziaders",
  "dziaders-dzialkowy": "vrtickarski-dziaders",
  "dziaders-wedkarski": "ribiski-dziaders",
  "dziaders-korporacyjny": "korporativni-dziaders",
  "dziaders-zeglarski": "jadralski-dziaders",
  "dziaders-grzybiarski": "gobarski-dziaders",
  "dziaders-przygraniczny": "obmejni-dziaders",
  "dziaders-oszczednosciowy": "varcni-dziaders",
  "dziaders-uzdrowiskowy": "zdraviliski-dziaders",
  "dziaders-gorski": "gorski-dziaders",
  "dziaders-festiwalowy": "festivalski-dziaders",
  "dziaders-golebiarz": "golobarski-dziaders",
  "dziaders-jurajski": "jurski-dziaders",
  "dziaders-meteorologiczny": "meteoroloski-dziaders",
  "dziaders-krupowkowy": "krupowkovski-dziaders",
  "dziaders-bieszczadzki": "bieszczadski-dziaders",
  "dziaders-weselny": "svatbeni-dziaders",
  "dziaders-wigilijny": "svetovecerni-dziaders",
  "dziaders-parapetowy": "okenski-dziaders",
  "dziaders-kolejkowy": "cakalni-dziaders",
  "dziaders-kibicowski": "navijaski-dziaders",
  "dziaders-kempingowy": "kamperski-dziaders",
};
